"""Reproduce the pre-ice-fix GPU source/setting preservation audit without Unity.

Run this file with Python 3.10+ from any directory. The repository root is inferred
from this file. It only writes ice-contact-preservation-audit.json; historical
pre-F audits/manifests are read-only and are never regenerated by this script.
"""
from collections import defaultdict
from datetime import datetime, timezone
import hashlib
import json
from pathlib import Path
import re
import sys


ROOT = Path(__file__).resolve().parents[2]
FEATURE = ROOT / "Assets/_Project/Features/Bartending/FluidGpuExperiment"
EVIDENCE = ROOT / "FluidGpuExperimentEvidence"
SNAPSHOT = ROOT / "Library/IceContactOriginal/FluidGpuExperiment"
MANIFEST = EVIDENCE / "ice-contact-original-sha256.json"
OUTPUT = EVIDENCE / "ice-contact-preservation-audit.json"
CONTACT_MACRO = "COHESIVE_ICE_CONTACTS"
GUID = re.compile(r"^guid: ([a-fA-F0-9]{32})\s*$", re.MULTILINE)
KERNELS = {
    "SweepBoundaries": ("sweepKernel", "SweepCohesiveIceBoundaries"),
    "ApplyDeltaAndBoundaries": ("applyKernel", "ApplyCohesiveIceContacts"),
    "UpdateVelocities": ("velocityKernel", "UpdateCohesiveContactVelocities"),
}


def sha(path):
    return hashlib.sha256(path.read_bytes()).hexdigest().upper()


def read(path):
    return path.read_text(encoding="utf-8-sig")


def sha_text(value):
    return hashlib.sha256(value.encode("utf-8")).hexdigest().upper()


def without_comments(value):
    return re.sub(r"/\*.*?\*/|//[^\n]*", "", value, flags=re.DOTALL)


def select_contact_branch(source, enabled):
    """Select only the narrowly scoped contact macro, leaving other directives intact.

    Reject nested directives inside these blocks rather than silently pretending to
    be a general C preprocessor. The current blocks contain straight #if/#else code.
    """
    output, block, take = [], False, True
    blocks = 0
    for line in source.splitlines():
        directive = line.strip()
        if directive == f"#if defined({CONTACT_MACRO})":
            if block:
                raise ValueError("Nested contact macro block is not supported")
            block, take = True, enabled
            blocks += 1
        elif block and directive == "#else":
            take = not enabled
        elif block and directive == "#endif":
            block, take = False, True
        elif block and re.match(r"#\s*(?:if|ifdef|ifndef|elif)\b", directive):
            raise ValueError("Nested/elif directive needs an explicit audit update")
        elif take:
            output.append(line)
    if block:
        raise ValueError("Unclosed contact macro block")
    return "\n".join(output), blocks


def function_body(source, name):
    source = without_comments(source)
    match = re.search(r"\bvoid\s+" + re.escape(name) + r"\s*\(", source)
    if not match:
        raise ValueError(f"Kernel entry point missing: {name}")
    start = source.index("{", match.end())
    depth = 0
    for end in range(start, len(source)):
        if source[end] == "{":
            depth += 1
        elif source[end] == "}":
            depth -= 1
            if depth == 0:
                return re.sub(r"\s+", "", source[start:end + 1])
    raise ValueError(f"Kernel entry point not closed: {name}")


def main():
    original = json.loads(read(MANIFEST))
    snapshot_errors = [name for name, digest in original.items()
                       if not (SNAPSHOT / name).is_file() or sha(SNAPSHOT / name) != digest.upper()]
    changed = sorted(name for name, digest in original.items()
                     if not (FEATURE / name).is_file() or sha(FEATURE / name) != digest.upper())

    old_source = read(SNAPSHOT / "Shaders/FluidExperimentLiquid.compute")
    new_source = read(FEATURE / "Shaders/FluidExperimentLiquid.compute")
    legacy_source, legacy_blocks = select_contact_branch(new_source, False)
    contact_source, contact_blocks = select_contact_branch(new_source, True)
    buffers = re.sub(r"\s+", "", without_comments(read(FEATURE / "Runtime/FluidExperimentGpuLiquid.Buffers.cs")))
    reference = re.sub(r"\s+", "", without_comments(read(FEATURE / "Runtime/FluidExperimentGpuLiquid.Reference.cs")))
    mode_condition = "useCohesivePhysics&&!useImprovedPhysics&&activeSolver==FluidExperimentSolver.ReferenceSph"
    selection_gated = f"boolcohesiveIceContacts={mode_condition};" in buffers
    uniform_explicit = f'simulationShader.SetInt("_CohesiveIceContacts",{mode_condition}?1:0);' in reference
    kernel_reports = []
    for old_name, (field, f_name) in KERNELS.items():
        before, after = function_body(old_source, old_name), function_body(legacy_source, old_name)
        kernel_reports.append({
            "legacy_entry_point": old_name,
            "f_entry_point": f_name,
            "legacy_body_identical_without_comments_or_whitespace": before == after,
            "original_normalized_sha256": sha_text(before),
            "current_legacy_normalized_sha256": sha_text(after),
            "legacy_body_has_no_cohesive_contact_code": "Cohesive" not in after and "cohesive" not in after,
            "f_pragma_has_contact_define": bool(re.search(
                rf"^#pragma kernel {f_name} {CONTACT_MACRO}\s*$", new_source, re.MULTILINE)),
            "f_entry_rename_is_conditional": f"#define {old_name} {f_name}" in contact_source
                and f"#define {old_name} {f_name}" not in legacy_source,
            "runtime_selects_original_name_for_a_e":
                f'{field}=RequireKernel(cohesiveIceContacts?"{f_name}":"{old_name}");' in buffers,
        })
    helper = '#include "FluidExperimentCohesiveContacts.hlsl"'
    helper_excluded = helper not in legacy_source and helper in contact_source

    # These whole files contain the radius/ml/solver settings, material response,
    # pouring behavior and the D/F display. Their byte preservation is stronger
    # than testing only a few property values.
    protected = {
        "Runtime/FluidExperimentLiquidSettings.cs",
        "Runtime/FluidExperimentMaterials.cs",
        "Runtime/FluidExperimentGpuLiquid.Cohesive.cs",
        "Runtime/FluidExperimentGpuLiquid.CalibratedFill.cs",
        "Runtime/FluidExperimentBody.Pouring.cs",
        "Runtime/FluidExperimentBody.Reservoir.cs",
    }
    protected.update(name for name in original if name.startswith("Data/"))
    protected.update(name for name in original if name.startswith("Shaders/")
                     and name != "Shaders/FluidExperimentLiquid.compute")
    protected.update(name for name in original if name.startswith("Runtime/")
                     and ("Surface" in name or "Rendering" in name))
    protected = sorted(name for name in protected if name in original)
    protected_errors = [name for name in protected if name in changed]
    protected_hashes = {name: {"original": original[name],
                              "current": sha(FEATURE / name) if (FEATURE / name).is_file() else None}
                        for name in protected}

    # Check all feature metadata and search the entire Assets tree for duplicate
    # GUIDs involving this feature, without judging unrelated malformed metadata.
    guid_paths = defaultdict(list)
    feature_guids, invalid_feature_meta = {}, []
    assets_meta_count = 0
    for path in (ROOT / "Assets").rglob("*.meta"):
        assets_meta_count += 1
        match = GUID.search(read(path))
        is_feature = path.is_relative_to(FEATURE)
        if match:
            guid = match.group(1).lower()
            guid_paths[guid].append(path.relative_to(ROOT).as_posix())
            if is_feature:
                feature_guids[path.relative_to(FEATURE).as_posix()] = guid
        elif is_feature:
            invalid_feature_meta.append(path.relative_to(FEATURE).as_posix())
    duplicate_feature_guids = {guid: paths for guid, paths in guid_paths.items()
                              if guid in set(feature_guids.values()) and len(paths) > 1}
    kernel_fields = (
        "legacy_body_identical_without_comments_or_whitespace",
        "legacy_body_has_no_cohesive_contact_code", "f_pragma_has_contact_define",
        "f_entry_rename_is_conditional", "runtime_selects_original_name_for_a_e",
    )
    passed = (not snapshot_errors and not protected_errors and not invalid_feature_meta
              and not duplicate_feature_guids and selection_gated and uniform_explicit and helper_excluded
              and legacy_blocks == contact_blocks and legacy_blocks > 0
              and all(all(kernel[field] for field in kernel_fields) for kernel in kernel_reports))
    report = {
        "passed": passed,
        "audited_at_utc": datetime.now(timezone.utc).isoformat(),
        "basis": "Exact pre-ice-contact-fix working-tree snapshot; includes the already implemented default F mode.",
        "manifest": MANIFEST.relative_to(ROOT).as_posix(),
        "manifest_sha256": sha(MANIFEST),
        "snapshot_directory": SNAPSHOT.relative_to(ROOT).as_posix(),
        "snapshot_file_count": len(original),
        "snapshot_errors": snapshot_errors,
        "changed_original_files": changed,
        "script": Path(__file__).resolve().relative_to(ROOT).as_posix(),
        "script_sha256": sha(Path(__file__).resolve()),
        "python_version": sys.version.split()[0],
        "conditional_contact_block_count": legacy_blocks,
        "legacy_contact_helper_and_arrays_excluded_at_preprocessing": helper_excluded,
        "runtime_f_selection_is_mode_guarded": selection_gated,
        "contact_uniform_explicitly_zero_for_a_e": uniform_explicit,
        "kernel_checks": kernel_reports,
        "protected_file_count": len(protected),
        "settings_material_geometry_pouring_and_surface_changes": protected_errors,
        "protected_file_hashes": protected_hashes,
        "metadata": {
            "assets_meta_scanned": assets_meta_count,
            "feature_meta_checked": len(feature_guids) + len(invalid_feature_meta),
            "invalid_feature_meta": sorted(invalid_feature_meta),
            "duplicate_feature_guids": duplicate_feature_guids,
            "new_contact_include_guid": feature_guids.get("Shaders/FluidExperimentCohesiveContacts.hlsl.meta"),
        },
        "limits": [
            "Static source and file preservation only; this does not measure generated ISA, register occupancy, frame time or FPS.",
            "F contact arrays and helper calls are absent from the A-E preprocessed kernel bodies; their compiled performance still requires profiling if asserted.",
            "CPU ice containment/contact recovery intentionally changed and is not claimed to have identical A-E gameplay behavior.",
            "Runtime GPU/Physics2D regression evidence is separate. Historical pre-F audits are untouched.",
        ],
    }
    OUTPUT.write_text(json.dumps(report, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(json.dumps({"passed": passed, "output": str(OUTPUT), "snapshot_errors": snapshot_errors,
                      "protected_errors": protected_errors, "kernel_checks": kernel_reports,
                      "metadata": report["metadata"]}, indent=2))
    return 0 if passed else 1


if __name__ == "__main__":
    raise SystemExit(main())
