//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer $Globals
// {
//
//   int _StreamHeadCount;              // Offset:    0 Size:     4 [unused]
//   int _StreamRenderingEnabled;       // Offset:    4 Size:     4 [unused]
//   float _SimulationTime;             // Offset:    8 Size:     4 [unused]
//   float _StreamMaximumGap;           // Offset:   12 Size:     4 [unused]
//   float _StreamMaximumLength;        // Offset:   16 Size:     4 [unused]
//   int _ParticleCapacity;             // Offset:   20 Size:     4
//   int _MaximumIngredients;           // Offset:   24 Size:     4 [unused]
//   int _IngredientCount;              // Offset:   28 Size:     4 [unused]
//   int _SpawnCount;                   // Offset:   32 Size:     4 [unused]
//   int _GridWidth;                    // Offset:   36 Size:     4 [unused]
//   int _GridHeight;                   // Offset:   40 Size:     4 [unused]
//   int _GridCellCount;                // Offset:   44 Size:     4 [unused]
//   int _BoundaryCount;                // Offset:   48 Size:     4 [unused]
//   int _VesselTriggerCount;           // Offset:   52 Size:     4
//   int _AgitatorCount;                // Offset:   56 Size:     4 [unused]
//   int _TechniqueTargetVessel;        // Offset:   60 Size:     4 [unused]
//   int _TechniqueMask;                // Offset:   64 Size:     4 [unused]
//   int _TechniqueStateMask;           // Offset:   68 Size:     4 [unused]
//   int _TransformTargetVessel;        // Offset:   72 Size:     4 [unused]
//   int _SuspensionTargetVessel;       // Offset:   76 Size:     4 [unused]
//   int _SuspensionEnabled;            // Offset:   80 Size:     4 [unused]
//   int _ReferenceSolverEnabled;       // Offset:   84 Size:     4 [unused]
//   int _ImprovedPhysics;              // Offset:   88 Size:     4 [unused]
//   int _TransferTargetVessel;         // Offset:   92 Size:     4 [unused]
//   float _ReferenceParticleVolume;    // Offset:   96 Size:     4 [unused]
//   float _ReferenceRestDensity;       // Offset:  100 Size:     4 [unused]
//   float _ReferencePressureStiffness; // Offset:  104 Size:     4 [unused]
//   float _ReferenceNearPressureStiffness;// Offset:  108 Size:     4 [unused]
//   float _ReferenceViscosityRate;     // Offset:  112 Size:     4 [unused]
//   float _ReferenceMaximumTensionRatio;// Offset:  116 Size:     4 [unused]
//   float _ReferenceMaximumAcceleration;// Offset:  120 Size:     4 [unused]
//   float _ReferenceMaximumDisplacementRatio;// Offset:  124 Size:     4 [unused]
//   float _DeltaTime;                  // Offset:  128 Size:     4 [unused]
//   float _ParticleRadius;             // Offset:  132 Size:     4
//   float _SmoothingRadius;            // Offset:  136 Size:     4
//   float _RestDensity;                // Offset:  140 Size:     4 [unused]
//   float _DensityCompliance;          // Offset:  144 Size:     4 [unused]
//   float _LambdaEpsilon;              // Offset:  148 Size:     4 [unused]
//   float _ArtificialPressureStrength; // Offset:  152 Size:     4 [unused]
//   float _ArtificialPressureRadiusRatio;// Offset:  156 Size:     4 [unused]
//   float _BoundaryDensityScale;       // Offset:  160 Size:     4 [unused]
//   float _WallFriction;               // Offset:  164 Size:     4 [unused]
//   float _WallRestitution;            // Offset:  168 Size:     4 [unused]
//   float _SplashTransfer;             // Offset:  172 Size:     4 [unused]
//   float _SplashMinimumImpactSpeed;   // Offset:  176 Size:     4 [unused]
//   float _BottomImpactSpread;         // Offset:  180 Size:     4 [unused]
//   float _VelocityDamping;            // Offset:  184 Size:     4 [unused]
//   float _MaximumSpeed;               // Offset:  188 Size:     4 [unused]
//   float _ClosedVesselDampingRate;    // Offset:  192 Size:     4 [unused]
//   float _ClosedVesselMaximumRelativeSpeed;// Offset:  196 Size:     4 [unused]
//   float _Viscosity;                  // Offset:  200 Size:     4 [unused]
//   float _PassiveMixRate;             // Offset:  204 Size:     4 [unused]
//   float _AgitationMixRate;           // Offset:  208 Size:     4 [unused]
//   float _FullMixRelativeSpeed;       // Offset:  212 Size:     4 [unused]
//   float _MaximumMixPerSubstep;       // Offset:  216 Size:     4 [unused]
//   float _MinimumVisibleAlpha;        // Offset:  220 Size:     4 [unused]
//   float2 _Gravity;                   // Offset:  224 Size:     8 [unused]
//   float2 _GridOrigin;                // Offset:  232 Size:     8 [unused]
//   float2 _WorldMin;                  // Offset:  240 Size:     8 [unused]
//   float2 _WorldMax;                  // Offset:  248 Size:     8 [unused]
//   float2 _TransformDelta;            // Offset:  256 Size:     8 [unused]
//   int _SwapA;                        // Offset:  264 Size:     4 [unused]
//   int _SwapB;                        // Offset:  268 Size:     4 [unused]
//   float2 _SwapDeltaA;                // Offset:  272 Size:     8 [unused]
//   float2 _SwapDeltaB;                // Offset:  280 Size:     8 [unused]
//   int _BoundaryGroupCount;           // Offset:  288 Size:     4
//   int _ImprovedVesselCount;          // Offset:  292 Size:     4 [unused]
//   float _ImprovedAreaPerMl;          // Offset:  296 Size:     4 [unused]
//   float _ImprovedKernelRatio;        // Offset:  300 Size:     4 [unused]
//   float _ImprovedCompliance;         // Offset:  304 Size:     4 [unused]
//   float _ImprovedCorrectionRatio;    // Offset:  308 Size:     4 [unused]
//   float _ImprovedWallDensity;        // Offset:  312 Size:     4 [unused]
//   float _ImprovedShear;              // Offset:  316 Size:     4 [unused]
//   float _ImprovedTension;            // Offset:  320 Size:     4 [unused]
//   float _ImprovedWetting;            // Offset:  324 Size:     4 [unused]
//
// }
//
// Resource bind info for _Boundaries
// {
//
//   struct BoundarySegment
//   {
//       
//       float2 a;                      // Offset:    0
//       float2 b;                      // Offset:    8
//       float2 velocityA;              // Offset:   16
//       float2 velocityB;              // Offset:   24
//       uint vesselId;                 // Offset:   32
//       uint flags;                    // Offset:   36
//       float2 localA;                 // Offset:   40
//       float2 localB;                 // Offset:   48
//       float2 startPosition;          // Offset:   56
//       float2 endPosition;            // Offset:   64
//       float startAngle;              // Offset:   72
//       float angleDelta;              // Offset:   76
//
//   } $Element;                        // Offset:    0 Size:    80
//
// }
//
// Resource bind info for _VesselTriggers
// {
//
//   struct VesselTrigger
//   {
//       
//       float2 center;                 // Offset:    0
//       float2 axisX;                  // Offset:    8
//       float2 axisY;                  // Offset:   16
//       float2 halfExtents;            // Offset:   24
//       uint vesselId;                 // Offset:   32
//       int priority;                  // Offset:   36
//       uint active;                   // Offset:   40
//       uint flags;                    // Offset:   44
//
//   } $Element;                        // Offset:    0 Size:    48
//
// }
//
// Resource bind info for _BoundaryGroups
// {
//
//   struct BoundaryGroup
//   {
//       
//       float2 minPosition;            // Offset:    0
//       float2 maxPosition;            // Offset:    8
//       float2 sweptMin;               // Offset:   16
//       float2 sweptMax;               // Offset:   24
//       uint first;                    // Offset:   32
//       uint end;                      // Offset:   36
//       uint contourFirst;             // Offset:   40
//       uint contourEnd;               // Offset:   44
//       uint vesselId;                 // Offset:   48
//
//   } $Element;                        // Offset:    0 Size:    52
//
// }
//
// Resource bind info for _Particles
// {
//
//   struct LiquidParticle
//   {
//       
//       float2 position;               // Offset:    0
//       float2 previousPosition;       // Offset:    8
//       float2 velocity;               // Offset:   16
//       float volumeMl;                // Offset:   24
//       float temperatureC;            // Offset:   28
//       uint vesselId;                 // Offset:   32
//       uint techniqueFlags;           // Offset:   36
//       uint stateFlags;               // Offset:   40
//       uint active;                   // Offset:   44
//       uint padding;                  // Offset:   48
//
//   } $Element;                        // Offset:    0 Size:    52
//
// }
//
// Resource bind info for _PositionDeltas
// {
//
//   float2 $Element;                   // Offset:    0 Size:     8
//
// }
//
// Resource bind info for _StreamParticles
// {
//
//   struct StreamParticle
//   {
//       
//       uint token;                    // Offset:    0
//       uint previousToken;            // Offset:    4
//       uint streamId;                 // Offset:    8
//       uint sourceId;                 // Offset:   12
//       float delay;                   // Offset:   16
//       float stepDt;                  // Offset:   20
//       float startFraction;           // Offset:   24
//       float birthTime;               // Offset:   28
//       float radius;                  // Offset:   32
//       uint detached;                 // Offset:   36
//       uint pending;                  // Offset:   40
//       uint padding;                  // Offset:   44
//
//   } $Element;                        // Offset:    0 Size:    48
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// _Boundaries                       texture  struct         r/o             t0      1 
// _VesselTriggers                   texture  struct         r/o             t1      1 
// _BoundaryGroups                   texture  struct         r/o             t2      1 
// _Particles                            UAV  struct         r/w             u0      1 
// _PositionDeltas                       UAV  struct         r/w             u1      1 
// _StreamParticles                      UAV  struct         r/w             u2      1 
// $Globals                          cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[19], immediateIndexed
dcl_resource_structured t0, 80
dcl_resource_structured t1, 48
dcl_resource_structured t2, 52
dcl_uav_structured u0, 52
dcl_uav_structured u1, 8
dcl_uav_structured u2, 48
dcl_input vThreadID.x
dcl_temps 11
dcl_thread_group 64, 1, 1
uge r0.x, vThreadID.x, cb0[1].y
if_nz r0.x
  ret 
endif 
ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r0.xy, vThreadID.x, l(0), u0.xyxx
ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r0.z, vThreadID.x, l(32), u0.xxxx
ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r1.xy, vThreadID.x, l(40), u0.xyxx
ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r0.w, vThreadID.x, l(20), u2.xxxx
ge r0.w, l(0.000001), r0.w
ieq r1.y, r1.y, l(0)
or r0.w, r0.w, r1.y
and r1.x, r1.x, l(4)
ine r1.x, r1.x, l(0)
or r0.w, r0.w, r1.x
if_nz r0.w
  ret 
endif 
ld_structured_indexable(structured_buffer, stride=8)(mixed,mixed,mixed,mixed) r1.xy, vThreadID.x, l(0), u1.xyxx
add r1.zw, r0.xxxy, r1.xxxy
dp2 r0.w, r1.xyxx, r1.xyxx
sqrt r0.w, r0.w
add r0.w, r0.w, cb0[8].y
add r1.xy, -r0.wwww, r1.zwzz
add r2.xy, r0.wwww, r1.zwzz
mov r3.y, l(0)
mov r4.x, l(-1.000000)
mov r4.yz, r1.zzwz
mov r0.w, l(0)
loop 
  ige r2.z, r0.w, cb0[18].x
  breakc_nz r2.z
  ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r5.xyzw, r0.w, l(0), t2.xyzw
  ge r2.zw, r2.xxxy, r5.xxxy
  and r2.z, r2.w, r2.z
  ge r3.zw, r5.zzzw, r1.xxxy
  and r2.w, r3.w, r3.z
  and r2.z, r2.w, r2.z
  if_z r2.z
    iadd r2.z, r0.w, l(1)
    mov r0.w, r2.z
    continue 
  endif 
  ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r2.zw, r0.w, l(32), t2.xxxy
  mov r5.xyz, r4.xyzx
  mov r3.z, r2.z
  loop 
    uge r3.w, r3.z, r2.w
    breakc_nz r3.w
    ld_structured_indexable(structured_buffer, stride=80)(mixed,mixed,mixed,mixed) r6.xy, r3.z, l(32), t0.xyxx
    and r3.w, r6.y, l(16)
    if_z r3.w
      ine r3.w, r0.z, r6.x
      if_nz r3.w
        and r3.w, r6.y, l(2)
        ine r3.w, r3.w, l(0)
        if_nz r0.z
          mov r6.xy, l(0,0,0,0)
          mov r4.w, l(0)
          loop 
            ige r5.w, r6.y, cb0[3].y
            mov r4.w, l(0)
            breakc_nz r5.w
            ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r5.w, r6.y, l(32), t1.xxxx
            ieq r5.w, r0.z, r5.w
            ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r6.z, r6.y, l(44), t1.xxxx
            and r6.z, r6.z, l(2)
            ine r6.z, r6.z, l(0)
            and r5.w, r5.w, r6.z
            if_nz r5.w
              mov r6.x, l(-1)
              mov r4.w, l(-1)
              break 
            endif 
            iadd r3.x, r6.y, l(1)
            mov r6.xy, r3.yxyy
            mov r4.w, r5.w
          endloop 
          and r3.x, r6.x, r4.w
        else 
          mov r3.x, l(0)
        endif 
        or r3.x, r3.x, r3.w
        not r3.x, r3.x
      else 
        mov r3.x, l(-1)
      endif 
    else 
      mov r3.x, l(0)
    endif 
    if_z r3.x
      iadd r3.x, r3.z, l(1)
      mov r3.z, r3.x
      continue 
    endif 
    ld_structured_indexable(structured_buffer, stride=80)(mixed,mixed,mixed,mixed) r7.xyzw, r3.z, l(0), t0.xyzw
    add r8.xy, -r7.xyxx, r7.zwzz
    dp2 r3.x, r8.xyxx, r8.xyxx
    lt r3.w, l(0.000000), r3.x
    add r6.yz, r1.wwzw, -r7.yyxy
    dp2 r5.w, r6.zyzz, r8.xyxx
    div_sat r3.x, r5.w, r3.x
    and r3.x, r3.x, r3.w
    mad r7.zw, r8.xxxy, r3.xxxx, r7.xxxy
    add r9.xy, r1.zwzz, -r7.zwzz
    dp2 r3.w, r9.xyxx, r9.xyxx
    sqrt r3.w, r3.w
    add r7.xy, r0.yxyy, -r7.yxyy
    mul r5.w, r7.y, r8.y
    mad r5.w, r8.x, r7.x, -r5.w
    mul r6.z, r6.z, r8.y
    mad r6.y, r8.x, r6.y, -r6.z
    mul r6.y, r5.w, r6.y
    lt r6.y, r6.y, l(0.000000)
    lt r6.z, l(0.000000), r3.x
    and r6.y, r6.z, r6.y
    lt r3.x, r3.x, l(1.000000)
    and r3.x, r3.x, r6.y
    if_nz r3.x
      mov r8.zw, -r8.yyyy
      dp2 r3.x, r8.xzxx, r8.xwxx
      rsq r3.x, r3.x
      mul r6.yz, r8.yyxy, l(0.000000, -1.000000, 1.000000, 0.000000)
      mul r6.yz, r3.xxxx, r6.yyzy
      ge r3.x, r5.w, l(0.000000)
      movc r3.x, r3.x, l(1.000000), l(-1.000000)
      mul r6.yz, r3.xxxx, r6.yyzy
      add r10.x, r3.w, cb0[8].y
      lt r3.x, r5.x, r10.x
      mad r10.yz, r6.yyzy, cb0[8].yyyy, r7.zzwz
      movc r6.yzw, r3.xxxx, r10.xxyz, r5.xxyz
      iadd r3.x, r3.z, l(1)
      mov r5.xyz, r6.yzwy
      mov r3.z, r3.x
      continue 
    endif 
    lt r3.x, r3.w, cb0[8].y
    if_nz r3.x
      lt r3.x, l(0.000010), r3.w
      div r6.yz, r9.xxyx, r3.wwww
      mul r7.xy, r8.yxyy, l(-1.000000, 1.000000, 0.000000, 0.000000)
      dp2 r5.w, r7.xyxx, r7.xyxx
      rsq r5.w, r5.w
      mul r7.xy, r5.wwww, r7.xyxx
      movc r6.yz, r3.xxxx, r6.yyzy, r7.xxyx
      add r8.x, -r3.w, cb0[8].y
      lt r3.x, r5.x, r8.x
      mad r8.yz, r6.yyzy, cb0[8].yyyy, r7.zzwz
      movc r6.yzw, r3.xxxx, r8.xxyz, r5.xxyz
      iadd r3.x, r3.z, l(1)
      mov r5.xyz, r6.yzwy
      mov r3.z, r3.x
      continue 
    endif 
    iadd r3.z, r3.z, l(1)
  endloop 
  mov r4.xyz, r5.xyzx
  iadd r0.w, r0.w, l(1)
endloop 
ge r0.x, r4.x, l(0.000000)
movc r0.yw, r0.xxxx, r4.yyyz, r1.zzzw
if_nz r0.z
  mov r1.y, l(0)
  mov r1.zw, l(0,0,0,0)
  mov r2.x, l(0)
  loop 
    ige r2.y, r1.w, cb0[3].y
    mov r2.x, l(0)
    breakc_nz r2.y
    ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r2.y, r1.w, l(32), t1.xxxx
    ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r2.zw, r1.w, l(40), t1.xxxy
    ine r2.z, r2.z, l(0)
    ieq r2.y, r0.z, r2.y
    and r2.y, r2.y, r2.z
    and r2.z, r2.w, l(1)
    ine r2.z, r2.z, l(0)
    and r2.y, r2.z, r2.y
    if_nz r2.y
      mov r1.z, l(-1)
      mov r2.x, l(-1)
      break 
    endif 
    iadd r1.x, r1.w, l(1)
    mov r1.zw, r1.yyyx
    mov r2.x, r2.y
  endloop 
  and r1.x, r1.z, r2.x
  add r1.y, cb0[8].y, l(0.000010)
  mov r1.zw, r0.yyyw
  mov r2.xy, r0.ywyy
  mov r2.zw, l(0,0,0,0)
  loop 
    ige r3.x, r2.z, cb0[3].y
    mov r2.w, l(0)
    breakc_nz r3.x
    ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r3.x, r2.z, l(32), t1.xxxx
    ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r3.yz, r2.z, l(40), t1.xxyx
    ieq r3.y, r3.y, l(0)
    ine r3.x, r0.z, r3.x
    or r3.x, r3.x, r3.y
    and r3.y, r3.z, l(1)
    ieq r3.y, r3.y, l(0)
    or r3.x, r3.y, r3.x
    if_nz r3.x
      iadd r3.x, r2.z, l(1)
      mov r2.w, l(0)
      mov r2.z, r3.x
      continue 
    endif 
    and r3.x, r3.z, l(32)
    if_nz r3.x
      if_nz r0.z
        mov r3.xyz, l(0,0,0,0)
        loop 
          ige r3.w, r3.z, cb0[18].x
          breakc_nz r3.w
          ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r4.xyz, r3.z, l(40), t2.xyzx
          ine r3.w, r0.z, r4.z
          if_nz r3.w
            iadd r3.w, r3.z, l(1)
            mov r3.z, r3.w
            continue 
          endif 
          mov r3.xy, r4.xyxx
          break 
        endloop 
      else 
        mov r3.xy, l(0,0,0,0)
      endif 
      mov r2.xy, r1.zwzz
      mov r3.z, l(0)
      loop 
        ige r3.w, r3.z, l(4)
        breakc_nz r3.w
        mov r4.xy, r2.xyxx
        mov r5.xyz, l(100000002004087734272.000000,0,0,0)
        mov r3.w, r3.x
        loop 
          uge r4.z, r3.w, r3.y
          breakc_nz r4.z
          ld_structured_indexable(structured_buffer, stride=80)(mixed,mixed,mixed,mixed) r4.zw, r3.w, l(32), t0.xxxy
          ine r4.z, r0.z, r4.z
          and r4.w, r4.w, l(8)
          ieq r4.w, r4.w, l(0)
          or r4.z, r4.w, r4.z
          if_nz r4.z
            iadd r4.z, r3.w, l(1)
            mov r3.w, r4.z
            continue 
          endif 
          ld_structured_indexable(structured_buffer, stride=80)(mixed,mixed,mixed,mixed) r6.xyzw, r3.w, l(0), t0.xyzw
          add r7.xy, -r6.xyxx, r6.zwzz
          dp2 r4.z, r7.xyxx, r7.xyxx
          lt r4.w, l(0.000000), r4.z
          add r6.zw, r2.xxxy, -r6.xxxy
          dp2 r5.w, r6.zwzz, r7.xyxx
          div_sat r4.z, r5.w, r4.z
          and r4.z, r4.z, r4.w
          mad r4.zw, r7.xxxy, r4.zzzz, r6.xxxy
          add r6.xy, r2.xyxx, -r4.zwzz
          dp2 r5.w, r6.xyxx, r6.xyxx
          sqrt r6.x, r5.w
          lt r5.w, r6.x, r5.x
          mov r7.zw, -r7.yyyy
          dp2 r6.w, r7.xzxx, r7.xwxx
          rsq r6.w, r6.w
          mul r7.xy, r7.yxyy, l(-1.000000, 1.000000, 0.000000, 0.000000)
          mul r6.yz, r6.wwww, r7.xxyx
          movc r4.xy, r5.wwww, r4.zwzz, r4.xyxx
          movc r5.xyz, r5.wwww, r6.xyzx, r5.xyzx
          iadd r3.w, r3.w, l(1)
        endloop 
        if_nz r0.z
          mov r4.zw, l(0,0,0,0)
          mov r3.w, l(0)
          loop 
            ige r5.w, r3.w, cb0[18].x
            breakc_nz r5.w
            ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r6.xyz, r3.w, l(40), t2.xyzx
            ine r5.w, r0.z, r6.z
            if_nz r5.w
              iadd r5.w, r3.w, l(1)
              mov r3.w, r5.w
              continue 
            endif 
            mov r4.zw, r6.xxxy
            break 
          endloop 
        else 
          mov r4.zw, l(0,0,0,0)
        endif 
        mov r3.w, l(0)
        mov r5.w, r4.z
        loop 
          uge r6.x, r5.w, r4.w
          breakc_nz r6.x
          ld_structured_indexable(structured_buffer, stride=80)(mixed,mixed,mixed,mixed) r6.xy, r5.w, l(32), t0.xyxx
          ine r6.x, r0.z, r6.x
          and r6.y, r6.y, l(8)
          ieq r6.y, r6.y, l(0)
          or r6.x, r6.y, r6.x
          if_nz r6.x
            iadd r6.x, r5.w, l(1)
            mov r5.w, r6.x
            continue 
          endif 
          ld_structured_indexable(structured_buffer, stride=80)(mixed,mixed,mixed,mixed) r6.xyzw, r5.w, l(0), t0.xyzw
          lt r7.xy, r2.yyyy, r6.ywyy
          ine r7.x, r7.y, r7.x
          add r6.zw, -r6.xxxy, r6.zzzw
          add r6.y, r2.y, -r6.y
          mul r6.y, r6.y, r6.z
          div r6.y, r6.y, r6.w
          add r6.x, r6.y, r6.x
          lt r6.x, r2.x, r6.x
          not r6.y, r3.w
          movc r6.x, r6.x, r6.y, r3.w
          movc r3.w, r7.x, r6.x, r3.w
          iadd r5.w, r5.w, l(1)
        endloop 
        ge r5.w, r5.x, l(9999999980506447872.000000)
        ge r6.x, r5.x, cb0[8].y
        and r6.x, r3.w, r6.x
        or r5.w, r5.w, r6.x
        if_nz r5.w
          break 
        endif 
        mad r2.xy, r5.yzyy, r1.yyyy, r4.xyxx
        iadd r3.z, r3.z, l(1)
      endloop 
      mov r1.zw, r2.xxxy
      mov r2.w, l(-1)
      break 
    endif 
    ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r6.xyzw, r2.z, l(0), t1.xyzw
    ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r7.xyzw, r2.z, l(16), t1.xyzw
    add r8.xy, r1.zwzz, -r6.xyxx
    dp2 r9.x, r8.xyxx, r6.zwzz
    dp2 r9.y, r8.xyxx, r7.xyxx
    add r7.zw, r7.zzzw, -cb0[8].yyyy
    max r7.zw, r7.zzzw, cb0[8].yyyy
    max r8.xy, -r7.zwzz, r9.xyxx
    min r7.zw, r7.zzzw, r8.xxxy
    mad r6.xy, r6.zwzz, r7.zzzz, r6.xyxx
    mad r6.xy, r7.xyxx, r7.wwww, r6.xyxx
    mov r2.xy, r6.xyxx
    mov r2.w, l(-1)
    break 
  endloop 
  movc r0.yw, r2.wwww, r2.xxxy, r1.zzzw
else 
  mov r1.x, l(0)
endif 
ine r1.y, r0.z, l(0)
if_nz r0.z
  mov r1.zw, l(0,0,0,0)
  mov r2.x, l(0)
  loop 
    ige r2.y, r2.x, cb0[18].x
    breakc_nz r2.y
    ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r2.yzw, r2.x, l(40), t2.xxyz
    ine r2.w, r0.z, r2.w
    if_nz r2.w
      iadd r2.w, r2.x, l(1)
      mov r2.x, r2.w
      continue 
    endif 
    mov r1.zw, r2.yyyz
    break 
  endloop 
else 
  mov r1.zw, l(0,0,0,0)
endif 
mov r2.x, l(0)
mov r2.y, r1.z
loop 
  uge r2.z, r2.y, r1.w
  breakc_nz r2.z
  ld_structured_indexable(structured_buffer, stride=80)(mixed,mixed,mixed,mixed) r2.zw, r2.y, l(32), t0.xxxy
  ine r2.z, r0.z, r2.z
  and r2.w, r2.w, l(8)
  ieq r2.w, r2.w, l(0)
  or r2.z, r2.w, r2.z
  if_nz r2.z
    iadd r2.z, r2.y, l(1)
    mov r2.y, r2.z
    continue 
  endif 
  ld_structured_indexable(structured_buffer, stride=80)(mixed,mixed,mixed,mixed) r3.xyzw, r2.y, l(0), t0.xyzw
  lt r2.zw, r0.wwww, r3.yyyw
  ine r2.z, r2.w, r2.z
  add r3.zw, -r3.xxxy, r3.zzzw
  add r2.w, r0.w, -r3.y
  mul r2.w, r2.w, r3.z
  div r2.w, r2.w, r3.w
  add r2.w, r2.w, r3.x
  lt r2.w, r0.y, r2.w
  not r3.x, r2.x
  movc r2.w, r2.w, r3.x, r2.x
  movc r2.x, r2.z, r2.w, r2.x
  iadd r2.y, r2.y, l(1)
endloop 
and r1.y, r1.y, r2.x
if_z r1.y
  add r1.y, cb0[8].y, cb0[8].z
  max r1.y, r1.y, l(0.000000)
  mov r1.zw, l(0,0,0,0x80000001)
  mov r2.x, l(0)
  loop 
    ieq r2.y, r1.z, l(0)
    ilt r2.z, r2.x, cb0[3].y
    and r2.y, r2.z, r2.y
    breakc_z r2.y
    ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r3.xyzw, r2.x, l(32), t1.xyzw
    ieq r2.y, r3.z, l(0)
    and r2.z, r3.w, l(2)
    ine r2.z, r2.z, l(0)
    ine r2.w, r0.z, r3.x
    and r2.z, r2.w, r2.z
    or r2.y, r2.z, r2.y
    if_nz r2.y
      iadd r2.y, r2.x, l(1)
      mov r2.x, r2.y
      continue 
    endif 
    ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r4.xyzw, r2.x, l(0), t1.xyzw
    ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r5.xyzw, r2.x, l(16), t1.xyzw
    add r2.yz, r0.yywy, -r4.xxyx
    dp2 r2.w, r2.yzyy, r4.zwzz
    dp2 r2.y, r2.yzyy, r5.xyxx
    add r3.zw, r1.yyyy, r5.zzzw
    ge r2.yz, r3.wwzw, |r2.yywy|
    and r2.y, r2.y, r2.z
    if_nz r3.x
      mov r2.zw, l(0,0,0,0)
      mov r3.z, l(0)
      loop 
        ige r3.w, r3.z, cb0[18].x
        breakc_nz r3.w
        ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r4.xyz, r3.z, l(40), t2.xyzx
        ine r3.w, r3.x, r4.z
        if_nz r3.w
          iadd r3.w, r3.z, l(1)
          mov r3.z, r3.w
          continue 
        endif 
        mov r2.zw, r4.xxxy
        break 
      endloop 
    else 
      mov r2.zw, l(0,0,0,0)
    endif 
    mov r3.z, l(0)
    mov r3.w, r2.z
    loop 
      uge r4.x, r3.w, r2.w
      breakc_nz r4.x
      ld_structured_indexable(structured_buffer, stride=80)(mixed,mixed,mixed,mixed) r4.xy, r3.w, l(32), t0.xyxx
      ine r4.x, r3.x, r4.x
      and r4.y, r4.y, l(8)
      ieq r4.y, r4.y, l(0)
      or r4.x, r4.y, r4.x
      if_nz r4.x
        iadd r4.x, r3.w, l(1)
        mov r3.w, r4.x
        continue 
      endif 
      ld_structured_indexable(structured_buffer, stride=80)(mixed,mixed,mixed,mixed) r4.xyzw, r3.w, l(0), t0.xyzw
      lt r5.xy, r0.wwww, r4.ywyy
      ine r5.x, r5.y, r5.x
      add r4.zw, -r4.xxxy, r4.zzzw
      add r4.y, r0.w, -r4.y
      mul r4.y, r4.y, r4.z
      div r4.y, r4.y, r4.w
      add r4.x, r4.y, r4.x
      lt r4.x, r0.y, r4.x
      not r4.y, r3.z
      movc r4.x, r4.x, r4.y, r3.z
      movc r3.z, r5.x, r4.x, r3.z
      iadd r3.w, r3.w, l(1)
    endloop 
    and r2.y, r2.y, r3.z
    ige r3.w, r3.y, r1.w
    and r2.y, r2.y, r3.w
    movc r1.zw, r2.yyyy, r3.xxxy, r1.zzzw
    iadd r2.x, r2.x, l(1)
  endloop 
else 
  mov r1.z, r0.z
endif 
movc r0.z, r1.x, r0.z, r1.z
if_nz r0.x
  store_structured u2.x, vThreadID.x, l(36), l(1)
endif 
store_structured u0.xy, vThreadID.x, l(0), r0.ywyy
store_structured u0.x, vThreadID.x, l(32), r0.z
ret 
// Approximately 496 instruction slots used
