//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer $Globals
// {
//
//   int _StreamHeadCount;              // Offset:    0 Size:     4
//   int _StreamRenderingEnabled;       // Offset:    4 Size:     4
//   float _SimulationTime;             // Offset:    8 Size:     4
//   float _StreamMaximumGap;           // Offset:   12 Size:     4
//   float _StreamMaximumLength;        // Offset:   16 Size:     4
//   int _ParticleCapacity;             // Offset:   20 Size:     4
//   int _MaximumIngredients;           // Offset:   24 Size:     4 [unused]
//   int _IngredientCount;              // Offset:   28 Size:     4 [unused]
//   int _SpawnCount;                   // Offset:   32 Size:     4 [unused]
//   int _GridWidth;                    // Offset:   36 Size:     4 [unused]
//   int _GridHeight;                   // Offset:   40 Size:     4 [unused]
//   int _GridCellCount;                // Offset:   44 Size:     4 [unused]
//   int _BoundaryCount;                // Offset:   48 Size:     4 [unused]
//   int _VesselTriggerCount;           // Offset:   52 Size:     4 [unused]
//   int _AgitatorCount;                // Offset:   56 Size:     4 [unused]
//   int _TechniqueTargetVessel;        // Offset:   60 Size:     4 [unused]
//   int _TechniqueMask;                // Offset:   64 Size:     4 [unused]
//   int _TechniqueStateMask;           // Offset:   68 Size:     4 [unused]
//   int _TransformTargetVessel;        // Offset:   72 Size:     4 [unused]
//   int _SuspensionTargetVessel;       // Offset:   76 Size:     4 [unused]
//   int _SuspensionEnabled;            // Offset:   80 Size:     4 [unused]
//   int _ReferenceSolverEnabled;       // Offset:   84 Size:     4 [unused]
//   int _ImprovedPhysics;              // Offset:   88 Size:     4 [unused]
//   int _TransferTargetVessel;         // Offset:   92 Size:     4 [unused]
//   float _ReferenceParticleVolume;    // Offset:   96 Size:     4 [unused]
//   float _ReferenceRestDensity;       // Offset:  100 Size:     4 [unused]
//   float _ReferencePressureStiffness; // Offset:  104 Size:     4 [unused]
//   float _ReferenceNearPressureStiffness;// Offset:  108 Size:     4 [unused]
//   float _ReferenceViscosityRate;     // Offset:  112 Size:     4 [unused]
//   float _ReferenceMaximumTensionRatio;// Offset:  116 Size:     4 [unused]
//   float _ReferenceMaximumAcceleration;// Offset:  120 Size:     4 [unused]
//   float _ReferenceMaximumDisplacementRatio;// Offset:  124 Size:     4 [unused]
//   float _DeltaTime;                  // Offset:  128 Size:     4 [unused]
//   float _ParticleRadius;             // Offset:  132 Size:     4 [unused]
//   float _SmoothingRadius;            // Offset:  136 Size:     4 [unused]
//   float _RestDensity;                // Offset:  140 Size:     4 [unused]
//   float _DensityCompliance;          // Offset:  144 Size:     4 [unused]
//   float _LambdaEpsilon;              // Offset:  148 Size:     4 [unused]
//   float _ArtificialPressureStrength; // Offset:  152 Size:     4 [unused]
//   float _ArtificialPressureRadiusRatio;// Offset:  156 Size:     4 [unused]
//   float _BoundaryDensityScale;       // Offset:  160 Size:     4 [unused]
//   float _WallFriction;               // Offset:  164 Size:     4 [unused]
//   float _WallRestitution;            // Offset:  168 Size:     4 [unused]
//   float _SplashTransfer;             // Offset:  172 Size:     4 [unused]
//   float _SplashMinimumImpactSpeed;   // Offset:  176 Size:     4 [unused]
//   float _BottomImpactSpread;         // Offset:  180 Size:     4 [unused]
//   float _VelocityDamping;            // Offset:  184 Size:     4 [unused]
//   float _MaximumSpeed;               // Offset:  188 Size:     4 [unused]
//   float _ClosedVesselDampingRate;    // Offset:  192 Size:     4 [unused]
//   float _ClosedVesselMaximumRelativeSpeed;// Offset:  196 Size:     4 [unused]
//   float _Viscosity;                  // Offset:  200 Size:     4 [unused]
//   float _PassiveMixRate;             // Offset:  204 Size:     4 [unused]
//   float _AgitationMixRate;           // Offset:  208 Size:     4 [unused]
//   float _FullMixRelativeSpeed;       // Offset:  212 Size:     4 [unused]
//   float _MaximumMixPerSubstep;       // Offset:  216 Size:     4 [unused]
//   float _MinimumVisibleAlpha;        // Offset:  220 Size:     4 [unused]
//   float2 _Gravity;                   // Offset:  224 Size:     8 [unused]
//   float2 _GridOrigin;                // Offset:  232 Size:     8 [unused]
//   float2 _WorldMin;                  // Offset:  240 Size:     8 [unused]
//   float2 _WorldMax;                  // Offset:  248 Size:     8 [unused]
//   float2 _TransformDelta;            // Offset:  256 Size:     8 [unused]
//   int _SwapA;                        // Offset:  264 Size:     4 [unused]
//   int _SwapB;                        // Offset:  268 Size:     4 [unused]
//   float2 _SwapDeltaA;                // Offset:  272 Size:     8 [unused]
//   float2 _SwapDeltaB;                // Offset:  280 Size:     8 [unused]
//   int _BoundaryGroupCount;           // Offset:  288 Size:     4
//   int _ImprovedVesselCount;          // Offset:  292 Size:     4 [unused]
//   float _ImprovedAreaPerMl;          // Offset:  296 Size:     4 [unused]
//   float _ImprovedKernelRatio;        // Offset:  300 Size:     4 [unused]
//   float _ImprovedCompliance;         // Offset:  304 Size:     4 [unused]
//   float _ImprovedCorrectionRatio;    // Offset:  308 Size:     4 [unused]
//   float _ImprovedWallDensity;        // Offset:  312 Size:     4 [unused]
//   float _ImprovedShear;              // Offset:  316 Size:     4 [unused]
//   float _ImprovedTension;            // Offset:  320 Size:     4 [unused]
//   float _ImprovedWetting;            // Offset:  324 Size:     4 [unused]
//
// }
//
// Resource bind info for _Boundaries
// {
//
//   struct BoundarySegment
//   {
//       
//       float2 a;                      // Offset:    0
//       float2 b;                      // Offset:    8
//       float2 velocityA;              // Offset:   16
//       float2 velocityB;              // Offset:   24
//       uint vesselId;                 // Offset:   32
//       uint flags;                    // Offset:   36
//       float2 localA;                 // Offset:   40
//       float2 localB;                 // Offset:   48
//       float2 startPosition;          // Offset:   56
//       float2 endPosition;            // Offset:   64
//       float startAngle;              // Offset:   72
//       float angleDelta;              // Offset:   76
//
//   } $Element;                        // Offset:    0 Size:    80
//
// }
//
// Resource bind info for _StreamHeads
// {
//
//   struct StreamHead
//   {
//       
//       float2 lip;                    // Offset:    0
//       uint token;                    // Offset:    8
//       uint streamId;                 // Offset:   12
//       uint sourceId;                 // Offset:   16
//       float radius;                  // Offset:   20
//
//   } $Element;                        // Offset:    0 Size:    24
//
// }
//
// Resource bind info for _BoundaryGroups
// {
//
//   struct BoundaryGroup
//   {
//       
//       float2 minPosition;            // Offset:    0
//       float2 maxPosition;            // Offset:    8
//       float2 sweptMin;               // Offset:   16
//       float2 sweptMax;               // Offset:   24
//       uint first;                    // Offset:   32
//       uint end;                      // Offset:   36
//       uint contourFirst;             // Offset:   40
//       uint contourEnd;               // Offset:   44
//       uint vesselId;                 // Offset:   48
//
//   } $Element;                        // Offset:    0 Size:    52
//
// }
//
// Resource bind info for _Particles
// {
//
//   struct LiquidParticle
//   {
//       
//       float2 position;               // Offset:    0
//       float2 previousPosition;       // Offset:    8
//       float2 velocity;               // Offset:   16
//       float volumeMl;                // Offset:   24
//       float temperatureC;            // Offset:   28
//       uint vesselId;                 // Offset:   32
//       uint techniqueFlags;           // Offset:   36
//       uint stateFlags;               // Offset:   40
//       uint active;                   // Offset:   44
//       uint padding;                  // Offset:   48
//
//   } $Element;                        // Offset:    0 Size:    52
//
// }
//
// Resource bind info for _StreamParticles
// {
//
//   struct StreamParticle
//   {
//       
//       uint token;                    // Offset:    0
//       uint previousToken;            // Offset:    4
//       uint streamId;                 // Offset:    8
//       uint sourceId;                 // Offset:   12
//       float delay;                   // Offset:   16
//       float stepDt;                  // Offset:   20
//       float startFraction;           // Offset:   24
//       float birthTime;               // Offset:   28
//       float radius;                  // Offset:   32
//       uint detached;                 // Offset:   36
//       uint pending;                  // Offset:   40
//       uint padding;                  // Offset:   44
//
//   } $Element;                        // Offset:    0 Size:    48
//
// }
//
// Resource bind info for _StreamLookup
// {
//
//   uint2 $Element;                    // Offset:    0 Size:     8
//
// }
//
// Resource bind info for _StreamSegments
// {
//
//   struct StreamSegment
//   {
//       
//       float2 a;                      // Offset:    0
//       float2 b;                      // Offset:    8
//       float radiusA;                 // Offset:   16
//       float radiusB;                 // Offset:   20
//       uint active;                   // Offset:   24
//       uint particleIndex;            // Offset:   28
//
//   } $Element;                        // Offset:    0 Size:    32
//
// }
//
// Resource bind info for _SurfaceParticles
// {
//
//   struct LiquidParticle
//   {
//       
//       float2 position;               // Offset:    0
//       float2 previousPosition;       // Offset:    8
//       float2 velocity;               // Offset:   16
//       float volumeMl;                // Offset:   24
//       float temperatureC;            // Offset:   28
//       uint vesselId;                 // Offset:   32
//       uint techniqueFlags;           // Offset:   36
//       uint stateFlags;               // Offset:   40
//       uint active;                   // Offset:   44
//       uint padding;                  // Offset:   48
//
//   } $Element;                        // Offset:    0 Size:    52
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// _Boundaries                       texture  struct         r/o             t0      1 
// _StreamHeads                      texture  struct         r/o             t1      1 
// _BoundaryGroups                   texture  struct         r/o             t2      1 
// _Particles                            UAV  struct         r/w             u0      1 
// _StreamParticles                      UAV  struct         r/w             u1      1 
// _StreamLookup                         UAV  struct         r/w             u2      1 
// _StreamSegments                       UAV  struct         r/w             u3      1 
// _SurfaceParticles                     UAV  struct         r/w             u4      1 
// $Globals                          cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[19], immediateIndexed
dcl_resource_structured t0, 80
dcl_resource_structured t1, 24
dcl_resource_structured t2, 52
dcl_uav_structured u0, 52
dcl_uav_structured u1, 48
dcl_uav_structured u2, 8
dcl_uav_structured u3, 32
dcl_uav_structured u4, 52
dcl_input vThreadID.x
dcl_temps 13
dcl_thread_group 64, 1, 1
iadd r0.x, cb0[1].y, l(64)
uge r0.x, vThreadID.x, r0.x
if_nz r0.x
  ret 
endif 
ult r0.x, vThreadID.x, cb0[1].y
if_nz r0.x
  ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r0.xyzw, vThreadID.x, l(0), u0.xyzw
  ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r1.xyzw, vThreadID.x, l(16), u0.xyzw
  ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r2.xyzw, vThreadID.x, l(32), u0.wxyz
  ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r3.x, vThreadID.x, l(48), u0.xxxx
  ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r4.xyzw, vThreadID.x, l(0), u1.xyzw
  ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r3.y, vThreadID.x, l(28), u1.xxxx
  ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r3.z, vThreadID.x, l(36), u1.xxxx
  ine r3.w, cb0[0].y, l(0)
  ine r5.x, r2.x, l(0)
  and r3.w, r3.w, r5.x
  ine r4.x, r4.x, l(0)
  and r3.w, r3.w, r4.x
  ieq r3.z, r3.z, l(0)
  and r3.z, r3.z, r3.w
  if_nz r3.z
    ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r3.z, vThreadID.x, l(32), u1.xxxx
    ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r5.xy, vThreadID.x, l(16), u0.xyxx
    dp2 r3.w, r5.xyxx, r5.xyxx
    sqrt r3.w, r3.w
    max r3.w, r3.w, l(0.500000)
    div r3.w, l(2.400000), r3.w
    sqrt r3.w, r3.w
    max r3.w, r3.w, l(0.500000)
    min r3.w, r3.w, l(1.200000)
    mul r5.x, r3.w, r3.z
    if_nz r4.y
      ishl r3.z, cb0[1].y, l(1)
      udiv null, r3.z, r4.y, r3.z
      ld_structured_indexable(structured_buffer, stride=8)(mixed,mixed,mixed,mixed) r3.zw, r3.z, l(0), u2.xxyx
      ine r3.w, r4.y, r3.w
      uge r4.x, r3.z, cb0[1].y
      or r3.w, r3.w, r4.x
      if_z r3.w
        ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r3.w, r3.z, l(0), u1.xxxx
        ieq r3.w, r4.y, r3.w
        ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r4.x, r3.z, l(44), u0.xxxx
        ine r4.x, r4.x, l(0)
        and r3.w, r3.w, r4.x
      else 
        mov r3.zw, l(0,0,0,0)
      endif 
    else 
      mov r3.zw, l(0,0,0,0)
    endif 
    if_nz r3.w
      ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r4.xy, r3.z, l(8), u1.xyxx
      ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r6.xyz, r3.z, l(28), u1.xyzx
      add r3.y, r3.y, -r6.x
      ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r7.zw, r3.z, l(0), u0.xxxy
      ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r3.w, r3.z, l(32), u0.xxxx
      ine r6.x, r2.y, l(0)
      ieq r6.w, r2.y, r3.w
      and r6.x, r6.w, r6.x
      ieq r6.zw, r6.zzzz, l(0, 0, 0, 2)
      and r6.w, r6.x, r6.w
      or r6.z, r6.w, r6.z
      ieq r6.w, r2.y, l(0)
      ieq r3.w, r3.w, l(0)
      or r3.w, r3.w, r6.w
      or r3.w, r6.x, r3.w
      ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r6.xw, r3.z, l(16), u0.xxxy
      dp2 r6.x, r6.xwxx, r6.xwxx
      sqrt r6.x, r6.x
      max r6.x, r6.x, l(0.500000)
      div r6.x, l(2.400000), r6.x
      sqrt r6.x, r6.x
      max r6.x, r6.x, l(0.500000)
      min r6.x, r6.x, l(1.200000)
      mul r6.x, r6.x, r6.y
      max r6.x, r5.x, r6.x
      and r3.w, r3.w, r6.z
      ieq r4.xy, r4.zwzz, r4.xyxx
      and r3.w, r3.w, r4.x
      and r3.w, r4.y, r3.w
      lt r4.x, l(0.000000), r3.y
      and r3.w, r3.w, r4.x
      ge r3.y, cb0[0].w, r3.y
      and r3.y, r3.y, r3.w
      add r4.xy, -r0.xyxx, r7.zwzz
      dp2 r3.w, r4.xyxx, r4.xyxx
      sqrt r4.z, r3.w
      ge r4.z, cb0[1].x, r4.z
      and r3.y, r3.y, r4.z
      min r4.zw, r0.xxxy, r7.zzzw
      add r4.zw, -r6.xxxx, r4.zzzw
      max r6.yz, r0.xxyx, r7.zzwz
      add r6.yz, r6.xxxx, r6.yyzy
      lt r6.w, l(0.000000), r3.w
      mov r8.xyz, l(0,0,0,0)
      loop 
        ige r8.w, r8.y, cb0[18].x
        mov r8.z, l(0)
        breakc_nz r8.w
        ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r9.xyzw, r8.y, l(0), t2.xyzw
        ge r9.xy, r6.yzyy, r9.xyxx
        and r8.w, r9.y, r9.x
        ge r9.xy, r9.zwzz, r4.zwzz
        and r9.x, r9.y, r9.x
        and r8.w, r8.w, r9.x
        if_z r8.w
          iadd r8.w, r8.y, l(1)
          mov r8.z, l(0)
          mov r8.y, r8.w
          continue 
        endif 
        ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r9.xy, r8.y, l(32), t2.xyxx
        mov r8.w, r8.x
        mov r9.z, r9.x
        mov r9.w, l(0)
        loop 
          uge r10.x, r9.z, r9.y
          mov r9.w, l(0)
          breakc_nz r10.x
          ld_structured_indexable(structured_buffer, stride=80)(mixed,mixed,mixed,mixed) r10.x, r9.z, l(36), t0.xxxx
          and r10.x, r10.x, l(16)
          if_nz r10.x
            iadd r10.x, r9.z, l(1)
            mov r9.w, l(0)
            mov r9.z, r10.x
            continue 
          endif 
          ld_structured_indexable(structured_buffer, stride=80)(mixed,mixed,mixed,mixed) r10.xyzw, r9.z, l(0), t0.xyzw
          min r11.xy, r10.zwzz, r10.xyxx
          lt r11.xy, r6.yzyy, r11.xyxx
          or r11.x, r11.y, r11.x
          max r11.yz, r10.zzwz, r10.xxyx
          lt r11.yz, r11.yyzy, r4.zzwz
          or r11.y, r11.z, r11.y
          or r11.x, r11.y, r11.x
          if_nz r11.x
            iadd r11.x, r9.z, l(1)
            mov r9.w, l(0)
            mov r9.z, r11.x
            continue 
          endif 
          add r11.xy, -r10.xyxx, r10.zwzz
          mul r11.z, r4.y, r11.x
          mad r11.z, r4.x, r11.y, -r11.z
          lt r11.w, l(0.000000), |r11.z|
          if_nz r11.w
            add r12.xy, -r0.xyxx, r10.xyxx
            mul r11.w, r11.x, r12.y
            mad r11.w, r12.x, r11.y, -r11.w
            div r11.w, r11.w, r11.z
            mul r12.y, r4.x, r12.y
            mad r12.x, r12.x, r4.y, -r12.y
            div r11.z, r12.x, r11.z
            ge r12.x, r11.w, l(0.000000)
            ge r11.w, l(1.000000), r11.w
            and r11.w, r11.w, r12.x
            ge r12.x, r11.z, l(0.000000)
            and r11.w, r11.w, r12.x
            ge r11.z, l(1.000000), r11.z
            and r11.z, r11.z, r11.w
            if_nz r11.z
              mov r8.w, l(-1)
              mov r9.w, l(-1)
              break 
            endif 
          else 
            mov r11.z, l(0)
          endif 
          dp2 r11.w, r11.xyxx, r11.xyxx
          lt r12.x, l(0.000000), r11.w
          add r12.yz, r0.xxyx, -r10.xxyx
          dp2 r12.y, r12.yzyy, r11.xyxx
          div_sat r12.y, r12.y, r11.w
          and r12.y, r12.y, r12.x
          mad r12.yz, r11.xxyx, r12.yyyy, r10.xxyx
          add r12.yz, r0.xxyx, -r12.yyzy
          dp2 r12.y, r12.yzyy, r12.yzyy
          sqrt r12.y, r12.y
          lt r12.y, r12.y, r6.x
          add r12.zw, r7.zzzw, -r10.xxxy
          dp2 r12.z, r12.zwzz, r11.xyxx
          div_sat r11.w, r12.z, r11.w
          and r11.w, r11.w, r12.x
          mad r11.xy, r11.xyxx, r11.wwww, r10.xyxx
          add r11.xy, r7.zwzz, -r11.xyxx
          dp2 r11.x, r11.xyxx, r11.xyxx
          sqrt r11.x, r11.x
          lt r11.x, r11.x, r6.x
          or r11.x, r11.x, r12.y
          add r12.xyzw, -r0.xyxy, r10.xyzw
          dp2 r11.y, r12.xyxx, r4.xyxx
          div_sat r11.y, r11.y, r3.w
          and r11.y, r6.w, r11.y
          mad r11.yw, r4.xxxy, r11.yyyy, r0.xxxy
          add r10.xy, r10.xyxx, -r11.ywyy
          dp2 r10.x, r10.xyxx, r10.xyxx
          sqrt r10.x, r10.x
          lt r10.x, r10.x, r6.x
          or r10.x, r10.x, r11.x
          dp2 r10.y, r12.zwzz, r4.xyxx
          div_sat r10.y, r10.y, r3.w
          and r10.y, r6.w, r10.y
          mad r11.xy, r4.xyxx, r10.yyyy, r0.xyxx
          add r10.yz, r10.zzwz, -r11.xxyx
          dp2 r10.y, r10.yzyy, r10.yzyy
          sqrt r10.y, r10.y
          lt r10.y, r10.y, r6.x
          or r10.x, r10.y, r10.x
          if_nz r10.x
            mov r8.w, l(-1)
            mov r9.w, l(-1)
            break 
          endif 
          or r9.w, r11.z, r10.x
          iadd r9.z, r9.z, l(1)
        endloop 
        mov r8.x, r8.w
        mov r8.z, r9.w
        breakc_nz r9.w
        iadd r8.y, r8.y, l(1)
        mov r8.xy, r8.wyww
        mov r8.z, r9.w
      endloop 
      and r3.w, r8.x, r8.z
      not r3.w, r3.w
      and r3.y, r3.w, r3.y
      if_nz r3.y
        ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r3.y, r3.z, l(32), u1.xxxx
        ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r3.zw, r3.z, l(16), u0.xxxy
        dp2 r3.z, r3.zwzz, r3.zwzz
        sqrt r3.z, r3.z
        max r3.z, r3.z, l(0.500000)
        div r3.z, l(2.400000), r3.z
        sqrt r3.z, r3.z
        max r3.z, r3.z, l(0.500000)
        min r3.z, r3.z, l(1.200000)
        mul r5.y, r3.z, r3.y
      else 
        mov r7.zw, r0.xxxy
        mov r5.y, r5.x
      endif 
    else 
      mov r7.zw, r0.xxxy
      mov r5.y, r5.x
    endif 
    mov r7.xy, r0.xyxx
    mov r5.z, l(1)
    mov r5.w, vThreadID.x
    mov r2.x, l(0)
  else 
    mov r7.xyzw, l(0,0,0,0)
    mov r5.xyzw, l(0,0,0,0)
  endif 
  store_structured u4.xyzw, vThreadID.x, l(0), r0.xyzw
  store_structured u4.xyzw, vThreadID.x, l(16), r1.xyzw
  store_structured u4.xyzw, vThreadID.x, l(32), r2.yzwx
  store_structured u4.x, vThreadID.x, l(48), r3.x
else 
  ine r0.x, cb0[0].y, l(0)
  iadd r0.y, vThreadID.x, -cb0[1].y
  ult r0.z, r0.y, cb0[0].x
  and r0.x, r0.z, r0.x
  if_nz r0.x
    ld_structured_indexable(structured_buffer, stride=24)(mixed,mixed,mixed,mixed) r1.xyzw, r0.y, l(0), t1.xyzw
    if_nz r1.z
      ishl r0.x, cb0[1].y, l(1)
      udiv null, r0.x, r1.z, r0.x
      ld_structured_indexable(structured_buffer, stride=8)(mixed,mixed,mixed,mixed) r5.yw, r0.x, l(0), u2.xxxy
      ine r0.x, r1.z, r5.y
      uge r0.z, r5.w, cb0[1].y
      or r0.x, r0.z, r0.x
      if_z r0.x
        ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r0.x, r5.w, l(0), u1.xxxx
        ieq r0.x, r1.z, r0.x
        ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r0.z, r5.w, l(44), u0.xxxx
        ine r0.z, r0.z, l(0)
        and r0.x, r0.z, r0.x
      else 
        mov r5.w, l(0)
        mov r0.x, l(0)
      endif 
    else 
      mov r5.w, l(0)
      mov r0.x, l(0)
    endif 
    if_nz r0.x
      ld_structured_indexable(structured_buffer, stride=24)(mixed,mixed,mixed,mixed) r5.xy, r0.y, l(16), t1.yxxx
      ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r0.xy, r5.w, l(8), u1.xyxx
      ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r0.z, r5.w, l(28), u1.xxxx
      ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r0.w, r5.w, l(36), u1.xxxx
      ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r7.zw, r5.w, l(0), u0.xxxy
      ieq r0.w, r0.w, l(0)
      ieq r0.x, r1.w, r0.x
      and r0.x, r0.x, r0.w
      ieq r0.y, r5.y, r0.y
      and r0.x, r0.y, r0.x
      add r0.y, -r0.z, cb0[0].z
      ge r0.y, cb0[0].w, r0.y
      and r0.x, r0.y, r0.x
      add r0.yz, r1.xxyx, -r7.zzwz
      dp2 r0.y, r0.yzyy, r0.yzyy
      sqrt r0.y, r0.y
      ge r0.y, cb0[1].x, r0.y
      and r0.x, r0.y, r0.x
      min r0.yz, r1.xxyx, r7.zzwz
      add r0.yz, -r5.xxxx, r0.yyzy
      max r1.zw, r1.xxxy, r7.zzzw
      add r1.zw, r5.xxxx, r1.zzzw
      ine r0.w, r5.y, l(0)
      add r2.xy, -r1.xyxx, r7.zwzz
      dp2 r2.z, r2.xyxx, r2.xyxx
      lt r2.w, l(0.000000), r2.z
      mov r3.xyz, l(0,0,0,0)
      loop 
        ige r3.w, r3.y, cb0[18].x
        mov r3.z, l(0)
        breakc_nz r3.w
        ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r4.xyzw, r3.y, l(0), t2.xyzw
        ge r4.xy, r1.zwzz, r4.xyxx
        and r3.w, r4.y, r4.x
        ge r4.xy, r4.zwzz, r0.yzyy
        and r4.x, r4.y, r4.x
        and r3.w, r3.w, r4.x
        if_z r3.w
          iadd r3.w, r3.y, l(1)
          mov r3.z, l(0)
          mov r3.y, r3.w
          continue 
        endif 
        ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r4.xy, r3.y, l(32), t2.xyxx
        mov r3.w, r3.x
        mov r4.z, r4.x
        mov r4.w, l(0)
        loop 
          uge r6.x, r4.z, r4.y
          mov r4.w, l(0)
          breakc_nz r6.x
          ld_structured_indexable(structured_buffer, stride=80)(mixed,mixed,mixed,mixed) r6.xy, r4.z, l(32), t0.xyxx
          ieq r6.x, r5.y, r6.x
          and r6.x, r0.w, r6.x
          and r6.y, r6.y, l(16)
          ine r6.y, r6.y, l(0)
          or r6.x, r6.y, r6.x
          if_nz r6.x
            iadd r6.x, r4.z, l(1)
            mov r4.w, l(0)
            mov r4.z, r6.x
            continue 
          endif 
          ld_structured_indexable(structured_buffer, stride=80)(mixed,mixed,mixed,mixed) r6.xyzw, r4.z, l(0), t0.xyzw
          min r8.xy, r6.zwzz, r6.xyxx
          lt r8.xy, r1.zwzz, r8.xyxx
          or r8.x, r8.y, r8.x
          max r8.yz, r6.zzwz, r6.xxyx
          lt r8.yz, r8.yyzy, r0.yyzy
          or r8.y, r8.z, r8.y
          or r8.x, r8.y, r8.x
          if_nz r8.x
            iadd r8.x, r4.z, l(1)
            mov r4.w, l(0)
            mov r4.z, r8.x
            continue 
          endif 
          add r8.xy, -r6.xyxx, r6.zwzz
          mul r8.z, r2.y, r8.x
          mad r8.z, r2.x, r8.y, -r8.z
          lt r8.w, l(0.000000), |r8.z|
          if_nz r8.w
            add r9.xy, -r1.xyxx, r6.xyxx
            mul r8.w, r8.x, r9.y
            mad r8.w, r9.x, r8.y, -r8.w
            div r8.w, r8.w, r8.z
            mul r9.y, r2.x, r9.y
            mad r9.x, r9.x, r2.y, -r9.y
            div r8.z, r9.x, r8.z
            ge r9.x, r8.w, l(0.000000)
            ge r8.w, l(1.000000), r8.w
            and r8.w, r8.w, r9.x
            ge r9.x, r8.z, l(0.000000)
            and r8.w, r8.w, r9.x
            ge r8.z, l(1.000000), r8.z
            and r8.z, r8.z, r8.w
            if_nz r8.z
              mov r3.w, l(-1)
              mov r4.w, l(-1)
              break 
            endif 
          else 
            mov r8.z, l(0)
          endif 
          dp2 r8.w, r8.xyxx, r8.xyxx
          lt r9.x, l(0.000000), r8.w
          add r9.yz, r1.xxyx, -r6.xxyx
          dp2 r9.y, r9.yzyy, r8.xyxx
          div_sat r9.y, r9.y, r8.w
          and r9.y, r9.y, r9.x
          mad r9.yz, r8.xxyx, r9.yyyy, r6.xxyx
          add r9.yz, r1.xxyx, -r9.yyzy
          dp2 r9.y, r9.yzyy, r9.yzyy
          sqrt r9.y, r9.y
          lt r9.y, r9.y, r5.x
          add r9.zw, -r6.xxxy, r7.zzzw
          dp2 r9.z, r9.zwzz, r8.xyxx
          div_sat r8.w, r9.z, r8.w
          and r8.w, r8.w, r9.x
          mad r8.xy, r8.xyxx, r8.wwww, r6.xyxx
          add r8.xy, r7.zwzz, -r8.xyxx
          dp2 r8.x, r8.xyxx, r8.xyxx
          sqrt r8.x, r8.x
          lt r8.x, r8.x, r5.x
          or r8.x, r8.x, r9.y
          add r9.xyzw, -r1.xyxy, r6.xyzw
          dp2 r8.y, r9.xyxx, r2.xyxx
          div_sat r8.y, r8.y, r2.z
          and r8.y, r2.w, r8.y
          mad r8.yw, r2.xxxy, r8.yyyy, r1.xxxy
          add r6.xy, r6.xyxx, -r8.ywyy
          dp2 r6.x, r6.xyxx, r6.xyxx
          sqrt r6.x, r6.x
          lt r6.x, r6.x, r5.x
          or r6.x, r6.x, r8.x
          dp2 r6.y, r9.zwzz, r2.xyxx
          div_sat r6.y, r6.y, r2.z
          and r6.y, r2.w, r6.y
          mad r8.xy, r2.xyxx, r6.yyyy, r1.xyxx
          add r6.yz, r6.zzwz, -r8.xxyx
          dp2 r6.y, r6.yzyy, r6.yzyy
          sqrt r6.y, r6.y
          lt r6.y, r6.y, r5.x
          or r6.x, r6.y, r6.x
          if_nz r6.x
            mov r3.w, l(-1)
            mov r4.w, l(-1)
            break 
          endif 
          or r4.w, r8.z, r6.x
          iadd r4.z, r4.z, l(1)
        endloop 
        mov r3.x, r3.w
        mov r3.z, r4.w
        breakc_nz r4.w
        iadd r3.y, r3.y, l(1)
        mov r3.xy, r3.wyww
        mov r3.z, r4.w
      endloop 
      and r0.y, r3.x, r3.z
      not r0.y, r0.y
      and r0.x, r0.y, r0.x
      if_nz r0.x
        ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r0.x, r5.w, l(32), u1.xxxx
        ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r0.yz, r5.w, l(16), u0.xxyx
        dp2 r0.y, r0.yzyy, r0.yzyy
        sqrt r0.y, r0.y
        max r0.y, r0.y, l(0.500000)
        div r0.y, l(2.400000), r0.y
        sqrt r0.y, r0.y
        max r0.y, r0.y, l(0.500000)
        min r0.y, r0.y, l(1.200000)
        mul r5.y, r0.y, r0.x
        mov r7.xy, r1.xyxx
        mov r5.z, l(1)
      else 
        mov r7.xyzw, l(0,0,0,0)
        mov r5.xyzw, l(0,0,0,0)
      endif 
    else 
      mov r7.xyzw, l(0,0,0,0)
      mov r5.xyzw, l(0,0,0,0)
    endif 
  else 
    mov r7.xyzw, l(0,0,0,0)
    mov r5.xyzw, l(0,0,0,0)
  endif 
endif 
store_structured u3.xyzw, vThreadID.x, l(0), r7.xyzw
store_structured u3.xyzw, vThreadID.x, l(16), r5.xyzw
ret 
// Approximately 478 instruction slots used
