//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer $Globals
// {
//
//   int _StreamHeadCount;              // Offset:    0 Size:     4 [unused]
//   int _StreamRenderingEnabled;       // Offset:    4 Size:     4 [unused]
//   float _SimulationTime;             // Offset:    8 Size:     4 [unused]
//   float _StreamMaximumGap;           // Offset:   12 Size:     4 [unused]
//   float _StreamMaximumLength;        // Offset:   16 Size:     4 [unused]
//   int _ParticleCapacity;             // Offset:   20 Size:     4
//   int _MaximumIngredients;           // Offset:   24 Size:     4 [unused]
//   int _IngredientCount;              // Offset:   28 Size:     4 [unused]
//   int _SpawnCount;                   // Offset:   32 Size:     4 [unused]
//   int _GridWidth;                    // Offset:   36 Size:     4
//   int _GridHeight;                   // Offset:   40 Size:     4
//   int _GridCellCount;                // Offset:   44 Size:     4 [unused]
//   int _BoundaryCount;                // Offset:   48 Size:     4 [unused]
//   int _VesselTriggerCount;           // Offset:   52 Size:     4 [unused]
//   int _AgitatorCount;                // Offset:   56 Size:     4 [unused]
//   int _TechniqueTargetVessel;        // Offset:   60 Size:     4 [unused]
//   int _TechniqueMask;                // Offset:   64 Size:     4 [unused]
//   int _TechniqueStateMask;           // Offset:   68 Size:     4 [unused]
//   int _TransformTargetVessel;        // Offset:   72 Size:     4 [unused]
//   int _SuspensionTargetVessel;       // Offset:   76 Size:     4 [unused]
//   int _SuspensionEnabled;            // Offset:   80 Size:     4 [unused]
//   int _ReferenceSolverEnabled;       // Offset:   84 Size:     4 [unused]
//   int _ImprovedPhysics;              // Offset:   88 Size:     4 [unused]
//   int _TransferTargetVessel;         // Offset:   92 Size:     4 [unused]
//   float _ReferenceParticleVolume;    // Offset:   96 Size:     4 [unused]
//   float _ReferenceRestDensity;       // Offset:  100 Size:     4 [unused]
//   float _ReferencePressureStiffness; // Offset:  104 Size:     4 [unused]
//   float _ReferenceNearPressureStiffness;// Offset:  108 Size:     4 [unused]
//   float _ReferenceViscosityRate;     // Offset:  112 Size:     4 [unused]
//   float _ReferenceMaximumTensionRatio;// Offset:  116 Size:     4 [unused]
//   float _ReferenceMaximumAcceleration;// Offset:  120 Size:     4 [unused]
//   float _ReferenceMaximumDisplacementRatio;// Offset:  124 Size:     4 [unused]
//   float _DeltaTime;                  // Offset:  128 Size:     4 [unused]
//   float _ParticleRadius;             // Offset:  132 Size:     4 [unused]
//   float _SmoothingRadius;            // Offset:  136 Size:     4
//   float _RestDensity;                // Offset:  140 Size:     4 [unused]
//   float _DensityCompliance;          // Offset:  144 Size:     4 [unused]
//   float _LambdaEpsilon;              // Offset:  148 Size:     4 [unused]
//   float _ArtificialPressureStrength; // Offset:  152 Size:     4 [unused]
//   float _ArtificialPressureRadiusRatio;// Offset:  156 Size:     4 [unused]
//   float _BoundaryDensityScale;       // Offset:  160 Size:     4 [unused]
//   float _WallFriction;               // Offset:  164 Size:     4 [unused]
//   float _WallRestitution;            // Offset:  168 Size:     4 [unused]
//   float _SplashTransfer;             // Offset:  172 Size:     4 [unused]
//   float _SplashMinimumImpactSpeed;   // Offset:  176 Size:     4 [unused]
//   float _BottomImpactSpread;         // Offset:  180 Size:     4 [unused]
//   float _VelocityDamping;            // Offset:  184 Size:     4 [unused]
//   float _MaximumSpeed;               // Offset:  188 Size:     4 [unused]
//   float _ClosedVesselDampingRate;    // Offset:  192 Size:     4 [unused]
//   float _ClosedVesselMaximumRelativeSpeed;// Offset:  196 Size:     4 [unused]
//   float _Viscosity;                  // Offset:  200 Size:     4 [unused]
//   float _PassiveMixRate;             // Offset:  204 Size:     4
//   float _AgitationMixRate;           // Offset:  208 Size:     4
//   float _FullMixRelativeSpeed;       // Offset:  212 Size:     4
//   float _MaximumMixPerSubstep;       // Offset:  216 Size:     4
//   float _MinimumVisibleAlpha;        // Offset:  220 Size:     4 [unused]
//   float2 _Gravity;                   // Offset:  224 Size:     8 [unused]
//   float2 _GridOrigin;                // Offset:  232 Size:     8
//   float2 _WorldMin;                  // Offset:  240 Size:     8 [unused]
//   float2 _WorldMax;                  // Offset:  248 Size:     8 [unused]
//   float2 _TransformDelta;            // Offset:  256 Size:     8 [unused]
//   int _SwapA;                        // Offset:  264 Size:     4 [unused]
//   int _SwapB;                        // Offset:  268 Size:     4 [unused]
//   float2 _SwapDeltaA;                // Offset:  272 Size:     8 [unused]
//   float2 _SwapDeltaB;                // Offset:  280 Size:     8 [unused]
//   int _BoundaryGroupCount;           // Offset:  288 Size:     4 [unused]
//   int _ImprovedVesselCount;          // Offset:  292 Size:     4 [unused]
//   float _ImprovedAreaPerMl;          // Offset:  296 Size:     4 [unused]
//   float _ImprovedKernelRatio;        // Offset:  300 Size:     4 [unused]
//   float _ImprovedCompliance;         // Offset:  304 Size:     4 [unused]
//   float _ImprovedCorrectionRatio;    // Offset:  308 Size:     4 [unused]
//   float _ImprovedWallDensity;        // Offset:  312 Size:     4 [unused]
//   float _ImprovedShear;              // Offset:  316 Size:     4 [unused]
//   float _ImprovedTension;            // Offset:  320 Size:     4 [unused]
//   float _ImprovedWetting;            // Offset:  324 Size:     4 [unused]
//
// }
//
// Resource bind info for _Particles
// {
//
//   struct LiquidParticle
//   {
//       
//       float2 position;               // Offset:    0
//       float2 previousPosition;       // Offset:    8
//       float2 velocity;               // Offset:   16
//       float volumeMl;                // Offset:   24
//       float temperatureC;            // Offset:   28
//       uint vesselId;                 // Offset:   32
//       uint techniqueFlags;           // Offset:   36
//       uint stateFlags;               // Offset:   40
//       uint active;                   // Offset:   44
//       uint padding;                  // Offset:   48
//
//   } $Element;                        // Offset:    0 Size:    52
//
// }
//
// Resource bind info for _ConservativeMixWeights
// {
//
//   float $Element;                    // Offset:    0 Size:     4
//
// }
//
// Resource bind info for _GridHeads
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
// Resource bind info for _GridNext
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
// Resource bind info for _StreamParticles
// {
//
//   struct StreamParticle
//   {
//       
//       uint token;                    // Offset:    0
//       uint previousToken;            // Offset:    4
//       uint streamId;                 // Offset:    8
//       uint sourceId;                 // Offset:   12
//       float delay;                   // Offset:   16
//       float stepDt;                  // Offset:   20
//       float startFraction;           // Offset:   24
//       float birthTime;               // Offset:   28
//       float radius;                  // Offset:   32
//       uint detached;                 // Offset:   36
//       uint pending;                  // Offset:   40
//       uint padding;                  // Offset:   44
//
//   } $Element;                        // Offset:    0 Size:    48
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// _Particles                            UAV  struct         r/w             u0      1 
// _ConservativeMixWeights               UAV  struct         r/w             u1      1 
// _GridHeads                            UAV  struct         r/w             u2      1 
// _GridNext                             UAV  struct         r/w             u3      1 
// _StreamParticles                      UAV  struct         r/w             u4      1 
// $Globals                          cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[15], immediateIndexed
dcl_uav_structured u0, 52
dcl_uav_structured u1, 4
dcl_uav_structured u2, 4
dcl_uav_structured u3, 4
dcl_uav_structured u4, 48
dcl_input vThreadID.x
dcl_temps 9
dcl_thread_group 64, 1, 1
uge r0.x, vThreadID.x, cb0[1].y
if_nz r0.x
  ret 
endif 
ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r0.xy, vThreadID.x, l(0), u0.xyxx
ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r1.xyz, vThreadID.x, l(16), u0.xyzx
ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r0.z, vThreadID.x, l(32), u0.xxxx
ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r2.xy, vThreadID.x, l(40), u0.xyxx
ine r0.w, r2.y, l(0)
lt r1.w, l(0.000000), r1.z
and r0.w, r0.w, r1.w
if_nz r0.w
  add r2.zw, r0.xxxy, -cb0[14].zzzw
  div r2.zw, r2.zzzw, cb0[8].zzzz
  round_ni r2.zw, r2.zzzw
  ftoi r2.zw, r2.zzzw
  ieq r0.w, r2.y, l(0)
  ge r1.w, l(0.000000), r1.z
  max r2.y, cb0[8].z, l(0.000010)
  max r3.x, cb0[13].y, l(0.010000)
  mov r3.yz, cb0[2].yyzy
  mov r3.w, l(0)
  mov r4.y, l(-1)
  loop 
    ilt r4.z, l(1), r4.y
    breakc_nz r4.z
    mov r4.z, r3.w
    mov r4.x, l(-1)
    loop 
      ilt r4.w, l(1), r4.x
      breakc_nz r4.w
      iadd r5.xy, r2.zwzz, r4.xyxx
      ige r5.zw, r5.xxxy, l(0, 0, 0, 0)
      and r4.w, r5.w, r5.z
      ilt r5.z, r5.x, r3.y
      and r4.w, r4.w, r5.z
      ilt r5.z, r5.y, r3.z
      and r4.w, r4.w, r5.z
      if_z r4.w
        iadd r4.w, r4.x, l(1)
        mov r4.x, r4.w
        continue 
      endif 
      imad r4.w, r5.y, r3.y, r5.x
      ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r4.w, r4.w, l(0), u2.xxxx
      ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r5.x, vThreadID.x, l(20), u4.xxxx
      mov r5.y, r4.z
      mov r5.z, r4.w
      mov r5.w, l(0)
      loop 
        ige r6.x, r5.z, l(0)
        ilt r6.y, r5.w, cb0[1].y
        and r6.x, r6.y, r6.x
        breakc_z r6.x
        iadd r5.w, r5.w, l(1)
        ine r6.x, r5.z, vThreadID.x
        if_nz r6.x
          ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r6.xy, r5.z, l(0), u0.xyxx
          ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r7.xyz, r5.z, l(16), u0.xyzx
          ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r6.z, r5.z, l(32), u0.xxxx
          ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r8.xy, r5.z, l(40), u0.xyxx
          ieq r6.w, r8.y, l(0)
          or r6.w, r0.w, r6.w
          or r6.w, r1.w, r6.w
          ge r7.w, l(0.000000), r7.z
          or r6.w, r6.w, r7.w
          or r7.w, r2.x, r8.x
          and r7.w, r7.w, l(4)
          ine r7.w, r7.w, l(0)
          or r6.w, r6.w, r7.w
          ine r6.z, r0.z, r6.z
          or r6.z, r6.z, r6.w
          if_z r6.z
            ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r6.z, r5.z, l(20), u4.xxxx
            min r6.z, r5.x, r6.z
            lt r6.w, l(0.000001), r6.z
            add r6.xy, r0.xyxx, -r6.xyxx
            dp2 r6.x, r6.xyxx, r6.xyxx
            sqrt r6.x, r6.x
            div r6.x, r6.x, r2.y
            add r6.x, -r6.x, l(1.000000)
            max r6.x, r6.x, l(0.000000)
            add r7.xy, r1.xyxx, -r7.xyxx
            dp2 r6.y, r7.xyxx, r7.xyxx
            sqrt r6.y, r6.y
            div r6.y, r6.y, r3.x
            min r6.y, r6.y, l(1.000000)
            mad r6.y, cb0[13].x, r6.y, cb0[12].w
            mul r6.x, r6.x, r6.y
            mul r6.x, r6.z, r6.x
            min r6.x, r6.x, cb0[13].z
            mul r6.x, r6.x, l(0.031250)
            mul r6.y, r1.z, r7.z
            add r6.z, r1.z, r7.z
            div r6.y, r6.y, r6.z
            mul r6.x, r6.y, r6.x
            and r6.x, r6.x, r6.w
          else 
            mov r6.x, l(0)
          endif 
          div r6.x, r6.x, r1.z
          add r5.y, r5.y, r6.x
        endif 
        ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r5.z, r5.z, l(0), u3.xxxx
      endloop 
      mov r4.z, r5.y
      iadd r4.x, r4.x, l(1)
    endloop 
    mov r3.w, r4.z
    iadd r4.y, r4.y, l(1)
  endloop 
else 
  mov r3.w, l(0)
endif 
max r0.x, cb0[13].z, l(0.000010)
div r0.x, r3.w, r0.x
max r0.x, r0.x, l(1.000000)
store_structured u1.x, vThreadID.x, l(0), r0.x
ret 
// Approximately 119 instruction slots used
