//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer $Globals
// {
//
//   int _StreamHeadCount;              // Offset:    0 Size:     4 [unused]
//   int _StreamRenderingEnabled;       // Offset:    4 Size:     4 [unused]
//   float _SimulationTime;             // Offset:    8 Size:     4 [unused]
//   float _StreamMaximumGap;           // Offset:   12 Size:     4 [unused]
//   float _StreamMaximumLength;        // Offset:   16 Size:     4 [unused]
//   int _ParticleCapacity;             // Offset:   20 Size:     4
//   int _MaximumIngredients;           // Offset:   24 Size:     4
//   int _IngredientCount;              // Offset:   28 Size:     4
//   int _SpawnCount;                   // Offset:   32 Size:     4 [unused]
//   int _GridWidth;                    // Offset:   36 Size:     4
//   int _GridHeight;                   // Offset:   40 Size:     4
//   int _GridCellCount;                // Offset:   44 Size:     4 [unused]
//   int _BoundaryCount;                // Offset:   48 Size:     4 [unused]
//   int _VesselTriggerCount;           // Offset:   52 Size:     4
//   int _AgitatorCount;                // Offset:   56 Size:     4 [unused]
//   int _TechniqueTargetVessel;        // Offset:   60 Size:     4 [unused]
//   int _TechniqueMask;                // Offset:   64 Size:     4 [unused]
//   int _TechniqueStateMask;           // Offset:   68 Size:     4 [unused]
//   int _TransformTargetVessel;        // Offset:   72 Size:     4 [unused]
//   int _SuspensionTargetVessel;       // Offset:   76 Size:     4 [unused]
//   int _SuspensionEnabled;            // Offset:   80 Size:     4 [unused]
//   int _ReferenceSolverEnabled;       // Offset:   84 Size:     4 [unused]
//   int _ImprovedPhysics;              // Offset:   88 Size:     4 [unused]
//   int _TransferTargetVessel;         // Offset:   92 Size:     4 [unused]
//   float _ReferenceParticleVolume;    // Offset:   96 Size:     4
//   float _ReferenceRestDensity;       // Offset:  100 Size:     4 [unused]
//   float _ReferencePressureStiffness; // Offset:  104 Size:     4 [unused]
//   float _ReferenceNearPressureStiffness;// Offset:  108 Size:     4 [unused]
//   float _ReferenceViscosityRate;     // Offset:  112 Size:     4 [unused]
//   float _ReferenceMaximumTensionRatio;// Offset:  116 Size:     4 [unused]
//   float _ReferenceMaximumAcceleration;// Offset:  120 Size:     4 [unused]
//   float _ReferenceMaximumDisplacementRatio;// Offset:  124 Size:     4 [unused]
//   float _DeltaTime;                  // Offset:  128 Size:     4 [unused]
//   float _ParticleRadius;             // Offset:  132 Size:     4
//   float _SmoothingRadius;            // Offset:  136 Size:     4
//   float _RestDensity;                // Offset:  140 Size:     4 [unused]
//   float _DensityCompliance;          // Offset:  144 Size:     4 [unused]
//   float _LambdaEpsilon;              // Offset:  148 Size:     4 [unused]
//   float _ArtificialPressureStrength; // Offset:  152 Size:     4 [unused]
//   float _ArtificialPressureRadiusRatio;// Offset:  156 Size:     4 [unused]
//   float _BoundaryDensityScale;       // Offset:  160 Size:     4 [unused]
//   float _WallFriction;               // Offset:  164 Size:     4 [unused]
//   float _WallRestitution;            // Offset:  168 Size:     4 [unused]
//   float _SplashTransfer;             // Offset:  172 Size:     4 [unused]
//   float _SplashMinimumImpactSpeed;   // Offset:  176 Size:     4 [unused]
//   float _BottomImpactSpread;         // Offset:  180 Size:     4 [unused]
//   float _VelocityDamping;            // Offset:  184 Size:     4 [unused]
//   float _MaximumSpeed;               // Offset:  188 Size:     4 [unused]
//   float _ClosedVesselDampingRate;    // Offset:  192 Size:     4 [unused]
//   float _ClosedVesselMaximumRelativeSpeed;// Offset:  196 Size:     4 [unused]
//   float _Viscosity;                  // Offset:  200 Size:     4 [unused]
//   float _PassiveMixRate;             // Offset:  204 Size:     4 [unused]
//   float _AgitationMixRate;           // Offset:  208 Size:     4 [unused]
//   float _FullMixRelativeSpeed;       // Offset:  212 Size:     4 [unused]
//   float _MaximumMixPerSubstep;       // Offset:  216 Size:     4 [unused]
//   float _MinimumVisibleAlpha;        // Offset:  220 Size:     4 [unused]
//   float2 _Gravity;                   // Offset:  224 Size:     8 [unused]
//   float2 _GridOrigin;                // Offset:  232 Size:     8
//   float2 _WorldMin;                  // Offset:  240 Size:     8 [unused]
//   float2 _WorldMax;                  // Offset:  248 Size:     8 [unused]
//   float2 _TransformDelta;            // Offset:  256 Size:     8 [unused]
//   int _SwapA;                        // Offset:  264 Size:     4 [unused]
//   int _SwapB;                        // Offset:  268 Size:     4 [unused]
//   float2 _SwapDeltaA;                // Offset:  272 Size:     8 [unused]
//   float2 _SwapDeltaB;                // Offset:  280 Size:     8 [unused]
//   int _BoundaryGroupCount;           // Offset:  288 Size:     4
//   int _ImprovedVesselCount;          // Offset:  292 Size:     4
//   float _ImprovedAreaPerMl;          // Offset:  296 Size:     4
//   float _ImprovedKernelRatio;        // Offset:  300 Size:     4
//   float _ImprovedCompliance;         // Offset:  304 Size:     4 [unused]
//   float _ImprovedCorrectionRatio;    // Offset:  308 Size:     4
//   float _ImprovedWallDensity;        // Offset:  312 Size:     4 [unused]
//   float _ImprovedShear;              // Offset:  316 Size:     4
//   float _ImprovedTension;            // Offset:  320 Size:     4
//   float _ImprovedWetting;            // Offset:  324 Size:     4
//
// }
//
// Resource bind info for _CompositionRead
// {
//
//   float $Element;                    // Offset:    0 Size:     4
//
// }
//
// Resource bind info for _Boundaries
// {
//
//   struct BoundarySegment
//   {
//       
//       float2 a;                      // Offset:    0
//       float2 b;                      // Offset:    8
//       float2 velocityA;              // Offset:   16
//       float2 velocityB;              // Offset:   24
//       uint vesselId;                 // Offset:   32
//       uint flags;                    // Offset:   36
//       float2 localA;                 // Offset:   40
//       float2 localB;                 // Offset:   48
//       float2 startPosition;          // Offset:   56
//       float2 endPosition;            // Offset:   64
//       float startAngle;              // Offset:   72
//       float angleDelta;              // Offset:   76
//
//   } $Element;                        // Offset:    0 Size:    80
//
// }
//
// Resource bind info for _VesselTriggers
// {
//
//   struct VesselTrigger
//   {
//       
//       float2 center;                 // Offset:    0
//       float2 axisX;                  // Offset:    8
//       float2 axisY;                  // Offset:   16
//       float2 halfExtents;            // Offset:   24
//       uint vesselId;                 // Offset:   32
//       int priority;                  // Offset:   36
//       uint active;                   // Offset:   40
//       uint flags;                    // Offset:   44
//
//   } $Element;                        // Offset:    0 Size:    48
//
// }
//
// Resource bind info for _BoundaryGroups
// {
//
//   struct BoundaryGroup
//   {
//       
//       float2 minPosition;            // Offset:    0
//       float2 maxPosition;            // Offset:    8
//       float2 sweptMin;               // Offset:   16
//       float2 sweptMax;               // Offset:   24
//       uint first;                    // Offset:   32
//       uint end;                      // Offset:   36
//       uint contourFirst;             // Offset:   40
//       uint contourEnd;               // Offset:   44
//       uint vesselId;                 // Offset:   48
//
//   } $Element;                        // Offset:    0 Size:    52
//
// }
//
// Resource bind info for _ImprovedVessels
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
// Resource bind info for _ImprovedMaterials
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
// Resource bind info for _Particles
// {
//
//   struct LiquidParticle
//   {
//       
//       float2 position;               // Offset:    0
//       float2 previousPosition;       // Offset:    8
//       float2 velocity;               // Offset:   16
//       float volumeMl;                // Offset:   24
//       float temperatureC;            // Offset:   28
//       uint vesselId;                 // Offset:   32
//       uint techniqueFlags;           // Offset:   36
//       uint stateFlags;               // Offset:   40
//       uint active;                   // Offset:   44
//       uint padding;                  // Offset:   48
//
//   } $Element;                        // Offset:    0 Size:    52
//
// }
//
// Resource bind info for _PositionDeltas
// {
//
//   float2 $Element;                   // Offset:    0 Size:     8
//
// }
//
// Resource bind info for _VelocitySnapshot
// {
//
//   float2 $Element;                   // Offset:    0 Size:     8
//
// }
//
// Resource bind info for _ReferenceDensityPressure
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
// Resource bind info for _GridHeads
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
// Resource bind info for _GridNext
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
// Resource bind info for _StreamParticles
// {
//
//   struct StreamParticle
//   {
//       
//       uint token;                    // Offset:    0
//       uint previousToken;            // Offset:    4
//       uint streamId;                 // Offset:    8
//       uint sourceId;                 // Offset:   12
//       float delay;                   // Offset:   16
//       float stepDt;                  // Offset:   20
//       float startFraction;           // Offset:   24
//       float birthTime;               // Offset:   28
//       float radius;                  // Offset:   32
//       uint detached;                 // Offset:   36
//       uint pending;                  // Offset:   40
//       uint padding;                  // Offset:   44
//
//   } $Element;                        // Offset:    0 Size:    48
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// _CompositionRead                  texture  struct         r/o             t0      1 
// _Boundaries                       texture  struct         r/o             t1      1 
// _VesselTriggers                   texture  struct         r/o             t2      1 
// _BoundaryGroups                   texture  struct         r/o             t3      1 
// _ImprovedVessels                  texture  struct         r/o             t4      1 
// _ImprovedMaterials                texture  struct         r/o             t5      1 
// _Particles                            UAV  struct         r/w             u0      1 
// _PositionDeltas                       UAV  struct         r/w             u1      1 
// _VelocitySnapshot                     UAV  struct         r/w             u2      1 
// _ReferenceDensityPressure             UAV  struct         r/w             u3      1 
// _GridHeads                            UAV  struct         r/w             u4      1 
// _GridNext                             UAV  struct         r/w             u5      1 
// _StreamParticles                      UAV  struct         r/w             u6      1 
// $Globals                          cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[21], immediateIndexed
dcl_resource_structured t0, 4
dcl_resource_structured t1, 80
dcl_resource_structured t2, 48
dcl_resource_structured t3, 52
dcl_resource_structured t4, 16
dcl_resource_structured t5, 16
dcl_uav_structured u0, 52
dcl_uav_structured u1, 8
dcl_uav_structured u2, 8
dcl_uav_structured u3, 16
dcl_uav_structured u4, 4
dcl_uav_structured u5, 4
dcl_uav_structured u6, 48
dcl_input vThreadID.x
dcl_temps 12
dcl_thread_group 64, 1, 1
uge r0.x, vThreadID.x, cb0[1].y
if_nz r0.x
  ret 
endif 
ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r0.xy, vThreadID.x, l(0), u0.xyxx
ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r0.z, vThreadID.x, l(24), u0.xxxx
ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r0.w, vThreadID.x, l(32), u0.xxxx
ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r1.xy, vThreadID.x, l(40), u0.xyxx
ine r1.y, r1.y, l(0)
and r1.x, r1.x, l(4)
ieq r1.x, r1.x, l(0)
and r1.x, r1.x, r1.y
ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r1.y, vThreadID.x, l(20), u6.xxxx
lt r1.y, l(0.000001), r1.y
and r1.x, r1.y, r1.x
if_z r1.x
  store_structured u1.xy, vThreadID.x, l(0), l(0,0,0,0)
  ret 
endif 
mov r1.yz, l(0,0,0,0)
mov r2.xyz, l(0,0,0,0)
mov r1.w, l(0)
loop 
  ige r2.w, r2.z, cb0[18].y
  mov r1.w, l(0)
  breakc_nz r2.w
  ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r2.w, r2.z, l(0), t4.xxxx
  ftou r2.w, r2.w
  ieq r2.w, r0.w, r2.w
  if_nz r2.w
    ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r2.xy, r2.z, l(4), t4.xyxx
    mov r1.w, l(-1)
    break 
  endif 
  iadd r1.x, r2.z, l(1)
  mov r2.xyz, r1.yzxy
  mov r1.w, r2.w
endloop 
mul r1.x, cb0[6].x, cb0[18].z
sqrt r1.x, r1.x
mul r1.x, r1.x, cb0[18].w
mul r1.yz, cb0[8].yyyy, l(0.000000, 2.100000, 2.500000, 0.000000)
max r1.x, r1.y, r1.x
min r1.y, r1.x, cb0[8].z
mov r1.x, cb0[18].z
movc r1.xy, r1.wwww, r2.xyxx, r1.xyxx
ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r1.w, vThreadID.x, l(20), u6.xxxx
mov r2.xyzw, l(0,0,0,0)
loop 
  ige r3.x, r2.w, cb0[1].w
  breakc_nz r3.x
  imad r3.x, vThreadID.x, cb0[1].z, r2.w
  ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r3.x, r3.x, l(0), t0.xxxx
  max r3.x, r3.x, l(0.000000)
  ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r3.yzw, r2.w, l(0), t5.xxyz
  mad r2.xyz, r3.xxxx, r3.yzwy, r2.xyzx
  iadd r2.w, r2.w, l(1)
endloop 
add r3.xy, r0.xyxx, -cb0[14].zwzz
div r3.xy, r3.xyxx, cb0[8].zzzz
round_ni r3.xy, r3.xyxx
ftoi r3.xy, r3.xyxx
mov r4.xyzw, l(0,0,0,0)
mov r2.w, cb0[2].y
mov r3.z, cb0[2].z
mov r5.y, l(-1)
loop 
  ilt r3.w, l(1), r5.y
  breakc_nz r3.w
  mov r5.zw, r4.xxxy
  mov r6.xy, r4.zwzz
  mov r5.x, l(-1)
  loop 
    ilt r3.w, l(1), r5.x
    breakc_nz r3.w
    iadd r6.zw, r3.xxxy, r5.xxxy
    ige r7.xy, r6.zwzz, l(0, 0, 0, 0)
    and r3.w, r7.y, r7.x
    ilt r7.x, r6.z, r2.w
    and r3.w, r3.w, r7.x
    ilt r7.x, r6.w, r3.z
    and r3.w, r3.w, r7.x
    if_z r3.w
      iadd r3.w, r5.x, l(1)
      mov r5.x, r3.w
      continue 
    endif 
    imad r3.w, r6.w, r2.w, r6.z
    ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r3.w, r3.w, l(0), u4.xxxx
    mov r6.zw, r5.zzzw
    mov r7.xy, r6.xyxx
    mov r7.z, r3.w
    mov r7.w, l(0)
    loop 
      ige r8.x, r7.z, l(0)
      ilt r8.y, r7.w, cb0[1].y
      and r8.x, r8.y, r8.x
      breakc_z r8.x
      iadd r7.w, r7.w, l(1)
      ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r8.xy, r7.z, l(0), u0.xyxx
      ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r8.z, r7.z, l(24), u0.xxxx
      ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r8.w, r7.z, l(32), u0.xxxx
      ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r9.xy, r7.z, l(40), u0.xyxx
      ine r9.z, r7.z, vThreadID.x
      ine r9.y, r9.y, l(0)
      and r9.x, r9.x, l(4)
      ieq r9.x, r9.x, l(0)
      and r9.x, r9.x, r9.y
      ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r9.y, r7.z, l(20), u6.xxxx
      lt r9.w, l(0.000001), r9.y
      and r9.x, r9.w, r9.x
      and r9.x, r9.x, r9.z
      ieq r8.w, r0.w, r8.w
      and r8.w, r8.w, r9.x
      if_nz r8.w
        add r8.xy, r0.xyxx, -r8.xyxx
        dp2 r8.w, r8.xyxx, r8.xyxx
        sqrt r8.w, r8.w
        div r9.x, r8.w, r1.y
        add_sat r9.x, -r9.x, l(1.000000)
        lt r9.z, l(0.000000), r9.x
        lt r9.w, l(0.000001), r8.w
        and r9.z, r9.w, r9.z
        if_nz r9.z
          min r9.y, r1.w, r9.y
          add r9.z, r0.z, r8.z
          max r9.w, r9.z, l(0.000001)
          div r8.z, r8.z, r9.w
          mov r10.xy, l(0,0,0,0)
          mov r9.w, l(0)
          loop 
            ige r10.z, r9.w, cb0[1].w
            breakc_nz r10.z
            imad r10.z, r7.z, cb0[1].z, r9.w
            ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r10.z, r10.z, l(0), t0.xxxx
            max r10.z, r10.z, l(0.000000)
            ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r11.xy, r9.w, l(0), t5.xyxx
            mad r10.xy, r10.zzzz, r11.xyxx, r10.xyxx
            iadd r9.w, r9.w, l(1)
          endloop 
          add r10.zw, r2.xxxy, r10.xxxy
          mul r9.w, r10.z, cb0[19].w
          mul r9.w, r9.y, r9.w
          mul r9.w, r9.w, l(-0.721348)
          exp r9.w, r9.w
          add r9.w, -r9.w, l(1.000000)
          ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r10.z, vThreadID.x, l(12), u3.xxxx
          ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r11.x, r7.z, l(12), u3.xxxx
          max r10.z, r10.z, r11.x
          max r10.z, r10.z, l(1.000000)
          ld_structured_indexable(structured_buffer, stride=8)(mixed,mixed,mixed,mixed) r11.xy, r7.z, l(0), u2.xyxx
          ld_structured_indexable(structured_buffer, stride=8)(mixed,mixed,mixed,mixed) r11.zw, vThreadID.x, l(0), u2.xxxy
          add r11.xy, -r11.zwzz, r11.xyxx
          mul r11.xy, r9.wwww, r11.xyxx
          mul r11.xy, r9.xxxx, r11.xyxx
          mul r11.xy, r8.zzzz, r11.xyxx
          div r11.xy, r11.xyxx, r10.zzzz
          add r6.zw, r6.zzzw, r11.xxxy
          mul r9.z, r1.x, r9.z
          mul r9.z, r9.z, l(0.577350)
          sqrt r9.z, r9.z
          div r8.xy, r8.xyxx, r8.wwww
          add r8.w, r8.w, -r9.z
          max r9.z, r9.z, l(0.001000)
          div_sat r8.w, r8.w, r9.z
          mul r8.xy, r8.wwww, r8.xyxx
          mul r8.w, r9.x, r9.x
          mul r8.xy, r8.xyxx, r8.wwww
          mul r8.xy, r8.xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)
          mul r8.xy, r10.wwww, r8.xyxx
          mul r8.xy, r8.xyxx, cb0[20].xxxx
          mul r8.xy, r8.zzzz, r8.xyxx
          div r8.z, r9.y, r1.w
          mad r7.xy, -r8.xyxx, r8.zzzz, r7.xyxx
        endif 
      endif 
      ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r7.z, r7.z, l(0), u5.xxxx
    endloop 
    mov r5.zw, r6.zzzw
    mov r6.xy, r7.xyxx
    iadd r5.x, r5.x, l(1)
  endloop 
  mov r4.xy, r5.zwzz
  mov r4.zw, r6.xxxy
  iadd r5.y, r5.y, l(1)
endloop 
add r2.xy, r0.xyxx, -r1.yyyy
add r3.xy, r0.xyxx, r1.yyyy
mov r5.y, l(0)
mov r3.zw, l(0,0,0,0)
mov r5.zw, l(0,0,0,0)
mov r0.z, r1.y
mov r1.x, l(0)
mov r2.w, l(0)
loop 
  ige r6.x, r2.w, cb0[18].x
  breakc_nz r6.x
  ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r6.xyzw, r2.w, l(0), t3.xyzw
  ge r6.xy, r3.xyxx, r6.xyxx
  and r6.x, r6.y, r6.x
  ge r6.yz, r6.zzwz, r2.xxyx
  and r6.y, r6.z, r6.y
  and r6.x, r6.y, r6.x
  if_z r6.x
    iadd r6.x, r2.w, l(1)
    mov r2.w, r6.x
    continue 
  endif 
  ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r6.xy, r2.w, l(32), t3.xyxx
  mov r6.zw, r3.zzzw
  mov r7.xy, r5.zwzz
  mov r7.z, r0.z
  mov r7.w, r1.x
  mov r8.x, r6.x
  loop 
    uge r8.y, r8.x, r6.y
    breakc_nz r8.y
    ld_structured_indexable(structured_buffer, stride=80)(mixed,mixed,mixed,mixed) r8.yz, r8.x, l(32), t1.xxyx
    and r8.w, r8.z, l(16)
    if_z r8.w
      ine r8.y, r0.w, r8.y
      if_nz r8.y
        and r8.y, r8.z, l(2)
        ine r8.y, r8.y, l(0)
        if_nz r0.w
          mov r8.zw, l(0,0,0,0)
          mov r9.x, l(0)
          loop 
            ige r9.y, r8.w, cb0[3].y
            mov r9.x, l(0)
            breakc_nz r9.y
            ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r9.y, r8.w, l(32), t2.xxxx
            ieq r9.y, r0.w, r9.y
            ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r9.z, r8.w, l(44), t2.xxxx
            and r9.z, r9.z, l(2)
            ine r9.z, r9.z, l(0)
            and r9.y, r9.z, r9.y
            if_nz r9.y
              mov r8.z, l(-1)
              mov r9.x, l(-1)
              break 
            endif 
            iadd r5.x, r8.w, l(1)
            mov r8.zw, r5.yyyx
            mov r9.x, r9.y
          endloop 
          and r5.x, r8.z, r9.x
        else 
          mov r5.x, l(0)
        endif 
        or r5.x, r5.x, r8.y
        not r5.x, r5.x
      else 
        mov r5.x, l(-1)
      endif 
    else 
      mov r5.x, l(0)
    endif 
    if_z r5.x
      iadd r5.x, r8.x, l(1)
      mov r8.x, r5.x
      continue 
    endif 
    ld_structured_indexable(structured_buffer, stride=80)(mixed,mixed,mixed,mixed) r10.xyzw, r8.x, l(0), t1.xyzw
    add r11.xy, -r10.xyxx, r10.zwzz
    dp2 r5.x, r11.xyxx, r11.xyxx
    lt r8.y, l(0.000000), r5.x
    add r9.yz, r0.xxyx, -r10.xxyx
    dp2 r8.w, r9.yzyy, r11.xyxx
    div_sat r5.x, r8.w, r5.x
    and r5.x, r5.x, r8.y
    mad r8.yw, r11.xxxy, r5.xxxx, r10.xxxy
    add r8.yw, r0.xxxy, -r8.yyyw
    dp2 r9.y, r8.ywyy, r8.ywyy
    sqrt r9.y, r9.y
    ge r9.z, r9.y, r7.z
    if_nz r9.z
      iadd r9.z, r8.x, l(1)
      mov r8.x, r9.z
      continue 
    endif 
    ld_structured_indexable(structured_buffer, stride=80)(mixed,mixed,mixed,mixed) r10.xyzw, r8.x, l(16), t1.xyzw
    lt r9.z, l(0.000010), r9.y
    div r8.yw, r8.yyyw, r9.yyyy
    mov r11.zw, -r11.yyyy
    dp2 r9.w, r11.xzxx, r11.xwxx
    rsq r9.w, r9.w
    mul r11.xy, r11.yxyy, l(-1.000000, 1.000000, 0.000000, 0.000000)
    mul r11.xy, r9.wwww, r11.xyxx
    movc r6.zw, r9.zzzz, r8.yyyw, r11.xxxy
    add r8.yw, -r10.xxxy, r10.zzzw
    mad r7.xy, r5.xxxx, r8.ywyy, r10.xyxx
    mov r7.z, r9.y
    iadd r8.x, r8.x, l(1)
    mov r7.w, l(-1)
  endloop 
  mov r3.zw, r6.zzzw
  mov r5.zw, r7.xxxy
  mov r0.z, r7.z
  mov r1.x, r7.w
  iadd r2.w, r2.w, l(1)
endloop 
max r0.x, r1.z, l(0.000100)
div r0.x, r0.z, r0.x
add_sat r0.x, -r0.x, l(1.000000)
ld_structured_indexable(structured_buffer, stride=8)(mixed,mixed,mixed,mixed) r0.yz, vThreadID.x, l(0), u2.xxyx
add r0.yz, -r5.zzwz, r0.yyzy
dp2 r0.w, r0.yzyy, r3.zwzz
mad r0.yz, -r3.zzwz, r0.wwww, r0.yyzy
mul r0.w, -r2.z, cb0[20].y
mul r0.w, r1.w, r0.w
mul r0.w, r0.w, l(1.442695)
exp r0.w, r0.w
add r0.w, -r0.w, l(1.000000)
mul r0.yz, r0.wwww, r0.yyzy
mad r5.xy, -r0.yzyy, r0.xxxx, r4.xyxx
mul r0.yz, r2.zzzz, r3.zzwz
mul r0.yz, r0.yyzy, cb0[20].yyyy
mul r0.xy, r0.xxxx, r0.yzyy
mad r5.zw, -r0.xxxy, l(0.000000, 0.000000, 0.020000, 0.020000), r4.zzzw
movc r0.xyzw, r1.xxxx, r5.xyzw, r4.xyzw
mad r0.xy, r0.zwzz, r1.wwww, r0.xyxx
mul r0.xy, r1.wwww, r0.xyxx
mul r0.z, cb0[8].y, cb0[19].y
dp2 r0.w, r0.xyxx, r0.xyxx
sqrt r0.w, r0.w
lt r1.x, r0.z, r0.w
div r0.z, r0.z, r0.w
mul r0.zw, r0.zzzz, r0.xxxy
movc r0.xy, r1.xxxx, r0.zwzz, r0.xyxx
and r0.zw, r0.xxxy, l(0, 0, 0x7f800000, 0x7f800000)
ine r0.zw, r0.zzzw, l(0, 0, 0x7f800000, 0x7f800000)
and r0.z, r0.w, r0.z
and r0.xy, r0.xyxx, r0.zzzz
store_structured u1.xy, vThreadID.x, l(0), r0.xyxx
ret 
// Approximately 336 instruction slots used
