//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer $Globals
// {
//
//   int _StreamHeadCount;              // Offset:    0 Size:     4 [unused]
//   int _StreamRenderingEnabled;       // Offset:    4 Size:     4 [unused]
//   float _SimulationTime;             // Offset:    8 Size:     4 [unused]
//   float _StreamMaximumGap;           // Offset:   12 Size:     4 [unused]
//   float _StreamMaximumLength;        // Offset:   16 Size:     4 [unused]
//   int _ParticleCapacity;             // Offset:   20 Size:     4
//   int _MaximumIngredients;           // Offset:   24 Size:     4 [unused]
//   int _IngredientCount;              // Offset:   28 Size:     4 [unused]
//   int _SpawnCount;                   // Offset:   32 Size:     4 [unused]
//   int _GridWidth;                    // Offset:   36 Size:     4
//   int _GridHeight;                   // Offset:   40 Size:     4
//   int _GridCellCount;                // Offset:   44 Size:     4 [unused]
//   int _BoundaryCount;                // Offset:   48 Size:     4 [unused]
//   int _VesselTriggerCount;           // Offset:   52 Size:     4
//   int _AgitatorCount;                // Offset:   56 Size:     4 [unused]
//   int _TechniqueTargetVessel;        // Offset:   60 Size:     4 [unused]
//   int _TechniqueMask;                // Offset:   64 Size:     4 [unused]
//   int _TechniqueStateMask;           // Offset:   68 Size:     4 [unused]
//   int _TransformTargetVessel;        // Offset:   72 Size:     4 [unused]
//   int _SuspensionTargetVessel;       // Offset:   76 Size:     4 [unused]
//   int _SuspensionEnabled;            // Offset:   80 Size:     4 [unused]
//   int _ReferenceSolverEnabled;       // Offset:   84 Size:     4 [unused]
//   int _ImprovedPhysics;              // Offset:   88 Size:     4 [unused]
//   int _TransferTargetVessel;         // Offset:   92 Size:     4 [unused]
//   float _ReferenceParticleVolume;    // Offset:   96 Size:     4 [unused]
//   float _ReferenceRestDensity;       // Offset:  100 Size:     4 [unused]
//   float _ReferencePressureStiffness; // Offset:  104 Size:     4 [unused]
//   float _ReferenceNearPressureStiffness;// Offset:  108 Size:     4 [unused]
//   float _ReferenceViscosityRate;     // Offset:  112 Size:     4 [unused]
//   float _ReferenceMaximumTensionRatio;// Offset:  116 Size:     4 [unused]
//   float _ReferenceMaximumAcceleration;// Offset:  120 Size:     4 [unused]
//   float _ReferenceMaximumDisplacementRatio;// Offset:  124 Size:     4 [unused]
//   float _DeltaTime;                  // Offset:  128 Size:     4 [unused]
//   float _ParticleRadius;             // Offset:  132 Size:     4
//   float _SmoothingRadius;            // Offset:  136 Size:     4
//   float _RestDensity;                // Offset:  140 Size:     4
//   float _DensityCompliance;          // Offset:  144 Size:     4
//   float _LambdaEpsilon;              // Offset:  148 Size:     4
//   float _ArtificialPressureStrength; // Offset:  152 Size:     4 [unused]
//   float _ArtificialPressureRadiusRatio;// Offset:  156 Size:     4 [unused]
//   float _BoundaryDensityScale;       // Offset:  160 Size:     4
//   float _WallFriction;               // Offset:  164 Size:     4 [unused]
//   float _WallRestitution;            // Offset:  168 Size:     4 [unused]
//   float _SplashTransfer;             // Offset:  172 Size:     4 [unused]
//   float _SplashMinimumImpactSpeed;   // Offset:  176 Size:     4 [unused]
//   float _BottomImpactSpread;         // Offset:  180 Size:     4 [unused]
//   float _VelocityDamping;            // Offset:  184 Size:     4 [unused]
//   float _MaximumSpeed;               // Offset:  188 Size:     4 [unused]
//   float _ClosedVesselDampingRate;    // Offset:  192 Size:     4 [unused]
//   float _ClosedVesselMaximumRelativeSpeed;// Offset:  196 Size:     4 [unused]
//   float _Viscosity;                  // Offset:  200 Size:     4 [unused]
//   float _PassiveMixRate;             // Offset:  204 Size:     4 [unused]
//   float _AgitationMixRate;           // Offset:  208 Size:     4 [unused]
//   float _FullMixRelativeSpeed;       // Offset:  212 Size:     4 [unused]
//   float _MaximumMixPerSubstep;       // Offset:  216 Size:     4 [unused]
//   float _MinimumVisibleAlpha;        // Offset:  220 Size:     4 [unused]
//   float2 _Gravity;                   // Offset:  224 Size:     8 [unused]
//   float2 _GridOrigin;                // Offset:  232 Size:     8
//   float2 _WorldMin;                  // Offset:  240 Size:     8 [unused]
//   float2 _WorldMax;                  // Offset:  248 Size:     8 [unused]
//   float2 _TransformDelta;            // Offset:  256 Size:     8 [unused]
//   int _SwapA;                        // Offset:  264 Size:     4 [unused]
//   int _SwapB;                        // Offset:  268 Size:     4 [unused]
//   float2 _SwapDeltaA;                // Offset:  272 Size:     8 [unused]
//   float2 _SwapDeltaB;                // Offset:  280 Size:     8 [unused]
//   int _BoundaryGroupCount;           // Offset:  288 Size:     4
//   int _ImprovedVesselCount;          // Offset:  292 Size:     4 [unused]
//   float _ImprovedAreaPerMl;          // Offset:  296 Size:     4 [unused]
//   float _ImprovedKernelRatio;        // Offset:  300 Size:     4 [unused]
//   float _ImprovedCompliance;         // Offset:  304 Size:     4 [unused]
//   float _ImprovedCorrectionRatio;    // Offset:  308 Size:     4 [unused]
//   float _ImprovedWallDensity;        // Offset:  312 Size:     4 [unused]
//   float _ImprovedShear;              // Offset:  316 Size:     4 [unused]
//   float _ImprovedTension;            // Offset:  320 Size:     4 [unused]
//   float _ImprovedWetting;            // Offset:  324 Size:     4 [unused]
//
// }
//
// Resource bind info for _Boundaries
// {
//
//   struct BoundarySegment
//   {
//       
//       float2 a;                      // Offset:    0
//       float2 b;                      // Offset:    8
//       float2 velocityA;              // Offset:   16
//       float2 velocityB;              // Offset:   24
//       uint vesselId;                 // Offset:   32
//       uint flags;                    // Offset:   36
//       float2 localA;                 // Offset:   40
//       float2 localB;                 // Offset:   48
//       float2 startPosition;          // Offset:   56
//       float2 endPosition;            // Offset:   64
//       float startAngle;              // Offset:   72
//       float angleDelta;              // Offset:   76
//
//   } $Element;                        // Offset:    0 Size:    80
//
// }
//
// Resource bind info for _VesselTriggers
// {
//
//   struct VesselTrigger
//   {
//       
//       float2 center;                 // Offset:    0
//       float2 axisX;                  // Offset:    8
//       float2 axisY;                  // Offset:   16
//       float2 halfExtents;            // Offset:   24
//       uint vesselId;                 // Offset:   32
//       int priority;                  // Offset:   36
//       uint active;                   // Offset:   40
//       uint flags;                    // Offset:   44
//
//   } $Element;                        // Offset:    0 Size:    48
//
// }
//
// Resource bind info for _BoundaryGroups
// {
//
//   struct BoundaryGroup
//   {
//       
//       float2 minPosition;            // Offset:    0
//       float2 maxPosition;            // Offset:    8
//       float2 sweptMin;               // Offset:   16
//       float2 sweptMax;               // Offset:   24
//       uint first;                    // Offset:   32
//       uint end;                      // Offset:   36
//       uint contourFirst;             // Offset:   40
//       uint contourEnd;               // Offset:   44
//       uint vesselId;                 // Offset:   48
//
//   } $Element;                        // Offset:    0 Size:    52
//
// }
//
// Resource bind info for _Particles
// {
//
//   struct LiquidParticle
//   {
//       
//       float2 position;               // Offset:    0
//       float2 previousPosition;       // Offset:    8
//       float2 velocity;               // Offset:   16
//       float volumeMl;                // Offset:   24
//       float temperatureC;            // Offset:   28
//       uint vesselId;                 // Offset:   32
//       uint techniqueFlags;           // Offset:   36
//       uint stateFlags;               // Offset:   40
//       uint active;                   // Offset:   44
//       uint padding;                  // Offset:   48
//
//   } $Element;                        // Offset:    0 Size:    52
//
// }
//
// Resource bind info for _Lambdas
// {
//
//   float $Element;                    // Offset:    0 Size:     4
//
// }
//
// Resource bind info for _GridHeads
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
// Resource bind info for _GridNext
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
// Resource bind info for _StreamParticles
// {
//
//   struct StreamParticle
//   {
//       
//       uint token;                    // Offset:    0
//       uint previousToken;            // Offset:    4
//       uint streamId;                 // Offset:    8
//       uint sourceId;                 // Offset:   12
//       float delay;                   // Offset:   16
//       float stepDt;                  // Offset:   20
//       float startFraction;           // Offset:   24
//       float birthTime;               // Offset:   28
//       float radius;                  // Offset:   32
//       uint detached;                 // Offset:   36
//       uint pending;                  // Offset:   40
//       uint padding;                  // Offset:   44
//
//   } $Element;                        // Offset:    0 Size:    48
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// _Boundaries                       texture  struct         r/o             t0      1 
// _VesselTriggers                   texture  struct         r/o             t1      1 
// _BoundaryGroups                   texture  struct         r/o             t2      1 
// _Particles                            UAV  struct         r/w             u0      1 
// _Lambdas                              UAV  struct         r/w             u1      1 
// _GridHeads                            UAV  struct         r/w             u2      1 
// _GridNext                             UAV  struct         r/w             u3      1 
// _StreamParticles                      UAV  struct         r/w             u4      1 
// $Globals                          cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[19], immediateIndexed
dcl_resource_structured t0, 80
dcl_resource_structured t1, 48
dcl_resource_structured t2, 52
dcl_uav_structured u0, 52
dcl_uav_structured u1, 4
dcl_uav_structured u2, 4
dcl_uav_structured u3, 4
dcl_uav_structured u4, 48
dcl_input vThreadID.x
dcl_temps 11
dcl_thread_group 64, 1, 1
uge r0.x, vThreadID.x, cb0[1].y
if_nz r0.x
  ret 
endif 
ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r0.xy, vThreadID.x, l(0), u0.xyxx
ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r0.z, vThreadID.x, l(24), u0.xxxx
ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r0.w, vThreadID.x, l(32), u0.xxxx
ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r1.xy, vThreadID.x, l(40), u0.xyxx
ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r1.z, vThreadID.x, l(20), u4.xxxx
ge r1.z, l(0.000001), r1.z
ieq r1.y, r1.y, l(0)
or r1.y, r1.y, r1.z
and r1.x, r1.x, l(4)
ine r1.x, r1.x, l(0)
or r1.x, r1.x, r1.y
if_nz r1.x
  store_structured u1.x, vThreadID.x, l(0), l(0)
  ret 
endif 
max r0.z, r0.z, l(0.010000)
mul r1.x, cb0[8].z, cb0[8].z
lt r1.y, l(0.000000), r1.x
mul r1.z, r1.x, r1.x
mul r1.w, r1.z, r1.z
max r1.w, r1.w, l(0.000000)
mul r1.w, r1.w, l(3.141593)
div r1.w, l(4.000000), r1.w
mul r2.x, r1.w, r1.z
mul r2.x, r1.x, r2.x
and r1.y, r1.y, r2.x
mul r1.y, r0.z, r1.y
add r2.xy, r0.xyxx, -cb0[14].zwzz
div r2.xy, r2.xyxx, cb0[8].zzzz
round_ni r2.xy, r2.xyxx
ftoi r2.xy, r2.xyxx
mul r2.z, cb0[8].y, l(0.050000)
max r2.z, r2.z, l(0.000100)
max r2.w, cb0[8].w, l(0.010000)
mul r1.z, r1.z, cb0[8].z
max r1.z, r1.z, l(0.000000)
mul r1.z, r1.z, l(3.141593)
div r1.z, l(-30.000000), r1.z
mov r3.xy, l(0,0,0,0)
mov r3.zw, cb0[2].yyyz
mov r4.x, r1.y
mov r4.y, l(0)
mov r5.y, l(-1)
loop 
  ilt r4.z, l(1), r5.y
  breakc_nz r4.z
  mov r4.zw, r3.xxxy
  mov r5.zw, r4.xxxy
  mov r5.x, l(-1)
  loop 
    ilt r6.x, l(1), r5.x
    breakc_nz r6.x
    iadd r6.xy, r2.xyxx, r5.xyxx
    ige r6.zw, r6.xxxy, l(0, 0, 0, 0)
    and r6.z, r6.w, r6.z
    ilt r6.w, r6.x, r3.z
    and r6.z, r6.w, r6.z
    ilt r6.w, r6.y, r3.w
    and r6.z, r6.w, r6.z
    if_z r6.z
      iadd r6.z, r5.x, l(1)
      mov r5.x, r6.z
      continue 
    endif 
    imad r6.x, r6.y, r3.z, r6.x
    ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r6.x, r6.x, l(0), u2.xxxx
    mov r6.yz, r4.zzwz
    mov r6.w, r5.z
    mov r7.x, r5.w
    mov r7.y, r6.x
    mov r7.z, l(0)
    loop 
      ige r7.w, r7.y, l(0)
      ilt r8.x, r7.z, cb0[1].y
      and r7.w, r7.w, r8.x
      breakc_z r7.w
      iadd r7.z, r7.z, l(1)
      ine r7.w, r7.y, vThreadID.x
      if_nz r7.w
        ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r8.xy, r7.y, l(0), u0.xyxx
        ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r7.w, r7.y, l(24), u0.xxxx
        ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r8.z, r7.y, l(32), u0.xxxx
        ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r9.xy, r7.y, l(40), u0.xyxx
        ine r8.w, r9.y, l(0)
        and r9.x, r9.x, l(4)
        ieq r9.x, r9.x, l(0)
        and r8.w, r8.w, r9.x
        ieq r8.z, r0.w, r8.z
        and r8.z, r8.z, r8.w
        if_nz r8.z
          add r8.xy, r0.xyxx, -r8.xyxx
          dp2 r8.z, r8.xyxx, r8.xyxx
          lt r8.w, r8.z, r1.x
          if_nz r8.w
            max r7.w, r7.w, l(0.010000)
            mad r8.w, cb0[8].z, cb0[8].z, -r8.z
            mul r9.x, r8.w, r8.w
            mul r9.x, r1.w, r9.x
            mul r8.w, r8.w, r9.x
            mad r6.w, r7.w, r8.w, r6.w
            ge r8.z, l(0.000000), r8.z
            umin r8.w, r7.y, vThreadID.x
            umax r9.x, r7.y, vThreadID.x
            imul null, r9.x, r9.x, l(0xac564b05)
            imad r9.x, r8.w, l(0x2c9277b5), r9.x
            and r9.x, r9.x, l(1023)
            utof r9.x, r9.x
            mul r9.x, r9.x, l(0.006136)
            sincos r9.x, r10.x, r9.x
            ieq r8.w, r8.w, vThreadID.x
            movc r8.w, r8.w, l(1.000000), l(-1.000000)
            mov r10.y, r9.x
            mul r9.xy, r8.wwww, r10.xyxx
            mul r9.xy, r2.zzzz, r9.xyxx
            movc r8.xy, r8.zzzz, r9.xyxx, r8.xyxx
            div r7.w, -r7.w, r2.w
            dp2 r8.z, r8.xyxx, r8.xyxx
            sqrt r8.z, r8.z
            ge r8.w, l(0.000010), r8.z
            ge r9.x, r8.z, cb0[8].z
            or r8.w, r8.w, r9.x
            add r9.x, -r8.z, cb0[8].z
            mul r9.x, r9.x, r9.x
            mul r9.x, r1.z, r9.x
            mul r8.xy, r8.xyxx, r9.xxxx
            div r8.xy, r8.xyxx, r8.zzzz
            movc r8.xy, r8.wwww, l(0,0,0,0), r8.xyxx
            mul r8.zw, r7.wwww, r8.xxxy
            dp2 r8.z, r8.zwzz, r8.zwzz
            add r7.x, r7.x, r8.z
            mad r6.yz, -r7.wwww, r8.xxyx, r6.yyzy
          endif 
        endif 
      endif 
      ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r7.y, r7.y, l(0), u3.xxxx
    endloop 
    mov r4.zw, r6.yyyz
    mov r5.z, r6.w
    mov r5.w, r7.x
    iadd r5.x, r5.x, l(1)
  endloop 
  mov r3.xy, r4.zwzz
  mov r4.xy, r5.zwzz
  iadd r5.y, r5.y, l(1)
endloop 
ine r1.y, r0.w, l(0)
lt r2.x, l(0.000000), cb0[10].x
and r1.y, r1.y, r2.x
if_nz r1.y
  add r2.xy, r0.xyxx, -cb0[8].zzzz
  add r3.zw, r0.xxxy, cb0[8].zzzz
  mov r5.y, l(0)
  mov r4.zw, l(0,0,0,0)
  mov r1.y, cb0[8].z
  mov r2.z, l(0)
  mov r5.z, l(0)
  loop 
    ige r5.w, r5.z, cb0[18].x
    breakc_nz r5.w
    ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r6.xyzw, r5.z, l(0), t2.xyzw
    ge r6.xy, r3.zwzz, r6.xyxx
    and r5.w, r6.y, r6.x
    ge r6.xy, r6.zwzz, r2.xyxx
    and r6.x, r6.y, r6.x
    and r5.w, r5.w, r6.x
    if_z r5.w
      iadd r5.w, r5.z, l(1)
      mov r5.z, r5.w
      continue 
    endif 
    ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r6.xy, r5.z, l(32), t2.xyxx
    mov r6.zw, r4.zzzw
    mov r5.w, r1.y
    mov r7.x, r2.z
    mov r7.y, r6.x
    loop 
      uge r7.z, r7.y, r6.y
      breakc_nz r7.z
      ld_structured_indexable(structured_buffer, stride=80)(mixed,mixed,mixed,mixed) r7.zw, r7.y, l(32), t0.xxxy
      and r8.x, r7.w, l(16)
      if_z r8.x
        ine r7.z, r0.w, r7.z
        if_nz r7.z
          and r7.z, r7.w, l(2)
          ine r7.z, r7.z, l(0)
          if_nz r0.w
            mov r8.xy, l(0,0,0,0)
            mov r7.w, l(0)
            loop 
              ige r8.z, r8.y, cb0[3].y
              mov r7.w, l(0)
              breakc_nz r8.z
              ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r8.z, r8.y, l(32), t1.xxxx
              ieq r8.z, r0.w, r8.z
              ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r8.w, r8.y, l(44), t1.xxxx
              and r8.w, r8.w, l(2)
              ine r8.w, r8.w, l(0)
              and r8.z, r8.w, r8.z
              if_nz r8.z
                mov r8.x, l(-1)
                mov r7.w, l(-1)
                break 
              endif 
              iadd r5.x, r8.y, l(1)
              mov r8.xy, r5.yxyy
              mov r7.w, r8.z
            endloop 
            and r5.x, r8.x, r7.w
          else 
            mov r5.x, l(0)
          endif 
          or r5.x, r5.x, r7.z
          not r5.x, r5.x
        else 
          mov r5.x, l(-1)
        endif 
      else 
        mov r5.x, l(0)
      endif 
      if_z r5.x
        iadd r5.x, r7.y, l(1)
        mov r7.y, r5.x
        continue 
      endif 
      ld_structured_indexable(structured_buffer, stride=80)(mixed,mixed,mixed,mixed) r9.xyzw, r7.y, l(0), t0.xyzw
      add r8.yz, -r9.xxyx, r9.zzwz
      dp2 r5.x, r8.yzyy, r8.yzyy
      lt r7.z, l(0.000000), r5.x
      add r9.zw, r0.xxxy, -r9.xxxy
      dp2 r8.w, r9.zwzz, r8.yzyy
      div_sat r5.x, r8.w, r5.x
      and r5.x, r5.x, r7.z
      mad r8.yz, r8.yyzy, r5.xxxx, r9.xxyx
      add r9.xy, r0.xyxx, -r8.yzyy
      dp2 r5.x, r9.xyxx, r9.xyxx
      sqrt r5.x, r5.x
      ge r7.z, r5.x, r5.w
      if_nz r7.z
        iadd r7.z, r7.y, l(1)
        mov r7.y, r7.z
        continue 
      endif 
      mov r6.zw, r8.yyyz
      mov r5.w, r5.x
      iadd r7.y, r7.y, l(1)
      mov r7.x, l(-1)
    endloop 
    mov r4.zw, r6.zzzw
    mov r1.y, r5.w
    mov r2.z, r7.x
    iadd r5.z, r5.z, l(1)
  endloop 
  if_nz r2.z
    mul r0.z, r0.z, cb0[10].x
    add r0.xy, r0.xyxx, -r4.zwzz
    mul r0.w, r1.y, r1.y
    lt r1.x, r0.w, r1.x
    mad r0.w, cb0[8].z, cb0[8].z, -r0.w
    mul r1.y, r0.w, r0.w
    mul r1.y, r1.w, r1.y
    mul r0.w, r0.w, r1.y
    and r0.w, r0.w, r1.x
    mad r4.x, r0.z, r0.w, r4.x
    div r0.z, r0.z, r2.w
    dp2 r0.w, r0.xyxx, r0.xyxx
    sqrt r0.w, r0.w
    ge r1.x, l(0.000010), r0.w
    ge r1.y, r0.w, cb0[8].z
    or r1.x, r1.y, r1.x
    add r1.y, -r0.w, cb0[8].z
    mul r1.y, r1.y, r1.y
    mul r1.y, r1.z, r1.y
    mul r0.xy, r0.xyxx, r1.yyyy
    div r0.xy, r0.xyxx, r0.wwww
    movc r0.xy, r1.xxxx, l(0,0,0,0), r0.xyxx
    mad r3.xy, r0.zzzz, r0.xyxx, r3.xyxx
  endif 
endif 
dp2 r0.x, r3.xyxx, r3.xyxx
add r0.x, r0.x, r4.y
div r0.y, r4.x, r2.w
add r0.y, r0.y, l(-1.000000)
ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r0.z, vThreadID.x, l(20), u4.xxxx
mul r0.z, r0.z, r0.z
max r0.yz, r0.yyzy, l(0.000000, 0.000000, 0.000000, 0.000000)
div r0.z, cb0[9].x, r0.z
add r0.x, r0.x, cb0[9].y
add r0.x, r0.z, r0.x
div r0.x, -r0.y, r0.x
store_structured u1.x, vThreadID.x, l(0), r0.x
ret 
// Approximately 295 instruction slots used
