//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer $Globals
// {
//
//   int _StreamHeadCount;              // Offset:    0 Size:     4 [unused]
//   int _StreamRenderingEnabled;       // Offset:    4 Size:     4 [unused]
//   float _SimulationTime;             // Offset:    8 Size:     4 [unused]
//   float _StreamMaximumGap;           // Offset:   12 Size:     4 [unused]
//   float _StreamMaximumLength;        // Offset:   16 Size:     4 [unused]
//   int _ParticleCapacity;             // Offset:   20 Size:     4
//   int _MaximumIngredients;           // Offset:   24 Size:     4 [unused]
//   int _IngredientCount;              // Offset:   28 Size:     4 [unused]
//   int _SpawnCount;                   // Offset:   32 Size:     4 [unused]
//   int _GridWidth;                    // Offset:   36 Size:     4
//   int _GridHeight;                   // Offset:   40 Size:     4
//   int _GridCellCount;                // Offset:   44 Size:     4 [unused]
//   int _BoundaryCount;                // Offset:   48 Size:     4 [unused]
//   int _VesselTriggerCount;           // Offset:   52 Size:     4
//   int _AgitatorCount;                // Offset:   56 Size:     4 [unused]
//   int _TechniqueTargetVessel;        // Offset:   60 Size:     4 [unused]
//   int _TechniqueMask;                // Offset:   64 Size:     4 [unused]
//   int _TechniqueStateMask;           // Offset:   68 Size:     4 [unused]
//   int _TransformTargetVessel;        // Offset:   72 Size:     4 [unused]
//   int _SuspensionTargetVessel;       // Offset:   76 Size:     4 [unused]
//   int _SuspensionEnabled;            // Offset:   80 Size:     4 [unused]
//   int _ReferenceSolverEnabled;       // Offset:   84 Size:     4 [unused]
//   int _ImprovedPhysics;              // Offset:   88 Size:     4 [unused]
//   int _TransferTargetVessel;         // Offset:   92 Size:     4 [unused]
//   float _ReferenceParticleVolume;    // Offset:   96 Size:     4
//   float _ReferenceRestDensity;       // Offset:  100 Size:     4 [unused]
//   float _ReferencePressureStiffness; // Offset:  104 Size:     4 [unused]
//   float _ReferenceNearPressureStiffness;// Offset:  108 Size:     4 [unused]
//   float _ReferenceViscosityRate;     // Offset:  112 Size:     4 [unused]
//   float _ReferenceMaximumTensionRatio;// Offset:  116 Size:     4 [unused]
//   float _ReferenceMaximumAcceleration;// Offset:  120 Size:     4 [unused]
//   float _ReferenceMaximumDisplacementRatio;// Offset:  124 Size:     4 [unused]
//   float _DeltaTime;                  // Offset:  128 Size:     4 [unused]
//   float _ParticleRadius;             // Offset:  132 Size:     4
//   float _SmoothingRadius;            // Offset:  136 Size:     4
//   float _RestDensity;                // Offset:  140 Size:     4 [unused]
//   float _DensityCompliance;          // Offset:  144 Size:     4 [unused]
//   float _LambdaEpsilon;              // Offset:  148 Size:     4 [unused]
//   float _ArtificialPressureStrength; // Offset:  152 Size:     4 [unused]
//   float _ArtificialPressureRadiusRatio;// Offset:  156 Size:     4 [unused]
//   float _BoundaryDensityScale;       // Offset:  160 Size:     4 [unused]
//   float _WallFriction;               // Offset:  164 Size:     4 [unused]
//   float _WallRestitution;            // Offset:  168 Size:     4 [unused]
//   float _SplashTransfer;             // Offset:  172 Size:     4 [unused]
//   float _SplashMinimumImpactSpeed;   // Offset:  176 Size:     4 [unused]
//   float _BottomImpactSpread;         // Offset:  180 Size:     4 [unused]
//   float _VelocityDamping;            // Offset:  184 Size:     4 [unused]
//   float _MaximumSpeed;               // Offset:  188 Size:     4 [unused]
//   float _ClosedVesselDampingRate;    // Offset:  192 Size:     4 [unused]
//   float _ClosedVesselMaximumRelativeSpeed;// Offset:  196 Size:     4 [unused]
//   float _Viscosity;                  // Offset:  200 Size:     4 [unused]
//   float _PassiveMixRate;             // Offset:  204 Size:     4 [unused]
//   float _AgitationMixRate;           // Offset:  208 Size:     4 [unused]
//   float _FullMixRelativeSpeed;       // Offset:  212 Size:     4 [unused]
//   float _MaximumMixPerSubstep;       // Offset:  216 Size:     4 [unused]
//   float _MinimumVisibleAlpha;        // Offset:  220 Size:     4 [unused]
//   float2 _Gravity;                   // Offset:  224 Size:     8 [unused]
//   float2 _GridOrigin;                // Offset:  232 Size:     8
//   float2 _WorldMin;                  // Offset:  240 Size:     8 [unused]
//   float2 _WorldMax;                  // Offset:  248 Size:     8 [unused]
//   float2 _TransformDelta;            // Offset:  256 Size:     8 [unused]
//   int _SwapA;                        // Offset:  264 Size:     4 [unused]
//   int _SwapB;                        // Offset:  268 Size:     4 [unused]
//   float2 _SwapDeltaA;                // Offset:  272 Size:     8 [unused]
//   float2 _SwapDeltaB;                // Offset:  280 Size:     8 [unused]
//   int _BoundaryGroupCount;           // Offset:  288 Size:     4
//   int _ImprovedVesselCount;          // Offset:  292 Size:     4
//   float _ImprovedAreaPerMl;          // Offset:  296 Size:     4
//   float _ImprovedKernelRatio;        // Offset:  300 Size:     4
//   float _ImprovedCompliance;         // Offset:  304 Size:     4 [unused]
//   float _ImprovedCorrectionRatio;    // Offset:  308 Size:     4
//   float _ImprovedWallDensity;        // Offset:  312 Size:     4
//   float _ImprovedShear;              // Offset:  316 Size:     4 [unused]
//   float _ImprovedTension;            // Offset:  320 Size:     4 [unused]
//   float _ImprovedWetting;            // Offset:  324 Size:     4 [unused]
//
// }
//
// Resource bind info for _Boundaries
// {
//
//   struct BoundarySegment
//   {
//       
//       float2 a;                      // Offset:    0
//       float2 b;                      // Offset:    8
//       float2 velocityA;              // Offset:   16
//       float2 velocityB;              // Offset:   24
//       uint vesselId;                 // Offset:   32
//       uint flags;                    // Offset:   36
//       float2 localA;                 // Offset:   40
//       float2 localB;                 // Offset:   48
//       float2 startPosition;          // Offset:   56
//       float2 endPosition;            // Offset:   64
//       float startAngle;              // Offset:   72
//       float angleDelta;              // Offset:   76
//
//   } $Element;                        // Offset:    0 Size:    80
//
// }
//
// Resource bind info for _VesselTriggers
// {
//
//   struct VesselTrigger
//   {
//       
//       float2 center;                 // Offset:    0
//       float2 axisX;                  // Offset:    8
//       float2 axisY;                  // Offset:   16
//       float2 halfExtents;            // Offset:   24
//       uint vesselId;                 // Offset:   32
//       int priority;                  // Offset:   36
//       uint active;                   // Offset:   40
//       uint flags;                    // Offset:   44
//
//   } $Element;                        // Offset:    0 Size:    48
//
// }
//
// Resource bind info for _BoundaryGroups
// {
//
//   struct BoundaryGroup
//   {
//       
//       float2 minPosition;            // Offset:    0
//       float2 maxPosition;            // Offset:    8
//       float2 sweptMin;               // Offset:   16
//       float2 sweptMax;               // Offset:   24
//       uint first;                    // Offset:   32
//       uint end;                      // Offset:   36
//       uint contourFirst;             // Offset:   40
//       uint contourEnd;               // Offset:   44
//       uint vesselId;                 // Offset:   48
//
//   } $Element;                        // Offset:    0 Size:    52
//
// }
//
// Resource bind info for _ImprovedVessels
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
// Resource bind info for _Particles
// {
//
//   struct LiquidParticle
//   {
//       
//       float2 position;               // Offset:    0
//       float2 previousPosition;       // Offset:    8
//       float2 velocity;               // Offset:   16
//       float volumeMl;                // Offset:   24
//       float temperatureC;            // Offset:   28
//       uint vesselId;                 // Offset:   32
//       uint techniqueFlags;           // Offset:   36
//       uint stateFlags;               // Offset:   40
//       uint active;                   // Offset:   44
//       uint padding;                  // Offset:   48
//
//   } $Element;                        // Offset:    0 Size:    52
//
// }
//
// Resource bind info for _PositionDeltas
// {
//
//   float2 $Element;                   // Offset:    0 Size:     8
//
// }
//
// Resource bind info for _Lambdas
// {
//
//   float $Element;                    // Offset:    0 Size:     4
//
// }
//
// Resource bind info for _GridHeads
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
// Resource bind info for _GridNext
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
// Resource bind info for _StreamParticles
// {
//
//   struct StreamParticle
//   {
//       
//       uint token;                    // Offset:    0
//       uint previousToken;            // Offset:    4
//       uint streamId;                 // Offset:    8
//       uint sourceId;                 // Offset:   12
//       float delay;                   // Offset:   16
//       float stepDt;                  // Offset:   20
//       float startFraction;           // Offset:   24
//       float birthTime;               // Offset:   28
//       float radius;                  // Offset:   32
//       uint detached;                 // Offset:   36
//       uint pending;                  // Offset:   40
//       uint padding;                  // Offset:   44
//
//   } $Element;                        // Offset:    0 Size:    48
//
// }
//
// Resource bind info for _ImprovedDiagnostics
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// _Boundaries                       texture  struct         r/o             t0      1 
// _VesselTriggers                   texture  struct         r/o             t1      1 
// _BoundaryGroups                   texture  struct         r/o             t2      1 
// _ImprovedVessels                  texture  struct         r/o             t3      1 
// _Particles                            UAV  struct         r/w             u0      1 
// _PositionDeltas                       UAV  struct         r/w             u1      1 
// _Lambdas                              UAV  struct         r/w             u2      1 
// _GridHeads                            UAV  struct         r/w             u3      1 
// _GridNext                             UAV  struct         r/w             u4      1 
// _StreamParticles                      UAV  struct         r/w             u5      1 
// _ImprovedDiagnostics                  UAV  struct         r/w             u6      1 
// $Globals                          cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[20], immediateIndexed
dcl_resource_structured t0, 80
dcl_resource_structured t1, 48
dcl_resource_structured t2, 52
dcl_resource_structured t3, 16
dcl_uav_structured u0, 52
dcl_uav_structured u1, 8
dcl_uav_structured u2, 4
dcl_uav_structured u3, 4
dcl_uav_structured u4, 4
dcl_uav_structured u5, 48
dcl_uav_structured u6, 16
dcl_input vThreadID.x
dcl_temps 10
dcl_thread_group 64, 1, 1
uge r0.x, vThreadID.x, cb0[1].y
if_nz r0.x
  ret 
endif 
ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r0.xy, vThreadID.x, l(0), u0.xyxx
ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r0.z, vThreadID.x, l(32), u0.xxxx
ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r1.xy, vThreadID.x, l(40), u0.xyxx
ine r0.w, r1.y, l(0)
and r1.x, r1.x, l(4)
ieq r1.x, r1.x, l(0)
and r0.w, r0.w, r1.x
ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r1.x, vThreadID.x, l(20), u5.xxxx
lt r1.x, l(0.000001), r1.x
and r0.w, r0.w, r1.x
if_z r0.w
  store_structured u1.xy, vThreadID.x, l(0), l(0,0,0,0)
  ret 
endif 
mov r1.yz, l(0,0,0,0)
mov r2.xyz, l(0,0,0,0)
mov r0.w, l(0)
loop 
  ige r1.w, r2.z, cb0[18].y
  mov r0.w, l(0)
  breakc_nz r1.w
  ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r1.w, r2.z, l(0), t3.xxxx
  ftou r1.w, r1.w
  ieq r1.w, r0.z, r1.w
  if_nz r1.w
    ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r2.xy, r2.z, l(4), t3.xyxx
    mov r0.w, l(-1)
    break 
  endif 
  iadd r1.x, r2.z, l(1)
  mov r2.xyz, r1.yzxy
  mov r0.w, r1.w
endloop 
mul r1.x, cb0[6].x, cb0[18].z
sqrt r1.x, r1.x
mul r1.x, r1.x, cb0[18].w
mul r1.yz, cb0[8].yyyy, l(0.000000, 2.100000, 0.050000, 0.000000)
max r1.x, r1.y, r1.x
min r1.y, r1.x, cb0[8].z
mov r1.x, cb0[18].z
movc r1.xy, r0.wwww, r2.xyxx, r1.xyxx
ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r0.w, vThreadID.x, l(20), u5.xxxx
add r2.xy, r0.xyxx, -cb0[14].zwzz
div r2.xy, r2.xyxx, cb0[8].zzzz
round_ni r2.xy, r2.xyxx
ftoi r2.xy, r2.xyxx
max r1.z, r1.z, l(0.000100)
max r1.w, r0.w, l(0.000001)
mul r2.z, r1.y, r1.y
mul r2.w, r2.z, r2.z
mul r2.w, r2.w, l(3.141593)
div r2.w, l(-24.000000), r2.w
mov r3.xy, l(0,0,0,0)
mov r3.zw, cb0[2].yyyz
mov r4.y, l(-1)
loop 
  ilt r4.z, l(1), r4.y
  breakc_nz r4.z
  mov r4.zw, r3.xxxy
  mov r4.x, l(-1)
  loop 
    ilt r5.x, l(1), r4.x
    breakc_nz r5.x
    iadd r5.xy, r2.xyxx, r4.xyxx
    ige r5.zw, r5.xxxy, l(0, 0, 0, 0)
    and r5.z, r5.w, r5.z
    ilt r5.w, r5.x, r3.z
    and r5.z, r5.w, r5.z
    ilt r5.w, r5.y, r3.w
    and r5.z, r5.w, r5.z
    if_z r5.z
      iadd r5.z, r4.x, l(1)
      mov r4.x, r5.z
      continue 
    endif 
    imad r5.x, r5.y, r3.z, r5.x
    ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r5.x, r5.x, l(0), u3.xxxx
    ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r5.y, vThreadID.x, l(0), u2.xxxx
    mov r5.zw, r4.zzzw
    mov r6.x, r5.x
    mov r6.y, l(0)
    loop 
      ige r6.z, r6.x, l(0)
      ilt r6.w, r6.y, cb0[1].y
      and r6.z, r6.w, r6.z
      breakc_z r6.z
      iadd r6.y, r6.y, l(1)
      ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r6.zw, r6.x, l(0), u0.xxxy
      ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r7.x, r6.x, l(24), u0.xxxx
      ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r7.y, r6.x, l(32), u0.xxxx
      ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r7.zw, r6.x, l(40), u0.xxxy
      ine r8.x, r6.x, vThreadID.x
      ine r7.w, r7.w, l(0)
      and r7.z, r7.z, l(4)
      ieq r7.z, r7.z, l(0)
      and r7.z, r7.z, r7.w
      ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r7.w, r6.x, l(20), u5.xxxx
      lt r8.y, l(0.000001), r7.w
      and r7.z, r7.z, r8.y
      and r7.z, r7.z, r8.x
      ieq r7.y, r0.z, r7.y
      and r7.y, r7.y, r7.z
      if_nz r7.y
        add r6.zw, r0.xxxy, -r6.zzzw
        dp2 r7.y, r6.zwzz, r6.zwzz
        ge r7.y, l(0.000000), r7.y
        umin r7.z, r6.x, vThreadID.x
        umax r8.x, r6.x, vThreadID.x
        imul null, r8.x, r8.x, l(0xac564b05)
        imad r8.x, r7.z, l(0x2c9277b5), r8.x
        and r8.x, r8.x, l(1023)
        utof r8.x, r8.x
        mul r8.x, r8.x, l(0.006136)
        sincos r8.x, r9.x, r8.x
        ieq r7.z, r7.z, vThreadID.x
        movc r7.z, r7.z, l(1.000000), l(-1.000000)
        mov r9.y, r8.x
        mul r8.xy, r7.zzzz, r9.xyxx
        mul r8.xy, r1.zzzz, r8.xyxx
        movc r6.zw, r7.yyyy, r8.xxxy, r6.zzzw
        min r7.y, r0.w, r7.w
        div r7.y, r7.y, r1.w
        ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r7.z, r6.x, l(0), u2.xxxx
        add r7.z, r5.y, r7.z
        max r7.x, r7.x, l(0.000000)
        mul r7.x, r7.x, r7.z
        mul r7.x, r1.x, r7.x
        dp2 r7.z, r6.zwzz, r6.zwzz
        div r7.z, r7.z, r2.z
        add r7.z, -r7.z, l(1.000000)
        max r7.z, r7.z, l(0.000000)
        mul r7.z, r7.z, r7.z
        mul r7.z, r2.w, r7.z
        mul r6.zw, r6.zzzw, r7.zzzz
        mul r6.zw, r6.zzzw, r7.xxxx
        mad r5.zw, r6.zzzw, r7.yyyy, r5.zzzw
      endif 
      ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r6.x, r6.x, l(0), u4.xxxx
    endloop 
    mov r4.zw, r5.zzzw
    iadd r4.x, r4.x, l(1)
  endloop 
  mov r3.xy, r4.zwzz
  iadd r4.y, r4.y, l(1)
endloop 
add r1.xz, r0.xxyx, -r1.yyyy
add r2.xy, r0.xyxx, r1.yyyy
mov r4.y, l(0)
mov r2.zw, l(0,0,0,0)
mov r0.w, r1.y
mov r1.w, l(0)
mov r3.z, l(0)
loop 
  ige r3.w, r3.z, cb0[18].x
  breakc_nz r3.w
  ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r5.xyzw, r3.z, l(0), t2.xyzw
  ge r4.zw, r2.xxxy, r5.xxxy
  and r3.w, r4.w, r4.z
  ge r4.zw, r5.zzzw, r1.xxxz
  and r4.z, r4.w, r4.z
  and r3.w, r3.w, r4.z
  if_z r3.w
    iadd r3.w, r3.z, l(1)
    mov r3.z, r3.w
    continue 
  endif 
  ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r4.zw, r3.z, l(32), t2.xxxy
  mov r5.xy, r2.zwzz
  mov r3.w, r0.w
  mov r5.z, r1.w
  mov r5.w, r4.z
  loop 
    uge r6.x, r5.w, r4.w
    breakc_nz r6.x
    ld_structured_indexable(structured_buffer, stride=80)(mixed,mixed,mixed,mixed) r6.xy, r5.w, l(32), t0.xyxx
    and r6.z, r6.y, l(16)
    if_z r6.z
      ine r6.x, r0.z, r6.x
      if_nz r6.x
        and r6.x, r6.y, l(2)
        ine r6.x, r6.x, l(0)
        if_nz r0.z
          mov r6.yzw, l(0,0,0,0)
          loop 
            ige r7.x, r6.z, cb0[3].y
            mov r6.w, l(0)
            breakc_nz r7.x
            ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r7.x, r6.z, l(32), t1.xxxx
            ieq r7.x, r0.z, r7.x
            ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r7.y, r6.z, l(44), t1.xxxx
            and r7.y, r7.y, l(2)
            ine r7.y, r7.y, l(0)
            and r7.x, r7.y, r7.x
            if_nz r7.x
              mov r6.yw, l(0,-1,0,-1)
              break 
            endif 
            iadd r4.x, r6.z, l(1)
            mov r6.yz, r4.yyxy
            mov r6.w, r7.x
          endloop 
          and r4.x, r6.y, r6.w
        else 
          mov r4.x, l(0)
        endif 
        or r4.x, r4.x, r6.x
        not r4.x, r4.x
      else 
        mov r4.x, l(-1)
      endif 
    else 
      mov r4.x, l(0)
    endif 
    if_z r4.x
      iadd r4.x, r5.w, l(1)
      mov r5.w, r4.x
      continue 
    endif 
    ld_structured_indexable(structured_buffer, stride=80)(mixed,mixed,mixed,mixed) r7.xyzw, r5.w, l(0), t0.xyzw
    add r8.xy, -r7.xyxx, r7.zwzz
    dp2 r4.x, r8.xyxx, r8.xyxx
    lt r6.x, l(0.000000), r4.x
    add r7.zw, r0.xxxy, -r7.xxxy
    dp2 r6.z, r7.zwzz, r8.xyxx
    div_sat r4.x, r6.z, r4.x
    and r4.x, r4.x, r6.x
    mad r6.xz, r8.xxyx, r4.xxxx, r7.xxyx
    add r6.xz, r0.xxyx, -r6.xxzx
    dp2 r4.x, r6.xzxx, r6.xzxx
    sqrt r4.x, r4.x
    ge r7.x, r4.x, r3.w
    if_nz r7.x
      iadd r7.x, r5.w, l(1)
      mov r5.w, r7.x
      continue 
    endif 
    lt r7.x, l(0.000010), r4.x
    div r6.xz, r6.xxzx, r4.xxxx
    mov r8.zw, -r8.yyyy
    dp2 r7.y, r8.xzxx, r8.xwxx
    rsq r7.y, r7.y
    mul r7.zw, r8.yyyx, l(0.000000, 0.000000, -1.000000, 1.000000)
    mul r7.yz, r7.yyyy, r7.zzwz
    movc r5.xy, r7.xxxx, r6.xzxx, r7.yzyy
    mov r3.w, r4.x
    iadd r5.w, r5.w, l(1)
    mov r5.z, l(-1)
  endloop 
  mov r2.zw, r5.xxxy
  mov r0.w, r3.w
  mov r1.w, r5.z
  iadd r3.z, r3.z, l(1)
endloop 
if_nz r1.w
  div r0.x, r0.w, r1.y
  mad r0.x, -r0.x, r0.x, l(1.000000)
  max r0.x, r0.x, l(0.000000)
  log r0.x, r0.x
  mul r0.x, r0.x, l(3.500000)
  exp r0.x, r0.x
  mul r0.x, r0.x, l(1.164105)
  div r0.x, r0.x, r1.y
  mul r0.xy, r0.xxxx, -r2.zwzz
  mul r0.xy, r0.xyxx, cb0[19].zzzz
else 
  mov r0.xy, l(0,0,0,0)
endif 
ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r0.z, vThreadID.x, l(0), u2.xxxx
mad r0.xy, r0.zzzz, r0.xyxx, r3.xyxx
mul r0.z, cb0[8].y, cb0[19].y
dp2 r0.w, r0.xyxx, r0.xyxx
sqrt r0.w, r0.w
lt r1.x, r0.z, r0.w
and r1.y, r1.x, l(0x3f800000)
store_structured u6.x, vThreadID.x, l(8), r1.y
div r0.z, r0.z, r0.w
mul r0.zw, r0.zzzz, r0.xxxy
movc r0.xy, r1.xxxx, r0.zwzz, r0.xyxx
and r0.zw, r0.xxxy, l(0, 0, 0x7f800000, 0x7f800000)
ine r0.zw, r0.zzzw, l(0, 0, 0x7f800000, 0x7f800000)
and r0.z, r0.w, r0.z
and r0.xy, r0.xyxx, r0.zzzz
store_structured u1.xy, vThreadID.x, l(0), r0.xyxx
ret 
// Approximately 288 instruction slots used
