//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer $Globals
// {
//
//   int _StreamHeadCount;              // Offset:    0 Size:     4 [unused]
//   int _StreamRenderingEnabled;       // Offset:    4 Size:     4 [unused]
//   float _SimulationTime;             // Offset:    8 Size:     4 [unused]
//   float _StreamMaximumGap;           // Offset:   12 Size:     4 [unused]
//   float _StreamMaximumLength;        // Offset:   16 Size:     4 [unused]
//   int _ParticleCapacity;             // Offset:   20 Size:     4
//   int _MaximumIngredients;           // Offset:   24 Size:     4 [unused]
//   int _IngredientCount;              // Offset:   28 Size:     4 [unused]
//   int _SpawnCount;                   // Offset:   32 Size:     4 [unused]
//   int _GridWidth;                    // Offset:   36 Size:     4
//   int _GridHeight;                   // Offset:   40 Size:     4
//   int _GridCellCount;                // Offset:   44 Size:     4 [unused]
//   int _BoundaryCount;                // Offset:   48 Size:     4 [unused]
//   int _VesselTriggerCount;           // Offset:   52 Size:     4
//   int _AgitatorCount;                // Offset:   56 Size:     4 [unused]
//   int _TechniqueTargetVessel;        // Offset:   60 Size:     4 [unused]
//   int _TechniqueMask;                // Offset:   64 Size:     4 [unused]
//   int _TechniqueStateMask;           // Offset:   68 Size:     4 [unused]
//   int _TransformTargetVessel;        // Offset:   72 Size:     4 [unused]
//   int _SuspensionTargetVessel;       // Offset:   76 Size:     4 [unused]
//   int _SuspensionEnabled;            // Offset:   80 Size:     4 [unused]
//   int _ReferenceSolverEnabled;       // Offset:   84 Size:     4 [unused]
//   int _ImprovedPhysics;              // Offset:   88 Size:     4 [unused]
//   int _TransferTargetVessel;         // Offset:   92 Size:     4 [unused]
//   float _ReferenceParticleVolume;    // Offset:   96 Size:     4
//   float _ReferenceRestDensity;       // Offset:  100 Size:     4 [unused]
//   float _ReferencePressureStiffness; // Offset:  104 Size:     4 [unused]
//   float _ReferenceNearPressureStiffness;// Offset:  108 Size:     4 [unused]
//   float _ReferenceViscosityRate;     // Offset:  112 Size:     4 [unused]
//   float _ReferenceMaximumTensionRatio;// Offset:  116 Size:     4 [unused]
//   float _ReferenceMaximumAcceleration;// Offset:  120 Size:     4 [unused]
//   float _ReferenceMaximumDisplacementRatio;// Offset:  124 Size:     4 [unused]
//   float _DeltaTime;                  // Offset:  128 Size:     4 [unused]
//   float _ParticleRadius;             // Offset:  132 Size:     4
//   float _SmoothingRadius;            // Offset:  136 Size:     4
//   float _RestDensity;                // Offset:  140 Size:     4 [unused]
//   float _DensityCompliance;          // Offset:  144 Size:     4 [unused]
//   float _LambdaEpsilon;              // Offset:  148 Size:     4 [unused]
//   float _ArtificialPressureStrength; // Offset:  152 Size:     4 [unused]
//   float _ArtificialPressureRadiusRatio;// Offset:  156 Size:     4 [unused]
//   float _BoundaryDensityScale;       // Offset:  160 Size:     4 [unused]
//   float _WallFriction;               // Offset:  164 Size:     4 [unused]
//   float _WallRestitution;            // Offset:  168 Size:     4 [unused]
//   float _SplashTransfer;             // Offset:  172 Size:     4 [unused]
//   float _SplashMinimumImpactSpeed;   // Offset:  176 Size:     4 [unused]
//   float _BottomImpactSpread;         // Offset:  180 Size:     4 [unused]
//   float _VelocityDamping;            // Offset:  184 Size:     4 [unused]
//   float _MaximumSpeed;               // Offset:  188 Size:     4 [unused]
//   float _ClosedVesselDampingRate;    // Offset:  192 Size:     4 [unused]
//   float _ClosedVesselMaximumRelativeSpeed;// Offset:  196 Size:     4 [unused]
//   float _Viscosity;                  // Offset:  200 Size:     4 [unused]
//   float _PassiveMixRate;             // Offset:  204 Size:     4 [unused]
//   float _AgitationMixRate;           // Offset:  208 Size:     4 [unused]
//   float _FullMixRelativeSpeed;       // Offset:  212 Size:     4 [unused]
//   float _MaximumMixPerSubstep;       // Offset:  216 Size:     4 [unused]
//   float _MinimumVisibleAlpha;        // Offset:  220 Size:     4 [unused]
//   float2 _Gravity;                   // Offset:  224 Size:     8 [unused]
//   float2 _GridOrigin;                // Offset:  232 Size:     8
//   float2 _WorldMin;                  // Offset:  240 Size:     8 [unused]
//   float2 _WorldMax;                  // Offset:  248 Size:     8 [unused]
//   float2 _TransformDelta;            // Offset:  256 Size:     8 [unused]
//   int _SwapA;                        // Offset:  264 Size:     4 [unused]
//   int _SwapB;                        // Offset:  268 Size:     4 [unused]
//   float2 _SwapDeltaA;                // Offset:  272 Size:     8 [unused]
//   float2 _SwapDeltaB;                // Offset:  280 Size:     8 [unused]
//   int _BoundaryGroupCount;           // Offset:  288 Size:     4
//   int _ImprovedVesselCount;          // Offset:  292 Size:     4
//   float _ImprovedAreaPerMl;          // Offset:  296 Size:     4
//   float _ImprovedKernelRatio;        // Offset:  300 Size:     4
//   float _ImprovedCompliance;         // Offset:  304 Size:     4
//   float _ImprovedCorrectionRatio;    // Offset:  308 Size:     4 [unused]
//   float _ImprovedWallDensity;        // Offset:  312 Size:     4
//   float _ImprovedShear;              // Offset:  316 Size:     4 [unused]
//   float _ImprovedTension;            // Offset:  320 Size:     4 [unused]
//   float _ImprovedWetting;            // Offset:  324 Size:     4 [unused]
//
// }
//
// Resource bind info for _Boundaries
// {
//
//   struct BoundarySegment
//   {
//       
//       float2 a;                      // Offset:    0
//       float2 b;                      // Offset:    8
//       float2 velocityA;              // Offset:   16
//       float2 velocityB;              // Offset:   24
//       uint vesselId;                 // Offset:   32
//       uint flags;                    // Offset:   36
//       float2 localA;                 // Offset:   40
//       float2 localB;                 // Offset:   48
//       float2 startPosition;          // Offset:   56
//       float2 endPosition;            // Offset:   64
//       float startAngle;              // Offset:   72
//       float angleDelta;              // Offset:   76
//
//   } $Element;                        // Offset:    0 Size:    80
//
// }
//
// Resource bind info for _VesselTriggers
// {
//
//   struct VesselTrigger
//   {
//       
//       float2 center;                 // Offset:    0
//       float2 axisX;                  // Offset:    8
//       float2 axisY;                  // Offset:   16
//       float2 halfExtents;            // Offset:   24
//       uint vesselId;                 // Offset:   32
//       int priority;                  // Offset:   36
//       uint active;                   // Offset:   40
//       uint flags;                    // Offset:   44
//
//   } $Element;                        // Offset:    0 Size:    48
//
// }
//
// Resource bind info for _BoundaryGroups
// {
//
//   struct BoundaryGroup
//   {
//       
//       float2 minPosition;            // Offset:    0
//       float2 maxPosition;            // Offset:    8
//       float2 sweptMin;               // Offset:   16
//       float2 sweptMax;               // Offset:   24
//       uint first;                    // Offset:   32
//       uint end;                      // Offset:   36
//       uint contourFirst;             // Offset:   40
//       uint contourEnd;               // Offset:   44
//       uint vesselId;                 // Offset:   48
//
//   } $Element;                        // Offset:    0 Size:    52
//
// }
//
// Resource bind info for _ImprovedVessels
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
// Resource bind info for _Particles
// {
//
//   struct LiquidParticle
//   {
//       
//       float2 position;               // Offset:    0
//       float2 previousPosition;       // Offset:    8
//       float2 velocity;               // Offset:   16
//       float volumeMl;                // Offset:   24
//       float temperatureC;            // Offset:   28
//       uint vesselId;                 // Offset:   32
//       uint techniqueFlags;           // Offset:   36
//       uint stateFlags;               // Offset:   40
//       uint active;                   // Offset:   44
//       uint padding;                  // Offset:   48
//
//   } $Element;                        // Offset:    0 Size:    52
//
// }
//
// Resource bind info for _Lambdas
// {
//
//   float $Element;                    // Offset:    0 Size:     4
//
// }
//
// Resource bind info for _ReferenceDensityPressure
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
// Resource bind info for _GridHeads
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
// Resource bind info for _GridNext
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
// Resource bind info for _StreamParticles
// {
//
//   struct StreamParticle
//   {
//       
//       uint token;                    // Offset:    0
//       uint previousToken;            // Offset:    4
//       uint streamId;                 // Offset:    8
//       uint sourceId;                 // Offset:   12
//       float delay;                   // Offset:   16
//       float stepDt;                  // Offset:   20
//       float startFraction;           // Offset:   24
//       float birthTime;               // Offset:   28
//       float radius;                  // Offset:   32
//       uint detached;                 // Offset:   36
//       uint pending;                  // Offset:   40
//       uint padding;                  // Offset:   44
//
//   } $Element;                        // Offset:    0 Size:    48
//
// }
//
// Resource bind info for _ImprovedDiagnostics
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// _Boundaries                       texture  struct         r/o             t0      1 
// _VesselTriggers                   texture  struct         r/o             t1      1 
// _BoundaryGroups                   texture  struct         r/o             t2      1 
// _ImprovedVessels                  texture  struct         r/o             t3      1 
// _Particles                            UAV  struct         r/w             u0      1 
// _Lambdas                              UAV  struct         r/w             u1      1 
// _ReferenceDensityPressure             UAV  struct         r/w             u2      1 
// _GridHeads                            UAV  struct         r/w             u3      1 
// _GridNext                             UAV  struct         r/w             u4      1 
// _StreamParticles                      UAV  struct         r/w             u5      1 
// _ImprovedDiagnostics                  UAV  struct         r/w             u6      1 
// $Globals                          cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[20], immediateIndexed
dcl_resource_structured t0, 80
dcl_resource_structured t1, 48
dcl_resource_structured t2, 52
dcl_resource_structured t3, 16
dcl_uav_structured u0, 52
dcl_uav_structured u1, 4
dcl_uav_structured u2, 16
dcl_uav_structured u3, 4
dcl_uav_structured u4, 4
dcl_uav_structured u5, 48
dcl_uav_structured u6, 16
dcl_input vThreadID.x
dcl_temps 14
dcl_thread_group 64, 1, 1
uge r0.x, vThreadID.x, cb0[1].y
if_nz r0.x
  ret 
endif 
ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r0.xy, vThreadID.x, l(0), u0.xyxx
ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r1.xyz, vThreadID.x, l(16), u0.xyzx
ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r0.z, vThreadID.x, l(32), u0.xxxx
ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r2.xy, vThreadID.x, l(40), u0.xyxx
ine r0.w, r2.y, l(0)
and r1.w, r2.x, l(4)
ieq r1.w, r1.w, l(0)
and r0.w, r0.w, r1.w
ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r1.w, vThreadID.x, l(20), u5.xxxx
lt r1.w, l(0.000001), r1.w
and r0.w, r0.w, r1.w
if_z r0.w
  store_structured u1.x, vThreadID.x, l(0), l(0)
  store_structured u6.xyzw, vThreadID.x, l(0), l(0,0,0,0)
  ret 
endif 
mov r2.yz, l(0,0,0,0)
mov r3.xyz, l(0,0,0,0)
mov r0.w, l(0)
loop 
  ige r1.w, r3.z, cb0[18].y
  mov r0.w, l(0)
  breakc_nz r1.w
  ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r1.w, r3.z, l(0), t3.xxxx
  ftou r1.w, r1.w
  ieq r1.w, r0.z, r1.w
  if_nz r1.w
    ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r3.xy, r3.z, l(4), t3.xyxx
    mov r0.w, l(-1)
    break 
  endif 
  iadd r2.x, r3.z, l(1)
  mov r3.xyz, r2.yzxy
  mov r0.w, r1.w
endloop 
mul r1.w, cb0[6].x, cb0[18].z
sqrt r1.w, r1.w
mul r1.w, r1.w, cb0[18].w
mul r2.xy, cb0[8].yyyy, l(2.100000, 0.050000, 0.000000, 0.000000)
max r1.w, r1.w, r2.x
min r4.y, r1.w, cb0[8].z
mov r4.x, cb0[18].z
movc r2.xz, r0.wwww, r3.xxyx, r4.xxyx
max r0.w, r1.z, l(0.000000)
mul r0.w, r2.x, r0.w
mul r1.z, r2.z, r2.z
mul r1.w, r1.z, l(3.141593)
div r2.w, l(4.000000), r1.w
mul r0.w, r0.w, r2.w
add r3.xy, r0.xyxx, -cb0[14].zwzz
div r3.xy, r3.xyxx, cb0[8].zzzz
round_ni r3.xy, r3.xyxx
ftoi r3.xy, r3.xyxx
max r2.y, r2.y, l(0.000100)
mul r1.w, r1.z, r1.w
div r1.w, l(-24.000000), r1.w
mov r3.zw, l(0,0,0,0)
mov r4.xy, cb0[2].yzyy
mov r4.z, r0.w
mov r4.w, l(0)
mov r5.w, l(0)
mov r6.y, l(-1)
loop 
  ilt r6.z, l(1), r6.y
  breakc_nz r6.z
  mov r6.zw, r3.zzzw
  mov r7.xy, r4.zwzz
  mov r7.z, r5.w
  mov r6.x, l(-1)
  loop 
    ilt r7.w, l(1), r6.x
    breakc_nz r7.w
    iadd r8.xy, r3.xyxx, r6.xyxx
    ige r8.zw, r8.xxxy, l(0, 0, 0, 0)
    and r7.w, r8.w, r8.z
    ilt r8.z, r8.x, r4.x
    and r7.w, r7.w, r8.z
    ilt r8.z, r8.y, r4.y
    and r7.w, r7.w, r8.z
    if_z r7.w
      iadd r7.w, r6.x, l(1)
      mov r6.x, r7.w
      continue 
    endif 
    imad r7.w, r8.y, r4.x, r8.x
    ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r7.w, r7.w, l(0), u3.xxxx
    mov r8.xy, r6.zwzz
    mov r8.zw, r7.xxxy
    mov r9.x, r7.z
    mov r9.y, r7.w
    mov r9.z, l(0)
    loop 
      ige r9.w, r9.y, l(0)
      ilt r10.x, r9.z, cb0[1].y
      and r9.w, r9.w, r10.x
      breakc_z r9.w
      iadd r9.z, r9.z, l(1)
      ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r10.xy, r9.y, l(0), u0.xyxx
      ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r9.w, r9.y, l(24), u0.xxxx
      ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r10.z, r9.y, l(32), u0.xxxx
      ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r11.xy, r9.y, l(40), u0.xyxx
      ine r10.w, r9.y, vThreadID.x
      ine r11.y, r11.y, l(0)
      and r11.x, r11.x, l(4)
      ieq r11.x, r11.x, l(0)
      and r11.x, r11.x, r11.y
      ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r11.y, r9.y, l(20), u5.xxxx
      lt r11.y, l(0.000001), r11.y
      and r11.x, r11.y, r11.x
      and r10.w, r10.w, r11.x
      ieq r10.z, r0.z, r10.z
      and r10.z, r10.z, r10.w
      if_nz r10.z
        add r10.xy, r0.xyxx, -r10.xyxx
        max r9.w, r9.w, l(0.000000)
        mul r9.w, r2.x, r9.w
        dp2 r10.z, r10.xyxx, r10.xyxx
        div r10.w, r10.z, r1.z
        add r10.w, -r10.w, l(1.000000)
        max r10.w, r10.w, l(0.000000)
        mul r11.x, r10.w, r10.w
        mul r11.x, r2.w, r11.x
        mul r10.w, r10.w, r11.x
        mad r8.z, r9.w, r10.w, r8.z
        ge r10.w, l(0.000000), r10.z
        umin r11.x, r9.y, vThreadID.x
        umax r11.y, r9.y, vThreadID.x
        imul null, r11.y, r11.y, l(0xac564b05)
        imad r11.y, r11.x, l(0x2c9277b5), r11.y
        and r11.y, r11.y, l(1023)
        utof r11.y, r11.y
        mul r11.y, r11.y, l(0.006136)
        sincos r12.x, r13.x, r11.y
        ieq r11.x, r11.x, vThreadID.x
        movc r11.x, r11.x, l(1.000000), l(-1.000000)
        mov r13.y, r12.x
        mul r11.xy, r11.xxxx, r13.xyxx
        mul r11.xy, r2.yyyy, r11.xyxx
        movc r10.xy, r10.wwww, r11.xyxx, r10.xyxx
        dp2 r10.w, r10.xyxx, r10.xyxx
        div r10.w, r10.w, r1.z
        add r10.w, -r10.w, l(1.000000)
        max r10.w, r10.w, l(0.000000)
        mul r10.w, r10.w, r10.w
        mul r10.w, r1.w, r10.w
        mul r10.xy, r10.xyxx, r10.wwww
        mul r11.xy, r9.wwww, r10.xyxx
        mad r8.xy, r9.wwww, r10.xyxx, r8.xyxx
        dp2 r9.w, r11.xyxx, r11.xyxx
        add r8.w, r8.w, r9.w
        sqrt r9.w, r10.z
        div r9.w, r9.w, r2.z
        add_sat r9.w, -r9.w, l(1.000000)
        add r9.x, r9.w, r9.x
      endif 
      ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r9.y, r9.y, l(0), u4.xxxx
    endloop 
    mov r6.zw, r8.xxxy
    mov r7.xy, r8.zwzz
    mov r7.z, r9.x
    iadd r6.x, r6.x, l(1)
  endloop 
  mov r3.zw, r6.zzzw
  mov r4.zw, r7.xxxy
  mov r5.w, r7.z
  iadd r6.y, r6.y, l(1)
endloop 
add r1.zw, r0.xxxy, -r2.zzzz
add r2.xy, r0.xyxx, r2.zzzz
mov r3.y, l(0)
mov r4.xy, l(0,0,0,0)
mov r0.w, r2.z
mov r2.w, l(0)
mov r6.x, l(0)
loop 
  ige r6.y, r6.x, cb0[18].x
  breakc_nz r6.y
  ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r7.xyzw, r6.x, l(0), t2.xyzw
  ge r6.yz, r2.xxyx, r7.xxyx
  and r6.y, r6.z, r6.y
  ge r6.zw, r7.zzzw, r1.zzzw
  and r6.z, r6.w, r6.z
  and r6.y, r6.z, r6.y
  if_z r6.y
    iadd r6.y, r6.x, l(1)
    mov r6.x, r6.y
    continue 
  endif 
  ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r6.yz, r6.x, l(32), t2.xxyx
  mov r7.xy, r4.xyxx
  mov r6.w, r0.w
  mov r7.z, r2.w
  mov r7.w, r6.y
  loop 
    uge r8.x, r7.w, r6.z
    breakc_nz r8.x
    ld_structured_indexable(structured_buffer, stride=80)(mixed,mixed,mixed,mixed) r8.xy, r7.w, l(32), t0.xyxx
    and r8.z, r8.y, l(16)
    if_z r8.z
      ine r8.x, r0.z, r8.x
      if_nz r8.x
        and r8.x, r8.y, l(2)
        ine r8.x, r8.x, l(0)
        if_nz r0.z
          mov r8.yzw, l(0,0,0,0)
          loop 
            ige r9.x, r8.z, cb0[3].y
            mov r8.w, l(0)
            breakc_nz r9.x
            ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r9.x, r8.z, l(32), t1.xxxx
            ieq r9.x, r0.z, r9.x
            ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r9.y, r8.z, l(44), t1.xxxx
            and r9.y, r9.y, l(2)
            ine r9.y, r9.y, l(0)
            and r9.x, r9.y, r9.x
            if_nz r9.x
              mov r8.yw, l(0,-1,0,-1)
              break 
            endif 
            iadd r3.x, r8.z, l(1)
            mov r8.yz, r3.yyxy
            mov r8.w, r9.x
          endloop 
          and r3.x, r8.y, r8.w
        else 
          mov r3.x, l(0)
        endif 
        or r3.x, r3.x, r8.x
        not r3.x, r3.x
      else 
        mov r3.x, l(-1)
      endif 
    else 
      mov r3.x, l(0)
    endif 
    if_z r3.x
      iadd r3.x, r7.w, l(1)
      mov r7.w, r3.x
      continue 
    endif 
    ld_structured_indexable(structured_buffer, stride=80)(mixed,mixed,mixed,mixed) r9.xyzw, r7.w, l(0), t0.xyzw
    add r10.xy, -r9.xyxx, r9.zwzz
    dp2 r3.x, r10.xyxx, r10.xyxx
    lt r8.x, l(0.000000), r3.x
    add r9.zw, r0.xxxy, -r9.xxxy
    dp2 r8.z, r9.zwzz, r10.xyxx
    div_sat r3.x, r8.z, r3.x
    and r3.x, r3.x, r8.x
    mad r8.xz, r10.xxyx, r3.xxxx, r9.xxyx
    add r8.xz, r0.xxyx, -r8.xxzx
    dp2 r3.x, r8.xzxx, r8.xzxx
    sqrt r3.x, r3.x
    ge r9.x, r3.x, r6.w
    if_nz r9.x
      iadd r9.x, r7.w, l(1)
      mov r7.w, r9.x
      continue 
    endif 
    lt r9.x, l(0.000010), r3.x
    div r8.xz, r8.xxzx, r3.xxxx
    mov r10.zw, -r10.yyyy
    dp2 r9.y, r10.xzxx, r10.xwxx
    rsq r9.y, r9.y
    mul r9.zw, r10.yyyx, l(0.000000, 0.000000, -1.000000, 1.000000)
    mul r9.yz, r9.yyyy, r9.zzwz
    movc r7.xy, r9.xxxx, r8.xzxx, r9.yzyy
    mov r6.w, r3.x
    iadd r7.w, r7.w, l(1)
    mov r7.z, l(-1)
  endloop 
  mov r4.xy, r7.xyxx
  mov r0.w, r6.w
  mov r2.w, r7.z
  iadd r6.x, r6.x, l(1)
endloop 
if_nz r2.w
  div r0.x, r0.w, r2.z
  mov_sat r0.y, r0.x
  add r0.z, -r0.y, l(1.000000)
  mul r0.w, r0.z, l(0.125000)
  mad r1.z, -r0.y, r0.y, l(1.000000)
  log r1.z, r1.z
  mul r1.z, r1.z, l(3.500000)
  exp r1.z, r1.z
  mad r6.xyzw, r0.zzzz, l(0.125000, 0.250000, 0.375000, 0.500000), r0.yyyy
  mad r6.xyzw, -r6.xyzw, r6.xyzw, l(1.000000, 1.000000, 1.000000, 1.000000)
  max r6.xyzw, r6.xyzw, l(0.000000, 0.000000, 0.000000, 0.000000)
  log r6.xyzw, r6.xyzw
  mul r6.xyzw, r6.xyzw, l(3.500000, 3.500000, 3.500000, 3.500000)
  exp r6.xyzw, r6.xyzw
  mul r1.w, r6.x, l(4.656419)
  mad r1.z, r1.z, l(1.164105), r1.w
  mad r1.z, r6.y, l(2.328209), r1.z
  mad r1.z, r6.z, l(4.656419), r1.z
  mad r1.z, r6.w, l(2.328209), r1.z
  mad r2.xyw, r0.zzzz, l(0.625000, 0.750000, 0.000000, 0.875000), r0.yyyy
  mad r2.xyw, -r2.xyxw, r2.xyxw, l(1.000000, 1.000000, 0.000000, 1.000000)
  max r2.xyw, r2.xyxw, l(0.000000, 0.000000, 0.000000, 0.000000)
  log r2.xyw, r2.xyxw
  mul r2.xyw, r2.xyxw, l(3.500000, 3.500000, 0.000000, 3.500000)
  exp r2.xyw, r2.xyxw
  mad r0.y, r2.x, l(4.656419), r1.z
  mad r0.y, r2.y, l(2.328209), r0.y
  mad r0.y, r2.w, l(4.656419), r0.y
  mul r0.y, r0.w, r0.y
  mul r0.y, r0.y, cb0[19].z
  mad r0.x, -r0.x, r0.x, l(1.000000)
  max r0.x, r0.x, l(0.000000)
  log r0.x, r0.x
  mul r0.xy, r0.xyxx, l(3.500000, 0.333333, 0.000000, 0.000000)
  exp r0.x, r0.x
  mul r0.x, r0.x, l(1.164105)
  div r0.x, r0.x, r2.z
  mul r0.xz, r0.xxxx, -r4.xxyx
  mul r0.xz, r0.xxzx, cb0[19].zzzz
else 
  mov r0.xyz, l(0,0,0,0)
endif 
add r2.x, r0.y, r4.z
add r0.xy, r0.xzxx, r3.zwzz
dp2 r0.x, r0.xyxx, r0.xyxx
add r0.x, r0.x, r4.w
add r0.y, r2.x, l(-1.000000)
max r2.y, r0.y, l(0.000000)
ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r0.y, vThreadID.x, l(20), u5.xxxx
mul r0.y, r0.y, r0.y
max r0.y, r0.y, l(0.000000)
div r0.y, cb0[19].x, r0.y
add r0.x, r0.y, r0.x
max r0.x, r0.x, l(0.000100)
div r0.x, -r2.y, r0.x
store_structured u1.x, vThreadID.x, l(0), r0.x
dp2 r2.w, r1.xyxx, r1.xyxx
mov r2.z, l(0)
store_structured u6.xyzw, vThreadID.x, l(0), r2.xyzw
mov r5.xyz, l(0,0,0,0)
store_structured u2.xyzw, vThreadID.x, l(0), r5.xyzw
ret 
// Approximately 342 instruction slots used
