//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer $Globals
// {
//
//   int _StreamHeadCount;              // Offset:    0 Size:     4 [unused]
//   int _StreamRenderingEnabled;       // Offset:    4 Size:     4 [unused]
//   float _SimulationTime;             // Offset:    8 Size:     4 [unused]
//   float _StreamMaximumGap;           // Offset:   12 Size:     4 [unused]
//   float _StreamMaximumLength;        // Offset:   16 Size:     4 [unused]
//   int _ParticleCapacity;             // Offset:   20 Size:     4
//   int _MaximumIngredients;           // Offset:   24 Size:     4 [unused]
//   int _IngredientCount;              // Offset:   28 Size:     4 [unused]
//   int _SpawnCount;                   // Offset:   32 Size:     4 [unused]
//   int _GridWidth;                    // Offset:   36 Size:     4
//   int _GridHeight;                   // Offset:   40 Size:     4
//   int _GridCellCount;                // Offset:   44 Size:     4 [unused]
//   int _BoundaryCount;                // Offset:   48 Size:     4 [unused]
//   int _VesselTriggerCount;           // Offset:   52 Size:     4 [unused]
//   int _AgitatorCount;                // Offset:   56 Size:     4 [unused]
//   int _TechniqueTargetVessel;        // Offset:   60 Size:     4 [unused]
//   int _TechniqueMask;                // Offset:   64 Size:     4 [unused]
//   int _TechniqueStateMask;           // Offset:   68 Size:     4 [unused]
//   int _TransformTargetVessel;        // Offset:   72 Size:     4 [unused]
//   int _SuspensionTargetVessel;       // Offset:   76 Size:     4 [unused]
//   int _SuspensionEnabled;            // Offset:   80 Size:     4 [unused]
//   int _ReferenceSolverEnabled;       // Offset:   84 Size:     4 [unused]
//   int _ImprovedPhysics;              // Offset:   88 Size:     4 [unused]
//   int _TransferTargetVessel;         // Offset:   92 Size:     4 [unused]
//   float _ReferenceParticleVolume;    // Offset:   96 Size:     4
//   float _ReferenceRestDensity;       // Offset:  100 Size:     4
//   float _ReferencePressureStiffness; // Offset:  104 Size:     4
//   float _ReferenceNearPressureStiffness;// Offset:  108 Size:     4
//   float _ReferenceViscosityRate;     // Offset:  112 Size:     4 [unused]
//   float _ReferenceMaximumTensionRatio;// Offset:  116 Size:     4
//   float _ReferenceMaximumAcceleration;// Offset:  120 Size:     4 [unused]
//   float _ReferenceMaximumDisplacementRatio;// Offset:  124 Size:     4 [unused]
//   float _DeltaTime;                  // Offset:  128 Size:     4 [unused]
//   float _ParticleRadius;             // Offset:  132 Size:     4 [unused]
//   float _SmoothingRadius;            // Offset:  136 Size:     4
//   float _RestDensity;                // Offset:  140 Size:     4 [unused]
//   float _DensityCompliance;          // Offset:  144 Size:     4 [unused]
//   float _LambdaEpsilon;              // Offset:  148 Size:     4 [unused]
//   float _ArtificialPressureStrength; // Offset:  152 Size:     4 [unused]
//   float _ArtificialPressureRadiusRatio;// Offset:  156 Size:     4 [unused]
//   float _BoundaryDensityScale;       // Offset:  160 Size:     4 [unused]
//   float _WallFriction;               // Offset:  164 Size:     4 [unused]
//   float _WallRestitution;            // Offset:  168 Size:     4 [unused]
//   float _SplashTransfer;             // Offset:  172 Size:     4 [unused]
//   float _SplashMinimumImpactSpeed;   // Offset:  176 Size:     4 [unused]
//   float _BottomImpactSpread;         // Offset:  180 Size:     4 [unused]
//   float _VelocityDamping;            // Offset:  184 Size:     4 [unused]
//   float _MaximumSpeed;               // Offset:  188 Size:     4 [unused]
//   float _ClosedVesselDampingRate;    // Offset:  192 Size:     4 [unused]
//   float _ClosedVesselMaximumRelativeSpeed;// Offset:  196 Size:     4 [unused]
//   float _Viscosity;                  // Offset:  200 Size:     4 [unused]
//   float _PassiveMixRate;             // Offset:  204 Size:     4 [unused]
//   float _AgitationMixRate;           // Offset:  208 Size:     4 [unused]
//   float _FullMixRelativeSpeed;       // Offset:  212 Size:     4 [unused]
//   float _MaximumMixPerSubstep;       // Offset:  216 Size:     4 [unused]
//   float _MinimumVisibleAlpha;        // Offset:  220 Size:     4 [unused]
//   float2 _Gravity;                   // Offset:  224 Size:     8 [unused]
//   float2 _GridOrigin;                // Offset:  232 Size:     8
//   float2 _WorldMin;                  // Offset:  240 Size:     8 [unused]
//   float2 _WorldMax;                  // Offset:  248 Size:     8 [unused]
//   float2 _TransformDelta;            // Offset:  256 Size:     8 [unused]
//   int _SwapA;                        // Offset:  264 Size:     4 [unused]
//   int _SwapB;                        // Offset:  268 Size:     4 [unused]
//   float2 _SwapDeltaA;                // Offset:  272 Size:     8 [unused]
//   float2 _SwapDeltaB;                // Offset:  280 Size:     8 [unused]
//   int _BoundaryGroupCount;           // Offset:  288 Size:     4 [unused]
//   int _ImprovedVesselCount;          // Offset:  292 Size:     4 [unused]
//   float _ImprovedAreaPerMl;          // Offset:  296 Size:     4 [unused]
//   float _ImprovedKernelRatio;        // Offset:  300 Size:     4 [unused]
//   float _ImprovedCompliance;         // Offset:  304 Size:     4 [unused]
//   float _ImprovedCorrectionRatio;    // Offset:  308 Size:     4 [unused]
//   float _ImprovedWallDensity;        // Offset:  312 Size:     4 [unused]
//   float _ImprovedShear;              // Offset:  316 Size:     4 [unused]
//   float _ImprovedTension;            // Offset:  320 Size:     4 [unused]
//   float _ImprovedWetting;            // Offset:  324 Size:     4 [unused]
//
// }
//
// Resource bind info for _Particles
// {
//
//   struct LiquidParticle
//   {
//       
//       float2 position;               // Offset:    0
//       float2 previousPosition;       // Offset:    8
//       float2 velocity;               // Offset:   16
//       float volumeMl;                // Offset:   24
//       float temperatureC;            // Offset:   28
//       uint vesselId;                 // Offset:   32
//       uint techniqueFlags;           // Offset:   36
//       uint stateFlags;               // Offset:   40
//       uint active;                   // Offset:   44
//       uint padding;                  // Offset:   48
//
//   } $Element;                        // Offset:    0 Size:    52
//
// }
//
// Resource bind info for _ReferenceDensityPressure
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
// Resource bind info for _GridHeads
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
// Resource bind info for _GridNext
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
// Resource bind info for _StreamParticles
// {
//
//   struct StreamParticle
//   {
//       
//       uint token;                    // Offset:    0
//       uint previousToken;            // Offset:    4
//       uint streamId;                 // Offset:    8
//       uint sourceId;                 // Offset:   12
//       float delay;                   // Offset:   16
//       float stepDt;                  // Offset:   20
//       float startFraction;           // Offset:   24
//       float birthTime;               // Offset:   28
//       float radius;                  // Offset:   32
//       uint detached;                 // Offset:   36
//       uint pending;                  // Offset:   40
//       uint padding;                  // Offset:   44
//
//   } $Element;                        // Offset:    0 Size:    48
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// _Particles                            UAV  struct         r/w             u0      1 
// _ReferenceDensityPressure             UAV  struct         r/w             u1      1 
// _GridHeads                            UAV  struct         r/w             u2      1 
// _GridNext                             UAV  struct         r/w             u3      1 
// _StreamParticles                      UAV  struct         r/w             u4      1 
// $Globals                          cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[15], immediateIndexed
dcl_uav_structured u0, 52
dcl_uav_structured u1, 16
dcl_uav_structured u2, 4
dcl_uav_structured u3, 4
dcl_uav_structured u4, 48
dcl_input vThreadID.x
dcl_temps 9
dcl_thread_group 64, 1, 1
uge r0.x, vThreadID.x, cb0[1].y
if_nz r0.x
  ret 
endif 
ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r0.xy, vThreadID.x, l(0), u0.xyxx
ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r0.z, vThreadID.x, l(24), u0.xxxx
ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r0.w, vThreadID.x, l(32), u0.xxxx
ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r1.xy, vThreadID.x, l(40), u0.xyxx
ine r1.y, r1.y, l(0)
and r1.x, r1.x, l(4)
ieq r1.x, r1.x, l(0)
and r1.x, r1.x, r1.y
ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r1.y, vThreadID.x, l(20), u4.xxxx
lt r1.y, l(0.000001), r1.y
and r1.x, r1.y, r1.x
if_z r1.x
  store_structured u1.xyzw, vThreadID.x, l(0), l(0,0,0,0)
  ret 
endif 
max r1.x, cb0[6].x, l(0.001000)
div r0.z, r0.z, r1.x
max r0.z, r0.z, l(0.000001)
add r1.yz, r0.xxyx, -cb0[14].zzwz
div r1.yz, r1.yyzy, cb0[8].zzzz
round_ni r1.yz, r1.yyzy
ftoi r1.yz, r1.yyzy
mov r1.w, cb0[2].y
mov r2.x, cb0[2].z
mov r3.w, r0.z
mov r2.y, r0.z
mov r3.z, l(0)
mov r4.y, l(-1)
loop 
  ilt r2.z, l(1), r4.y
  breakc_nz r2.z
  mov r2.z, r3.w
  mov r2.w, r2.y
  mov r4.z, r3.z
  mov r4.x, l(-1)
  loop 
    ilt r4.w, l(1), r4.x
    breakc_nz r4.w
    iadd r5.xy, r1.yzyy, r4.xyxx
    ige r5.zw, r5.xxxy, l(0, 0, 0, 0)
    and r4.w, r5.w, r5.z
    ilt r5.z, r5.x, r1.w
    and r4.w, r4.w, r5.z
    ilt r5.z, r5.y, r2.x
    and r4.w, r4.w, r5.z
    if_z r4.w
      iadd r4.w, r4.x, l(1)
      mov r4.x, r4.w
      continue 
    endif 
    imad r4.w, r5.y, r1.w, r5.x
    ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r4.w, r4.w, l(0), u2.xxxx
    mov r5.xy, r2.zwzz
    mov r5.z, r4.z
    mov r5.w, r4.w
    mov r6.x, l(0)
    loop 
      ige r6.y, r5.w, l(0)
      ilt r6.z, r6.x, cb0[1].y
      and r6.y, r6.z, r6.y
      breakc_z r6.y
      iadd r6.x, r6.x, l(1)
      ine r6.y, r5.w, vThreadID.x
      if_nz r6.y
        ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r6.yz, r5.w, l(0), u0.xxyx
        ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r6.w, r5.w, l(24), u0.xxxx
        ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r7.x, r5.w, l(32), u0.xxxx
        ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r7.yz, r5.w, l(40), u0.xxyx
        ine r7.z, r7.z, l(0)
        and r7.y, r7.y, l(4)
        ieq r7.y, r7.y, l(0)
        and r7.y, r7.y, r7.z
        ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r7.z, r5.w, l(20), u4.xxxx
        lt r7.z, l(0.000001), r7.z
        and r7.y, r7.z, r7.y
        ieq r7.x, r0.w, r7.x
        and r7.x, r7.x, r7.y
        add r6.yz, r0.xxyx, -r6.yyzy
        dp2 r6.y, r6.yzyy, r6.yzyy
        sqrt r6.y, r6.y
        div r6.y, r6.y, cb0[8].z
        add_sat r6.y, -r6.y, l(1.000000)
        div r6.z, r6.w, r1.x
        max r6.z, r6.z, l(0.000001)
        mul r6.w, r6.y, r6.y
        mul r7.y, r6.z, r6.w
        mad r8.x, r6.w, r6.z, r5.x
        mad r8.y, r7.y, r6.y, r5.y
        add r6.w, r6.z, r6.z
        add r6.z, r0.z, r6.z
        div r6.z, r6.w, r6.z
        mad r8.z, r6.y, r6.z, r5.z
        movc r5.xyz, r7.xxxx, r8.xyzx, r5.xyzx
      endif 
      ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r5.w, r5.w, l(0), u3.xxxx
    endloop 
    mov r2.zw, r5.xxxy
    mov r4.z, r5.z
    iadd r4.x, r4.x, l(1)
  endloop 
  mov r3.w, r2.z
  mov r2.y, r2.w
  mov r3.z, r4.z
  iadd r4.y, r4.y, l(1)
endloop 
add r0.x, r3.w, -cb0[6].y
mul r0.x, r0.x, cb0[6].z
mul r0.y, cb0[6].y, -cb0[6].z
mul r0.y, r0.y, cb0[7].y
max r3.x, r0.x, r0.y
mul r3.y, r2.y, cb0[6].w
store_structured u1.xyzw, vThreadID.x, l(0), r3.xyzw
ret 
// Approximately 117 instruction slots used
