//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer $Globals
// {
//
//   int _StreamHeadCount;              // Offset:    0 Size:     4 [unused]
//   int _StreamRenderingEnabled;       // Offset:    4 Size:     4 [unused]
//   float _SimulationTime;             // Offset:    8 Size:     4 [unused]
//   float _StreamMaximumGap;           // Offset:   12 Size:     4 [unused]
//   float _StreamMaximumLength;        // Offset:   16 Size:     4 [unused]
//   int _ParticleCapacity;             // Offset:   20 Size:     4
//   int _MaximumIngredients;           // Offset:   24 Size:     4 [unused]
//   int _IngredientCount;              // Offset:   28 Size:     4 [unused]
//   int _SpawnCount;                   // Offset:   32 Size:     4 [unused]
//   int _GridWidth;                    // Offset:   36 Size:     4
//   int _GridHeight;                   // Offset:   40 Size:     4
//   int _GridCellCount;                // Offset:   44 Size:     4 [unused]
//   int _BoundaryCount;                // Offset:   48 Size:     4 [unused]
//   int _VesselTriggerCount;           // Offset:   52 Size:     4
//   int _AgitatorCount;                // Offset:   56 Size:     4 [unused]
//   int _TechniqueTargetVessel;        // Offset:   60 Size:     4 [unused]
//   int _TechniqueMask;                // Offset:   64 Size:     4 [unused]
//   int _TechniqueStateMask;           // Offset:   68 Size:     4 [unused]
//   int _TransformTargetVessel;        // Offset:   72 Size:     4 [unused]
//   int _SuspensionTargetVessel;       // Offset:   76 Size:     4 [unused]
//   int _SuspensionEnabled;            // Offset:   80 Size:     4 [unused]
//   int _ReferenceSolverEnabled;       // Offset:   84 Size:     4 [unused]
//   int _ImprovedPhysics;              // Offset:   88 Size:     4 [unused]
//   int _TransferTargetVessel;         // Offset:   92 Size:     4 [unused]
//   float _ReferenceParticleVolume;    // Offset:   96 Size:     4 [unused]
//   float _ReferenceRestDensity;       // Offset:  100 Size:     4 [unused]
//   float _ReferencePressureStiffness; // Offset:  104 Size:     4 [unused]
//   float _ReferenceNearPressureStiffness;// Offset:  108 Size:     4 [unused]
//   float _ReferenceViscosityRate;     // Offset:  112 Size:     4 [unused]
//   float _ReferenceMaximumTensionRatio;// Offset:  116 Size:     4 [unused]
//   float _ReferenceMaximumAcceleration;// Offset:  120 Size:     4 [unused]
//   float _ReferenceMaximumDisplacementRatio;// Offset:  124 Size:     4 [unused]
//   float _DeltaTime;                  // Offset:  128 Size:     4 [unused]
//   float _ParticleRadius;             // Offset:  132 Size:     4
//   float _SmoothingRadius;            // Offset:  136 Size:     4
//   float _RestDensity;                // Offset:  140 Size:     4
//   float _DensityCompliance;          // Offset:  144 Size:     4 [unused]
//   float _LambdaEpsilon;              // Offset:  148 Size:     4 [unused]
//   float _ArtificialPressureStrength; // Offset:  152 Size:     4
//   float _ArtificialPressureRadiusRatio;// Offset:  156 Size:     4
//   float _BoundaryDensityScale;       // Offset:  160 Size:     4
//   float _WallFriction;               // Offset:  164 Size:     4 [unused]
//   float _WallRestitution;            // Offset:  168 Size:     4 [unused]
//   float _SplashTransfer;             // Offset:  172 Size:     4 [unused]
//   float _SplashMinimumImpactSpeed;   // Offset:  176 Size:     4 [unused]
//   float _BottomImpactSpread;         // Offset:  180 Size:     4 [unused]
//   float _VelocityDamping;            // Offset:  184 Size:     4 [unused]
//   float _MaximumSpeed;               // Offset:  188 Size:     4 [unused]
//   float _ClosedVesselDampingRate;    // Offset:  192 Size:     4 [unused]
//   float _ClosedVesselMaximumRelativeSpeed;// Offset:  196 Size:     4 [unused]
//   float _Viscosity;                  // Offset:  200 Size:     4 [unused]
//   float _PassiveMixRate;             // Offset:  204 Size:     4 [unused]
//   float _AgitationMixRate;           // Offset:  208 Size:     4 [unused]
//   float _FullMixRelativeSpeed;       // Offset:  212 Size:     4 [unused]
//   float _MaximumMixPerSubstep;       // Offset:  216 Size:     4 [unused]
//   float _MinimumVisibleAlpha;        // Offset:  220 Size:     4 [unused]
//   float2 _Gravity;                   // Offset:  224 Size:     8 [unused]
//   float2 _GridOrigin;                // Offset:  232 Size:     8
//   float2 _WorldMin;                  // Offset:  240 Size:     8 [unused]
//   float2 _WorldMax;                  // Offset:  248 Size:     8 [unused]
//   float2 _TransformDelta;            // Offset:  256 Size:     8 [unused]
//   int _SwapA;                        // Offset:  264 Size:     4 [unused]
//   int _SwapB;                        // Offset:  268 Size:     4 [unused]
//   float2 _SwapDeltaA;                // Offset:  272 Size:     8 [unused]
//   float2 _SwapDeltaB;                // Offset:  280 Size:     8 [unused]
//   int _BoundaryGroupCount;           // Offset:  288 Size:     4
//   int _ImprovedVesselCount;          // Offset:  292 Size:     4 [unused]
//   float _ImprovedAreaPerMl;          // Offset:  296 Size:     4 [unused]
//   float _ImprovedKernelRatio;        // Offset:  300 Size:     4 [unused]
//   float _ImprovedCompliance;         // Offset:  304 Size:     4 [unused]
//   float _ImprovedCorrectionRatio;    // Offset:  308 Size:     4 [unused]
//   float _ImprovedWallDensity;        // Offset:  312 Size:     4 [unused]
//   float _ImprovedShear;              // Offset:  316 Size:     4 [unused]
//   float _ImprovedTension;            // Offset:  320 Size:     4 [unused]
//   float _ImprovedWetting;            // Offset:  324 Size:     4 [unused]
//
// }
//
// Resource bind info for _Boundaries
// {
//
//   struct BoundarySegment
//   {
//       
//       float2 a;                      // Offset:    0
//       float2 b;                      // Offset:    8
//       float2 velocityA;              // Offset:   16
//       float2 velocityB;              // Offset:   24
//       uint vesselId;                 // Offset:   32
//       uint flags;                    // Offset:   36
//       float2 localA;                 // Offset:   40
//       float2 localB;                 // Offset:   48
//       float2 startPosition;          // Offset:   56
//       float2 endPosition;            // Offset:   64
//       float startAngle;              // Offset:   72
//       float angleDelta;              // Offset:   76
//
//   } $Element;                        // Offset:    0 Size:    80
//
// }
//
// Resource bind info for _VesselTriggers
// {
//
//   struct VesselTrigger
//   {
//       
//       float2 center;                 // Offset:    0
//       float2 axisX;                  // Offset:    8
//       float2 axisY;                  // Offset:   16
//       float2 halfExtents;            // Offset:   24
//       uint vesselId;                 // Offset:   32
//       int priority;                  // Offset:   36
//       uint active;                   // Offset:   40
//       uint flags;                    // Offset:   44
//
//   } $Element;                        // Offset:    0 Size:    48
//
// }
//
// Resource bind info for _BoundaryGroups
// {
//
//   struct BoundaryGroup
//   {
//       
//       float2 minPosition;            // Offset:    0
//       float2 maxPosition;            // Offset:    8
//       float2 sweptMin;               // Offset:   16
//       float2 sweptMax;               // Offset:   24
//       uint first;                    // Offset:   32
//       uint end;                      // Offset:   36
//       uint contourFirst;             // Offset:   40
//       uint contourEnd;               // Offset:   44
//       uint vesselId;                 // Offset:   48
//
//   } $Element;                        // Offset:    0 Size:    52
//
// }
//
// Resource bind info for _Particles
// {
//
//   struct LiquidParticle
//   {
//       
//       float2 position;               // Offset:    0
//       float2 previousPosition;       // Offset:    8
//       float2 velocity;               // Offset:   16
//       float volumeMl;                // Offset:   24
//       float temperatureC;            // Offset:   28
//       uint vesselId;                 // Offset:   32
//       uint techniqueFlags;           // Offset:   36
//       uint stateFlags;               // Offset:   40
//       uint active;                   // Offset:   44
//       uint padding;                  // Offset:   48
//
//   } $Element;                        // Offset:    0 Size:    52
//
// }
//
// Resource bind info for _PositionDeltas
// {
//
//   float2 $Element;                   // Offset:    0 Size:     8
//
// }
//
// Resource bind info for _Lambdas
// {
//
//   float $Element;                    // Offset:    0 Size:     4
//
// }
//
// Resource bind info for _GridHeads
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
// Resource bind info for _GridNext
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
// Resource bind info for _StreamParticles
// {
//
//   struct StreamParticle
//   {
//       
//       uint token;                    // Offset:    0
//       uint previousToken;            // Offset:    4
//       uint streamId;                 // Offset:    8
//       uint sourceId;                 // Offset:   12
//       float delay;                   // Offset:   16
//       float stepDt;                  // Offset:   20
//       float startFraction;           // Offset:   24
//       float birthTime;               // Offset:   28
//       float radius;                  // Offset:   32
//       uint detached;                 // Offset:   36
//       uint pending;                  // Offset:   40
//       uint padding;                  // Offset:   44
//
//   } $Element;                        // Offset:    0 Size:    48
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// _Boundaries                       texture  struct         r/o             t0      1 
// _VesselTriggers                   texture  struct         r/o             t1      1 
// _BoundaryGroups                   texture  struct         r/o             t2      1 
// _Particles                            UAV  struct         r/w             u0      1 
// _PositionDeltas                       UAV  struct         r/w             u1      1 
// _Lambdas                              UAV  struct         r/w             u2      1 
// _GridHeads                            UAV  struct         r/w             u3      1 
// _GridNext                             UAV  struct         r/w             u4      1 
// _StreamParticles                      UAV  struct         r/w             u5      1 
// $Globals                          cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[19], immediateIndexed
dcl_resource_structured t0, 80
dcl_resource_structured t1, 48
dcl_resource_structured t2, 52
dcl_uav_structured u0, 52
dcl_uav_structured u1, 8
dcl_uav_structured u2, 4
dcl_uav_structured u3, 4
dcl_uav_structured u4, 4
dcl_uav_structured u5, 48
dcl_input vThreadID.x
dcl_temps 11
dcl_thread_group 64, 1, 1
uge r0.x, vThreadID.x, cb0[1].y
if_nz r0.x
  ret 
endif 
ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r0.xy, vThreadID.x, l(0), u0.xyxx
ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r0.z, vThreadID.x, l(24), u0.xxxx
ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r0.w, vThreadID.x, l(32), u0.xxxx
ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r1.xy, vThreadID.x, l(40), u0.xyxx
ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r1.z, vThreadID.x, l(20), u5.xxxx
ge r1.z, l(0.000001), r1.z
ieq r1.y, r1.y, l(0)
or r1.y, r1.y, r1.z
and r1.x, r1.x, l(4)
ine r1.x, r1.x, l(0)
or r1.x, r1.x, r1.y
if_nz r1.x
  store_structured u1.xy, vThreadID.x, l(0), l(0,0,0,0)
  ret 
endif 
max r1.x, cb0[9].w, l(0.100000)
min r1.x, r1.x, l(0.900000)
mul r1.x, r1.x, cb0[8].z
mul r1.x, r1.x, r1.x
mul r1.y, cb0[8].z, cb0[8].z
lt r1.z, r1.x, r1.y
mad r1.x, cb0[8].z, cb0[8].z, -r1.x
mul r1.w, r1.y, r1.y
mul r2.xy, r1.wxww, r1.wxww
max r2.x, r2.x, l(0.000000)
mul r2.x, r2.x, l(3.141593)
div r2.x, l(4.000000), r2.x
mul r2.y, r2.x, r2.y
mul r1.x, r1.x, r2.y
and r1.x, r1.x, r1.z
add r2.yz, r0.xxyx, -cb0[14].zzwz
div r2.yz, r2.yyzy, cb0[8].zzzz
round_ni r2.yz, r2.yyzy
ftoi r2.yz, r2.yyzy
mul r3.xy, cb0[8].yyyy, l(0.050000, 0.750000, 0.000000, 0.000000)
max r1.z, r3.x, l(0.000100)
max r2.w, cb0[8].w, l(0.010000)
mul r1.w, r1.w, cb0[8].z
max r1.xw, r1.xxxw, l(0.000010, 0.000000, 0.000000, 0.000000)
mul r1.w, r1.w, l(3.141593)
div r1.w, l(-30.000000), r1.w
mov r3.xz, l(0,0,0,0)
mov r3.w, cb0[2].y
mov r4.x, cb0[2].z
mov r5.y, l(-1)
loop 
  ilt r4.y, l(1), r5.y
  breakc_nz r4.y
  mov r4.yz, r3.xxzx
  mov r5.x, l(-1)
  loop 
    ilt r4.w, l(1), r5.x
    breakc_nz r4.w
    iadd r5.zw, r2.yyyz, r5.xxxy
    ige r6.xy, r5.zwzz, l(0, 0, 0, 0)
    and r4.w, r6.y, r6.x
    ilt r6.x, r5.z, r3.w
    and r4.w, r4.w, r6.x
    ilt r6.x, r5.w, r4.x
    and r4.w, r4.w, r6.x
    if_z r4.w
      iadd r4.w, r5.x, l(1)
      mov r5.x, r4.w
      continue 
    endif 
    imad r4.w, r5.w, r3.w, r5.z
    ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r4.w, r4.w, l(0), u3.xxxx
    ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r5.z, vThreadID.x, l(0), u2.xxxx
    mov r6.xy, r4.yzyy
    mov r5.w, r4.w
    mov r6.z, l(0)
    loop 
      ige r6.w, r5.w, l(0)
      ilt r7.x, r6.z, cb0[1].y
      and r6.w, r6.w, r7.x
      breakc_z r6.w
      iadd r6.z, r6.z, l(1)
      ine r6.w, r5.w, vThreadID.x
      if_nz r6.w
        ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r7.xy, r5.w, l(0), u0.xyxx
        ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r6.w, r5.w, l(24), u0.xxxx
        ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r7.z, r5.w, l(32), u0.xxxx
        ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r8.xy, r5.w, l(40), u0.xyxx
        ine r7.w, r8.y, l(0)
        and r8.x, r8.x, l(4)
        ieq r8.x, r8.x, l(0)
        and r7.w, r7.w, r8.x
        ieq r7.z, r0.w, r7.z
        and r7.z, r7.z, r7.w
        if_nz r7.z
          add r7.xy, r0.xyxx, -r7.xyxx
          dp2 r7.z, r7.xyxx, r7.xyxx
          lt r7.w, r7.z, r1.y
          if_nz r7.w
            max r6.w, r6.w, l(0.010000)
            ge r7.w, l(0.000000), r7.z
            umin r8.x, r5.w, vThreadID.x
            umax r8.y, r5.w, vThreadID.x
            imul null, r8.y, r8.y, l(0xac564b05)
            imad r8.y, r8.x, l(0x2c9277b5), r8.y
            and r8.y, r8.y, l(1023)
            utof r8.y, r8.y
            mul r8.y, r8.y, l(0.006136)
            sincos r9.x, r10.x, r8.y
            ieq r8.x, r8.x, vThreadID.x
            movc r8.x, r8.x, l(1.000000), l(-1.000000)
            mov r10.y, r9.x
            mul r8.xy, r8.xxxx, r10.xyxx
            mul r8.xy, r1.zzzz, r8.xyxx
            movc r7.xy, r7.wwww, r8.xyxx, r7.xyxx
            mad r7.z, cb0[8].z, cb0[8].z, -r7.z
            mul r7.w, r7.z, r7.z
            mul r7.w, r2.x, r7.w
            mul r7.z, r7.z, r7.w
            div r7.z, r7.z, r1.x
            min r7.z, r7.z, l(1.500000)
            mul r7.z, r7.z, r7.z
            mul r7.z, r7.z, r7.z
            ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r7.w, r5.w, l(0), u2.xxxx
            add r7.w, r5.z, r7.w
            mad r7.z, -cb0[9].z, r7.z, r7.w
            mul r6.w, r6.w, r7.z
            div r6.w, r6.w, r2.w
            dp2 r7.z, r7.xyxx, r7.xyxx
            sqrt r7.z, r7.z
            ge r7.w, l(0.000010), r7.z
            ge r8.x, r7.z, cb0[8].z
            or r7.w, r7.w, r8.x
            add r8.x, -r7.z, cb0[8].z
            mul r8.x, r8.x, r8.x
            mul r8.x, r1.w, r8.x
            mul r7.xy, r7.xyxx, r8.xxxx
            div r7.xy, r7.xyxx, r7.zzzz
            movc r7.xy, r7.wwww, l(0,0,0,0), r7.xyxx
            mad r6.xy, r6.wwww, r7.xyxx, r6.xyxx
          endif 
        endif 
      endif 
      ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r5.w, r5.w, l(0), u4.xxxx
    endloop 
    mov r4.yz, r6.xxyx
    iadd r5.x, r5.x, l(1)
  endloop 
  mov r3.xz, r4.yyzy
  iadd r5.y, r5.y, l(1)
endloop 
ine r1.x, r0.w, l(0)
lt r1.y, l(0.000000), cb0[10].x
and r1.x, r1.y, r1.x
if_nz r1.x
  add r1.xy, r0.xyxx, -cb0[8].zzzz
  add r2.xy, r0.xyxx, cb0[8].zzzz
  mov r4.y, l(0)
  mov r4.zw, l(0,0,0,0)
  mov r1.z, cb0[8].z
  mov r2.z, l(0)
  mov r3.w, l(0)
  loop 
    ige r5.x, r3.w, cb0[18].x
    breakc_nz r5.x
    ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r5.xyzw, r3.w, l(0), t2.xyzw
    ge r5.xy, r2.xyxx, r5.xyxx
    and r5.x, r5.y, r5.x
    ge r5.yz, r5.zzwz, r1.xxyx
    and r5.y, r5.z, r5.y
    and r5.x, r5.y, r5.x
    if_z r5.x
      iadd r5.x, r3.w, l(1)
      mov r3.w, r5.x
      continue 
    endif 
    ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r5.xy, r3.w, l(32), t2.xyxx
    mov r5.zw, r4.zzzw
    mov r6.x, r1.z
    mov r6.y, r2.z
    mov r6.z, r5.x
    loop 
      uge r6.w, r6.z, r5.y
      breakc_nz r6.w
      ld_structured_indexable(structured_buffer, stride=80)(mixed,mixed,mixed,mixed) r7.xy, r6.z, l(32), t0.xyxx
      and r6.w, r7.y, l(16)
      if_z r6.w
        ine r6.w, r0.w, r7.x
        if_nz r6.w
          and r6.w, r7.y, l(2)
          ine r6.w, r6.w, l(0)
          if_nz r0.w
            mov r7.xyz, l(0,0,0,0)
            loop 
              ige r7.w, r7.y, cb0[3].y
              mov r7.z, l(0)
              breakc_nz r7.w
              ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r7.w, r7.y, l(32), t1.xxxx
              ieq r7.w, r0.w, r7.w
              ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r8.x, r7.y, l(44), t1.xxxx
              and r8.x, r8.x, l(2)
              ine r8.x, r8.x, l(0)
              and r7.w, r7.w, r8.x
              if_nz r7.w
                mov r7.xz, l(-1,0,-1,0)
                break 
              endif 
              iadd r4.x, r7.y, l(1)
              mov r7.xy, r4.yxyy
              mov r7.z, r7.w
            endloop 
            and r4.x, r7.x, r7.z
          else 
            mov r4.x, l(0)
          endif 
          or r4.x, r4.x, r6.w
          not r4.x, r4.x
        else 
          mov r4.x, l(-1)
        endif 
      else 
        mov r4.x, l(0)
      endif 
      if_z r4.x
        iadd r4.x, r6.z, l(1)
        mov r6.z, r4.x
        continue 
      endif 
      ld_structured_indexable(structured_buffer, stride=80)(mixed,mixed,mixed,mixed) r8.xyzw, r6.z, l(0), t0.xyzw
      add r7.yw, -r8.xxxy, r8.zzzw
      dp2 r4.x, r7.ywyy, r7.ywyy
      lt r6.w, l(0.000000), r4.x
      add r8.zw, r0.xxxy, -r8.xxxy
      dp2 r8.z, r8.zwzz, r7.ywyy
      div_sat r4.x, r8.z, r4.x
      and r4.x, r4.x, r6.w
      mad r7.yw, r7.yyyw, r4.xxxx, r8.xxxy
      add r8.xy, r0.xyxx, -r7.ywyy
      dp2 r4.x, r8.xyxx, r8.xyxx
      sqrt r4.x, r4.x
      ge r6.w, r4.x, r6.x
      if_nz r6.w
        iadd r6.w, r6.z, l(1)
        mov r6.z, r6.w
        continue 
      endif 
      mov r5.zw, r7.yyyw
      mov r6.x, r4.x
      iadd r6.z, r6.z, l(1)
      mov r6.y, l(-1)
    endloop 
    mov r4.zw, r5.zzzw
    mov r1.z, r6.x
    mov r2.z, r6.y
    iadd r3.w, r3.w, l(1)
  endloop 
  max r0.z, r0.z, l(0.010000)
  mul r0.z, r0.z, cb0[10].x
  ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r0.w, vThreadID.x, l(0), u2.xxxx
  mul r0.z, r0.z, r0.w
  div r0.z, r0.z, r2.w
  add r0.xy, r0.xyxx, -r4.zwzz
  dp2 r0.w, r0.xyxx, r0.xyxx
  sqrt r0.w, r0.w
  ge r1.x, l(0.000010), r0.w
  ge r1.y, r0.w, cb0[8].z
  or r1.x, r1.y, r1.x
  add r1.y, -r0.w, cb0[8].z
  mul r1.y, r1.y, r1.y
  mul r1.y, r1.w, r1.y
  mul r0.xy, r0.xyxx, r1.yyyy
  div r0.xy, r0.xyxx, r0.wwww
  movc r0.xy, r1.xxxx, l(0,0,0,0), r0.xyxx
  mad r0.xy, r0.zzzz, r0.xyxx, r3.xzxx
  movc r3.xz, r2.zzzz, r0.xxyx, r3.xxzx
endif 
dp2 r0.x, r3.xzxx, r3.xzxx
sqrt r0.x, r0.x
lt r0.y, r3.y, r0.x
div r0.x, r3.y, r0.x
mul r0.xz, r0.xxxx, r3.xxzx
movc r0.xy, r0.yyyy, r0.xzxx, r3.xzxx
store_structured u1.xy, vThreadID.x, l(0), r0.xyxx
ret 
// Approximately 283 instruction slots used
