//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer $Globals
// {
//
//   int _StreamHeadCount;              // Offset:    0 Size:     4 [unused]
//   int _StreamRenderingEnabled;       // Offset:    4 Size:     4 [unused]
//   float _SimulationTime;             // Offset:    8 Size:     4 [unused]
//   float _StreamMaximumGap;           // Offset:   12 Size:     4 [unused]
//   float _StreamMaximumLength;        // Offset:   16 Size:     4 [unused]
//   int _ParticleCapacity;             // Offset:   20 Size:     4
//   int _MaximumIngredients;           // Offset:   24 Size:     4 [unused]
//   int _IngredientCount;              // Offset:   28 Size:     4 [unused]
//   int _SpawnCount;                   // Offset:   32 Size:     4 [unused]
//   int _GridWidth;                    // Offset:   36 Size:     4
//   int _GridHeight;                   // Offset:   40 Size:     4
//   int _GridCellCount;                // Offset:   44 Size:     4 [unused]
//   int _BoundaryCount;                // Offset:   48 Size:     4 [unused]
//   int _VesselTriggerCount;           // Offset:   52 Size:     4 [unused]
//   int _AgitatorCount;                // Offset:   56 Size:     4 [unused]
//   int _TechniqueTargetVessel;        // Offset:   60 Size:     4 [unused]
//   int _TechniqueMask;                // Offset:   64 Size:     4 [unused]
//   int _TechniqueStateMask;           // Offset:   68 Size:     4 [unused]
//   int _TransformTargetVessel;        // Offset:   72 Size:     4 [unused]
//   int _SuspensionTargetVessel;       // Offset:   76 Size:     4 [unused]
//   int _SuspensionEnabled;            // Offset:   80 Size:     4 [unused]
//   int _ReferenceSolverEnabled;       // Offset:   84 Size:     4 [unused]
//   int _ImprovedPhysics;              // Offset:   88 Size:     4 [unused]
//   int _TransferTargetVessel;         // Offset:   92 Size:     4 [unused]
//   float _ReferenceParticleVolume;    // Offset:   96 Size:     4
//   float _ReferenceRestDensity;       // Offset:  100 Size:     4 [unused]
//   float _ReferencePressureStiffness; // Offset:  104 Size:     4 [unused]
//   float _ReferenceNearPressureStiffness;// Offset:  108 Size:     4 [unused]
//   float _ReferenceViscosityRate;     // Offset:  112 Size:     4
//   float _ReferenceMaximumTensionRatio;// Offset:  116 Size:     4 [unused]
//   float _ReferenceMaximumAcceleration;// Offset:  120 Size:     4
//   float _ReferenceMaximumDisplacementRatio;// Offset:  124 Size:     4
//   float _DeltaTime;                  // Offset:  128 Size:     4 [unused]
//   float _ParticleRadius;             // Offset:  132 Size:     4
//   float _SmoothingRadius;            // Offset:  136 Size:     4
//   float _RestDensity;                // Offset:  140 Size:     4 [unused]
//   float _DensityCompliance;          // Offset:  144 Size:     4 [unused]
//   float _LambdaEpsilon;              // Offset:  148 Size:     4 [unused]
//   float _ArtificialPressureStrength; // Offset:  152 Size:     4 [unused]
//   float _ArtificialPressureRadiusRatio;// Offset:  156 Size:     4 [unused]
//   float _BoundaryDensityScale;       // Offset:  160 Size:     4 [unused]
//   float _WallFriction;               // Offset:  164 Size:     4 [unused]
//   float _WallRestitution;            // Offset:  168 Size:     4 [unused]
//   float _SplashTransfer;             // Offset:  172 Size:     4 [unused]
//   float _SplashMinimumImpactSpeed;   // Offset:  176 Size:     4 [unused]
//   float _BottomImpactSpread;         // Offset:  180 Size:     4 [unused]
//   float _VelocityDamping;            // Offset:  184 Size:     4 [unused]
//   float _MaximumSpeed;               // Offset:  188 Size:     4 [unused]
//   float _ClosedVesselDampingRate;    // Offset:  192 Size:     4 [unused]
//   float _ClosedVesselMaximumRelativeSpeed;// Offset:  196 Size:     4 [unused]
//   float _Viscosity;                  // Offset:  200 Size:     4 [unused]
//   float _PassiveMixRate;             // Offset:  204 Size:     4 [unused]
//   float _AgitationMixRate;           // Offset:  208 Size:     4 [unused]
//   float _FullMixRelativeSpeed;       // Offset:  212 Size:     4 [unused]
//   float _MaximumMixPerSubstep;       // Offset:  216 Size:     4 [unused]
//   float _MinimumVisibleAlpha;        // Offset:  220 Size:     4 [unused]
//   float2 _Gravity;                   // Offset:  224 Size:     8 [unused]
//   float2 _GridOrigin;                // Offset:  232 Size:     8
//   float2 _WorldMin;                  // Offset:  240 Size:     8 [unused]
//   float2 _WorldMax;                  // Offset:  248 Size:     8 [unused]
//   float2 _TransformDelta;            // Offset:  256 Size:     8 [unused]
//   int _SwapA;                        // Offset:  264 Size:     4 [unused]
//   int _SwapB;                        // Offset:  268 Size:     4 [unused]
//   float2 _SwapDeltaA;                // Offset:  272 Size:     8 [unused]
//   float2 _SwapDeltaB;                // Offset:  280 Size:     8 [unused]
//   int _BoundaryGroupCount;           // Offset:  288 Size:     4 [unused]
//   int _ImprovedVesselCount;          // Offset:  292 Size:     4 [unused]
//   float _ImprovedAreaPerMl;          // Offset:  296 Size:     4 [unused]
//   float _ImprovedKernelRatio;        // Offset:  300 Size:     4 [unused]
//   float _ImprovedCompliance;         // Offset:  304 Size:     4 [unused]
//   float _ImprovedCorrectionRatio;    // Offset:  308 Size:     4 [unused]
//   float _ImprovedWallDensity;        // Offset:  312 Size:     4 [unused]
//   float _ImprovedShear;              // Offset:  316 Size:     4 [unused]
//   float _ImprovedTension;            // Offset:  320 Size:     4 [unused]
//   float _ImprovedWetting;            // Offset:  324 Size:     4 [unused]
//
// }
//
// Resource bind info for _Particles
// {
//
//   struct LiquidParticle
//   {
//       
//       float2 position;               // Offset:    0
//       float2 previousPosition;       // Offset:    8
//       float2 velocity;               // Offset:   16
//       float volumeMl;                // Offset:   24
//       float temperatureC;            // Offset:   28
//       uint vesselId;                 // Offset:   32
//       uint techniqueFlags;           // Offset:   36
//       uint stateFlags;               // Offset:   40
//       uint active;                   // Offset:   44
//       uint padding;                  // Offset:   48
//
//   } $Element;                        // Offset:    0 Size:    52
//
// }
//
// Resource bind info for _PositionDeltas
// {
//
//   float2 $Element;                   // Offset:    0 Size:     8
//
// }
//
// Resource bind info for _VelocitySnapshot
// {
//
//   float2 $Element;                   // Offset:    0 Size:     8
//
// }
//
// Resource bind info for _ReferenceDensityPressure
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
// Resource bind info for _GridHeads
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
// Resource bind info for _GridNext
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
// Resource bind info for _StreamParticles
// {
//
//   struct StreamParticle
//   {
//       
//       uint token;                    // Offset:    0
//       uint previousToken;            // Offset:    4
//       uint streamId;                 // Offset:    8
//       uint sourceId;                 // Offset:   12
//       float delay;                   // Offset:   16
//       float stepDt;                  // Offset:   20
//       float startFraction;           // Offset:   24
//       float birthTime;               // Offset:   28
//       float radius;                  // Offset:   32
//       uint detached;                 // Offset:   36
//       uint pending;                  // Offset:   40
//       uint padding;                  // Offset:   44
//
//   } $Element;                        // Offset:    0 Size:    48
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// _Particles                            UAV  struct         r/w             u0      1 
// _PositionDeltas                       UAV  struct         r/w             u1      1 
// _VelocitySnapshot                     UAV  struct         r/w             u2      1 
// _ReferenceDensityPressure             UAV  struct         r/w             u3      1 
// _GridHeads                            UAV  struct         r/w             u4      1 
// _GridNext                             UAV  struct         r/w             u5      1 
// _StreamParticles                      UAV  struct         r/w             u6      1 
// $Globals                          cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[15], immediateIndexed
dcl_uav_structured u0, 52
dcl_uav_structured u1, 8
dcl_uav_structured u2, 8
dcl_uav_structured u3, 16
dcl_uav_structured u4, 4
dcl_uav_structured u5, 4
dcl_uav_structured u6, 48
dcl_input vThreadID.x
dcl_temps 12
dcl_thread_group 64, 1, 1
uge r0.x, vThreadID.x, cb0[1].y
if_nz r0.x
  ret 
endif 
ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r0.xy, vThreadID.x, l(0), u0.xyxx
ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r0.z, vThreadID.x, l(24), u0.xxxx
ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r0.w, vThreadID.x, l(32), u0.xxxx
ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r1.xy, vThreadID.x, l(40), u0.xyxx
ine r1.y, r1.y, l(0)
and r1.x, r1.x, l(4)
ieq r1.x, r1.x, l(0)
and r1.x, r1.x, r1.y
ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r1.y, vThreadID.x, l(20), u6.xxxx
lt r1.y, l(0.000001), r1.y
and r1.x, r1.y, r1.x
if_z r1.x
  store_structured u1.xy, vThreadID.x, l(0), l(0,0,0,0)
  ret 
endif 
ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r1.x, vThreadID.x, l(20), u6.xxxx
max r1.y, cb0[6].x, l(0.001000)
div r0.z, r0.z, r1.y
max r0.z, r0.z, l(0.000001)
ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r2.xyz, vThreadID.x, l(0), u3.xyzx
ld_structured_indexable(structured_buffer, stride=8)(mixed,mixed,mixed,mixed) r1.zw, vThreadID.x, l(0), u2.xxxy
add r3.xy, r0.xyxx, -cb0[14].zwzz
div r3.xy, r3.xyxx, cb0[8].zzzz
round_ni r3.xy, r3.xyxx
ftoi r3.xy, r3.xyxx
mul r2.w, cb0[8].y, l(0.050000)
max r2.w, r2.w, l(0.000100)
mov r3.zw, l(0,0,0,0)
mov r4.xy, l(0,0,0,0)
mov r4.zw, cb0[2].yyyz
mov r5.y, l(-1)
loop 
  ilt r5.z, l(1), r5.y
  breakc_nz r5.z
  mov r5.zw, r3.zzzw
  mov r6.xy, r4.xyxx
  mov r5.x, l(-1)
  loop 
    ilt r6.z, l(1), r5.x
    breakc_nz r6.z
    iadd r6.zw, r3.xxxy, r5.xxxy
    ige r7.xy, r6.zwzz, l(0, 0, 0, 0)
    and r7.x, r7.y, r7.x
    ilt r7.y, r6.z, r4.z
    and r7.x, r7.y, r7.x
    ilt r7.y, r6.w, r4.w
    and r7.x, r7.y, r7.x
    if_z r7.x
      iadd r7.x, r5.x, l(1)
      mov r5.x, r7.x
      continue 
    endif 
    imad r6.z, r6.w, r4.z, r6.z
    ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r6.z, r6.z, l(0), u4.xxxx
    mov r7.xy, r5.zwzz
    mov r7.zw, r6.xxxy
    mov r6.w, r6.z
    mov r8.x, l(0)
    loop 
      ige r8.y, r6.w, l(0)
      ilt r8.z, r8.x, cb0[1].y
      and r8.y, r8.z, r8.y
      breakc_z r8.y
      iadd r8.x, r8.x, l(1)
      ine r8.y, r6.w, vThreadID.x
      if_nz r8.y
        ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r8.yz, r6.w, l(0), u0.xxyx
        ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r8.w, r6.w, l(24), u0.xxxx
        ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r9.x, r6.w, l(32), u0.xxxx
        ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r9.yz, r6.w, l(40), u0.xxyx
        ine r9.z, r9.z, l(0)
        and r9.y, r9.y, l(4)
        ieq r9.y, r9.y, l(0)
        and r9.y, r9.y, r9.z
        ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r9.z, r6.w, l(20), u6.xxxx
        lt r9.w, l(0.000001), r9.z
        and r9.y, r9.w, r9.y
        ieq r9.x, r0.w, r9.x
        and r9.x, r9.x, r9.y
        if_nz r9.x
          add r8.yz, r0.xxyx, -r8.yyzy
          dp2 r9.x, r8.yzyy, r8.yzyy
          sqrt r9.y, r9.x
          lt r9.w, r9.y, cb0[8].z
          if_nz r9.w
            ge r9.x, l(0.000000), r9.x
            umin r9.w, r6.w, vThreadID.x
            umax r10.x, r6.w, vThreadID.x
            imul null, r10.x, r10.x, l(0xac564b05)
            imad r10.x, r9.w, l(0x2c9277b5), r10.x
            and r10.x, r10.x, l(1023)
            utof r10.x, r10.x
            mul r10.x, r10.x, l(0.006136)
            sincos r10.x, r11.x, r10.x
            ieq r9.w, r9.w, vThreadID.x
            movc r9.w, r9.w, l(1.000000), l(-1.000000)
            mov r11.y, r10.x
            mul r10.xy, r9.wwww, r11.xyxx
            mul r10.xy, r2.wwww, r10.xyxx
            movc r8.yz, r9.xxxx, r10.xxyx, r8.yyzy
            dp2 r9.x, r8.yzyy, r8.yzyy
            rsq r9.x, r9.x
            mul r8.yz, r8.yyzy, r9.xxxx
            div r9.x, r9.y, cb0[8].z
            add r9.x, -r9.x, l(1.000000)
            div r8.w, r8.w, r1.y
            max r8.w, r8.w, l(0.000001)
            ld_structured_indexable(structured_buffer, stride=16)(mixed,mixed,mixed,mixed) r10.xyz, r6.w, l(0), u3.xyzx
            min r9.y, r1.x, r9.z
            add r9.zw, r2.xxxy, r10.xxxy
            mul r10.x, r9.x, r9.x
            mul r9.zw, r9.zzzw, r10.xxxx
            mad r9.z, r9.w, r9.x, r9.z
            mul r9.zw, r8.yyyz, r9.zzzz
            mul r9.zw, r8.wwww, r9.zzzw
            div r10.x, r9.y, r1.x
            mad r7.xy, r9.zwzz, r10.xxxx, r7.xyxx
            ld_structured_indexable(structured_buffer, stride=8)(mixed,mixed,mixed,mixed) r9.zw, r6.w, l(0), u2.xxxy
            add r9.zw, r1.zzzw, -r9.zzzw
            dp2 r9.z, r9.zwzz, r8.yzyy
            max r9.z, -r9.z, l(0.000000)
            max r9.w, r2.z, r10.z
            max r9.w, r9.w, l(1.000000)
            mul r9.y, r9.y, -cb0[7].x
            mul r9.y, r9.y, l(1.442695)
            exp r9.y, r9.y
            add r9.y, -r9.y, l(1.000000)
            add r10.x, r0.z, r8.w
            div r8.w, r8.w, r10.x
            mul r8.yz, r8.yyzy, r9.zzzz
            mul r8.yz, r9.xxxx, r8.yyzy
            mul r8.yz, r9.yyyy, r8.yyzy
            mul r8.yz, r8.wwww, r8.yyzy
            div r8.yz, r8.yyzy, r9.wwww
            add r7.zw, r7.zzzw, r8.yyyz
          endif 
        endif 
      endif 
      ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r6.w, r6.w, l(0), u5.xxxx
    endloop 
    mov r5.zw, r7.xxxy
    mov r6.xy, r7.zwzz
    iadd r5.x, r5.x, l(1)
  endloop 
  mov r3.zw, r5.zzzw
  mov r4.xy, r6.xyxx
  iadd r5.y, r5.y, l(1)
endloop 
dp2 r0.x, r3.zwzz, r3.zwzz
sqrt r0.x, r0.x
lt r0.y, cb0[7].z, r0.x
div r0.x, cb0[7].z, r0.x
mul r0.xz, r0.xxxx, r3.zzwz
movc r0.xy, r0.yyyy, r0.xzxx, r3.zwzz
mul r0.z, r1.x, r1.x
mul r1.xy, r1.xxxx, r4.xyxx
mad r0.xy, r0.zzzz, r0.xyxx, r1.xyxx
mul r0.z, cb0[7].w, cb0[8].y
dp2 r0.w, r0.xyxx, r0.xyxx
sqrt r0.w, r0.w
lt r1.x, r0.z, r0.w
div r0.z, r0.z, r0.w
mul r0.zw, r0.zzzz, r0.xxxy
movc r0.xy, r1.xxxx, r0.zwzz, r0.xyxx
and r0.zw, r0.xxxy, l(0, 0, 0x7f800000, 0x7f800000)
ine r0.zw, r0.zzzw, l(0, 0, 0x7f800000, 0x7f800000)
and r0.z, r0.w, r0.z
and r0.xy, r0.xyxx, r0.zzzz
store_structured u1.xy, vThreadID.x, l(0), r0.xyxx
ret 
// Approximately 174 instruction slots used
