//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer $Globals
// {
//
//   int _StreamHeadCount;              // Offset:    0 Size:     4 [unused]
//   int _StreamRenderingEnabled;       // Offset:    4 Size:     4 [unused]
//   float _SimulationTime;             // Offset:    8 Size:     4 [unused]
//   float _StreamMaximumGap;           // Offset:   12 Size:     4 [unused]
//   float _StreamMaximumLength;        // Offset:   16 Size:     4 [unused]
//   int _ParticleCapacity;             // Offset:   20 Size:     4
//   int _MaximumIngredients;           // Offset:   24 Size:     4 [unused]
//   int _IngredientCount;              // Offset:   28 Size:     4 [unused]
//   int _SpawnCount;                   // Offset:   32 Size:     4 [unused]
//   int _GridWidth;                    // Offset:   36 Size:     4 [unused]
//   int _GridHeight;                   // Offset:   40 Size:     4 [unused]
//   int _GridCellCount;                // Offset:   44 Size:     4 [unused]
//   int _BoundaryCount;                // Offset:   48 Size:     4 [unused]
//   int _VesselTriggerCount;           // Offset:   52 Size:     4 [unused]
//   int _AgitatorCount;                // Offset:   56 Size:     4
//   int _TechniqueTargetVessel;        // Offset:   60 Size:     4 [unused]
//   int _TechniqueMask;                // Offset:   64 Size:     4 [unused]
//   int _TechniqueStateMask;           // Offset:   68 Size:     4 [unused]
//   int _TransformTargetVessel;        // Offset:   72 Size:     4 [unused]
//   int _SuspensionTargetVessel;       // Offset:   76 Size:     4 [unused]
//   int _SuspensionEnabled;            // Offset:   80 Size:     4 [unused]
//   int _ReferenceSolverEnabled;       // Offset:   84 Size:     4 [unused]
//   int _ImprovedPhysics;              // Offset:   88 Size:     4 [unused]
//   int _TransferTargetVessel;         // Offset:   92 Size:     4 [unused]
//   float _ReferenceParticleVolume;    // Offset:   96 Size:     4 [unused]
//   float _ReferenceRestDensity;       // Offset:  100 Size:     4 [unused]
//   float _ReferencePressureStiffness; // Offset:  104 Size:     4 [unused]
//   float _ReferenceNearPressureStiffness;// Offset:  108 Size:     4 [unused]
//   float _ReferenceViscosityRate;     // Offset:  112 Size:     4 [unused]
//   float _ReferenceMaximumTensionRatio;// Offset:  116 Size:     4 [unused]
//   float _ReferenceMaximumAcceleration;// Offset:  120 Size:     4 [unused]
//   float _ReferenceMaximumDisplacementRatio;// Offset:  124 Size:     4 [unused]
//   float _DeltaTime;                  // Offset:  128 Size:     4
//   float _ParticleRadius;             // Offset:  132 Size:     4 [unused]
//   float _SmoothingRadius;            // Offset:  136 Size:     4
//   float _RestDensity;                // Offset:  140 Size:     4 [unused]
//   float _DensityCompliance;          // Offset:  144 Size:     4 [unused]
//   float _LambdaEpsilon;              // Offset:  148 Size:     4 [unused]
//   float _ArtificialPressureStrength; // Offset:  152 Size:     4 [unused]
//   float _ArtificialPressureRadiusRatio;// Offset:  156 Size:     4 [unused]
//   float _BoundaryDensityScale;       // Offset:  160 Size:     4 [unused]
//   float _WallFriction;               // Offset:  164 Size:     4 [unused]
//   float _WallRestitution;            // Offset:  168 Size:     4 [unused]
//   float _SplashTransfer;             // Offset:  172 Size:     4 [unused]
//   float _SplashMinimumImpactSpeed;   // Offset:  176 Size:     4 [unused]
//   float _BottomImpactSpread;         // Offset:  180 Size:     4 [unused]
//   float _VelocityDamping;            // Offset:  184 Size:     4 [unused]
//   float _MaximumSpeed;               // Offset:  188 Size:     4 [unused]
//   float _ClosedVesselDampingRate;    // Offset:  192 Size:     4 [unused]
//   float _ClosedVesselMaximumRelativeSpeed;// Offset:  196 Size:     4 [unused]
//   float _Viscosity;                  // Offset:  200 Size:     4 [unused]
//   float _PassiveMixRate;             // Offset:  204 Size:     4 [unused]
//   float _AgitationMixRate;           // Offset:  208 Size:     4 [unused]
//   float _FullMixRelativeSpeed;       // Offset:  212 Size:     4 [unused]
//   float _MaximumMixPerSubstep;       // Offset:  216 Size:     4 [unused]
//   float _MinimumVisibleAlpha;        // Offset:  220 Size:     4 [unused]
//   float2 _Gravity;                   // Offset:  224 Size:     8
//   float2 _GridOrigin;                // Offset:  232 Size:     8 [unused]
//   float2 _WorldMin;                  // Offset:  240 Size:     8 [unused]
//   float2 _WorldMax;                  // Offset:  248 Size:     8 [unused]
//   float2 _TransformDelta;            // Offset:  256 Size:     8 [unused]
//   int _SwapA;                        // Offset:  264 Size:     4 [unused]
//   int _SwapB;                        // Offset:  268 Size:     4 [unused]
//   float2 _SwapDeltaA;                // Offset:  272 Size:     8 [unused]
//   float2 _SwapDeltaB;                // Offset:  280 Size:     8 [unused]
//   int _BoundaryGroupCount;           // Offset:  288 Size:     4 [unused]
//   int _ImprovedVesselCount;          // Offset:  292 Size:     4 [unused]
//   float _ImprovedAreaPerMl;          // Offset:  296 Size:     4 [unused]
//   float _ImprovedKernelRatio;        // Offset:  300 Size:     4 [unused]
//   float _ImprovedCompliance;         // Offset:  304 Size:     4 [unused]
//   float _ImprovedCorrectionRatio;    // Offset:  308 Size:     4 [unused]
//   float _ImprovedWallDensity;        // Offset:  312 Size:     4 [unused]
//   float _ImprovedShear;              // Offset:  316 Size:     4 [unused]
//   float _ImprovedTension;            // Offset:  320 Size:     4 [unused]
//   float _ImprovedWetting;            // Offset:  324 Size:     4 [unused]
//
// }
//
// Resource bind info for _Agitators
// {
//
//   struct Agitator
//   {
//       
//       float2 a;                      // Offset:    0
//       float2 b;                      // Offset:    8
//       float2 velocity;               // Offset:   16
//       float radius;                  // Offset:   24
//       float strength;                // Offset:   28
//       uint vesselId;                 // Offset:   32
//       uint active;                   // Offset:   36
//
//   } $Element;                        // Offset:    0 Size:    40
//
// }
//
// Resource bind info for _Particles
// {
//
//   struct LiquidParticle
//   {
//       
//       float2 position;               // Offset:    0
//       float2 previousPosition;       // Offset:    8
//       float2 velocity;               // Offset:   16
//       float volumeMl;                // Offset:   24
//       float temperatureC;            // Offset:   28
//       uint vesselId;                 // Offset:   32
//       uint techniqueFlags;           // Offset:   36
//       uint stateFlags;               // Offset:   40
//       uint active;                   // Offset:   44
//       uint padding;                  // Offset:   48
//
//   } $Element;                        // Offset:    0 Size:    52
//
// }
//
// Resource bind info for _StreamParticles
// {
//
//   struct StreamParticle
//   {
//       
//       uint token;                    // Offset:    0
//       uint previousToken;            // Offset:    4
//       uint streamId;                 // Offset:    8
//       uint sourceId;                 // Offset:   12
//       float delay;                   // Offset:   16
//       float stepDt;                  // Offset:   20
//       float startFraction;           // Offset:   24
//       float birthTime;               // Offset:   28
//       float radius;                  // Offset:   32
//       uint detached;                 // Offset:   36
//       uint pending;                  // Offset:   40
//       uint padding;                  // Offset:   44
//
//   } $Element;                        // Offset:    0 Size:    48
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// _Agitators                        texture  struct         r/o             t0      1 
// _Particles                            UAV  struct         r/w             u0      1 
// _StreamParticles                      UAV  struct         r/w             u1      1 
// $Globals                          cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[15], immediateIndexed
dcl_resource_structured t0, 40
dcl_uav_structured u0, 52
dcl_uav_structured u1, 48
dcl_input vThreadID.x
dcl_temps 6
dcl_thread_group 64, 1, 1
uge r0.x, vThreadID.x, cb0[1].y
if_nz r0.x
  ret 
endif 
ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r0.zw, vThreadID.x, l(0), u0.xxxy
ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r1.xy, vThreadID.x, l(16), u0.xyxx
ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r1.z, vThreadID.x, l(32), u0.xxxx
ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r2.xy, vThreadID.x, l(40), u0.yxxx
ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r3.x, vThreadID.x, l(16), u1.xxxx
ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r1.w, vThreadID.x, l(40), u1.xxxx
if_nz r1.w
  add r1.w, -r3.x, cb0[8].x
  max r4.x, r1.w, l(0.000000)
  add r1.w, r3.x, -cb0[8].x
  max r4.y, r1.w, l(0.000000)
  div r1.w, r4.x, cb0[8].x
  add r4.z, -r1.w, l(1.000000)
  lt r1.w, l(0.000000), r4.y
  if_nz r1.w
    store_structured u1.xyz, vThreadID.x, l(16), r4.yxzy
    ret 
  endif 
  mov r3.xyz, r4.yxzy
  mov r2.x, l(1)
else 
  mov r3.y, cb0[8].x
  mov r3.z, l(0)
  mov r4.x, cb0[8].x
endif 
store_structured u1.xyz, vThreadID.x, l(16), r3.xyzx
store_structured u1.x, vThreadID.x, l(40), l(0)
store_structured u0.x, vThreadID.x, l(44), r2.x
ge r1.w, l(0.000001), r4.x
ieq r2.x, r2.x, l(0)
or r1.w, r1.w, r2.x
and r2.x, r2.y, l(4)
ine r2.x, r2.x, l(0)
or r1.w, r1.w, r2.x
if_nz r1.w
  ret 
endif 
mad r1.xy, cb0[14].xyxx, r4.xxxx, r1.xyxx
ine r1.w, r1.z, l(0)
mov r2.xy, r1.xyxx
mov r2.z, l(0)
loop 
  ige r2.w, r2.z, cb0[3].z
  breakc_nz r2.w
  ld_structured_indexable(structured_buffer, stride=40)(mixed,mixed,mixed,mixed) r3.xy, r2.z, l(32), t0.xyxx
  if_z r3.y
    iadd r2.w, r2.z, l(1)
    mov r2.z, r2.w
    continue 
  endif 
  ine r2.w, r3.x, l(0)
  and r2.w, r1.w, r2.w
  ine r3.x, r1.z, r3.x
  and r2.w, r2.w, r3.x
  if_nz r2.w
    iadd r2.w, r2.z, l(1)
    mov r2.z, r2.w
    continue 
  endif 
  ld_structured_indexable(structured_buffer, stride=40)(mixed,mixed,mixed,mixed) r3.xyzw, r2.z, l(0), t0.xyzw
  ld_structured_indexable(structured_buffer, stride=40)(mixed,mixed,mixed,mixed) r5.xyzw, r2.z, l(16), t0.xyzw
  add r3.zw, -r3.xxxy, r3.zzzw
  dp2 r2.w, r3.zwzz, r3.zwzz
  lt r4.y, l(0.000000), r2.w
  add r4.zw, r0.zzzw, -r3.xxxy
  dp2 r4.z, r4.zwzz, r3.zwzz
  div_sat r2.w, r4.z, r2.w
  and r2.w, r2.w, r4.y
  mad r3.xy, r3.zwzz, r2.wwww, r3.xyxx
  add r3.xy, r0.zwzz, -r3.xyxx
  dp2 r2.w, r3.xyxx, r3.xyxx
  sqrt r2.w, r2.w
  add r3.x, r5.z, cb0[8].z
  ge r3.y, r3.x, r2.w
  max r3.x, r3.x, l(0.000010)
  div r2.w, r2.w, r3.x
  add r2.w, -r2.w, l(1.000000)
  max r2.w, r2.w, l(0.000000)
  max r3.x, r5.w, l(0.000000)
  mul r3.x, r4.x, -r3.x
  mul r3.x, r3.x, l(1.442695)
  exp r3.x, r3.x
  add r3.x, -r3.x, l(1.000000)
  add r3.zw, -r2.xxxy, r5.xxxy
  mul r3.zw, r2.wwww, r3.zzzw
  mad r3.xz, r3.zzwz, r3.xxxx, r2.xxyx
  movc r2.xy, r3.yyyy, r3.xzxx, r2.xyxx
  iadd r2.z, r2.z, l(1)
endloop 
mad r0.xy, r2.xyxx, r4.xxxx, r0.zwzz
store_structured u0.xyzw, vThreadID.x, l(0), r0.xyzw
store_structured u0.xy, vThreadID.x, l(16), r2.xyxx
ret 
// Approximately 97 instruction slots used
