//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer $Globals
// {
//
//   int _StreamHeadCount;              // Offset:    0 Size:     4 [unused]
//   int _StreamRenderingEnabled;       // Offset:    4 Size:     4 [unused]
//   float _SimulationTime;             // Offset:    8 Size:     4 [unused]
//   float _StreamMaximumGap;           // Offset:   12 Size:     4 [unused]
//   float _StreamMaximumLength;        // Offset:   16 Size:     4 [unused]
//   int _ParticleCapacity;             // Offset:   20 Size:     4
//   int _MaximumIngredients;           // Offset:   24 Size:     4 [unused]
//   int _IngredientCount;              // Offset:   28 Size:     4 [unused]
//   int _SpawnCount;                   // Offset:   32 Size:     4 [unused]
//   int _GridWidth;                    // Offset:   36 Size:     4
//   int _GridHeight;                   // Offset:   40 Size:     4
//   int _GridCellCount;                // Offset:   44 Size:     4 [unused]
//   int _BoundaryCount;                // Offset:   48 Size:     4 [unused]
//   int _VesselTriggerCount;           // Offset:   52 Size:     4 [unused]
//   int _AgitatorCount;                // Offset:   56 Size:     4 [unused]
//   int _TechniqueTargetVessel;        // Offset:   60 Size:     4 [unused]
//   int _TechniqueMask;                // Offset:   64 Size:     4 [unused]
//   int _TechniqueStateMask;           // Offset:   68 Size:     4 [unused]
//   int _TransformTargetVessel;        // Offset:   72 Size:     4 [unused]
//   int _SuspensionTargetVessel;       // Offset:   76 Size:     4 [unused]
//   int _SuspensionEnabled;            // Offset:   80 Size:     4 [unused]
//   int _ReferenceSolverEnabled;       // Offset:   84 Size:     4 [unused]
//   int _ImprovedPhysics;              // Offset:   88 Size:     4 [unused]
//   int _TransferTargetVessel;         // Offset:   92 Size:     4 [unused]
//   float _ReferenceParticleVolume;    // Offset:   96 Size:     4 [unused]
//   float _ReferenceRestDensity;       // Offset:  100 Size:     4 [unused]
//   float _ReferencePressureStiffness; // Offset:  104 Size:     4 [unused]
//   float _ReferenceNearPressureStiffness;// Offset:  108 Size:     4 [unused]
//   float _ReferenceViscosityRate;     // Offset:  112 Size:     4 [unused]
//   float _ReferenceMaximumTensionRatio;// Offset:  116 Size:     4 [unused]
//   float _ReferenceMaximumAcceleration;// Offset:  120 Size:     4 [unused]
//   float _ReferenceMaximumDisplacementRatio;// Offset:  124 Size:     4 [unused]
//   float _DeltaTime;                  // Offset:  128 Size:     4 [unused]
//   float _ParticleRadius;             // Offset:  132 Size:     4
//   float _SmoothingRadius;            // Offset:  136 Size:     4
//   float _RestDensity;                // Offset:  140 Size:     4 [unused]
//   float _DensityCompliance;          // Offset:  144 Size:     4 [unused]
//   float _LambdaEpsilon;              // Offset:  148 Size:     4 [unused]
//   float _ArtificialPressureStrength; // Offset:  152 Size:     4 [unused]
//   float _ArtificialPressureRadiusRatio;// Offset:  156 Size:     4 [unused]
//   float _BoundaryDensityScale;       // Offset:  160 Size:     4 [unused]
//   float _WallFriction;               // Offset:  164 Size:     4 [unused]
//   float _WallRestitution;            // Offset:  168 Size:     4 [unused]
//   float _SplashTransfer;             // Offset:  172 Size:     4 [unused]
//   float _SplashMinimumImpactSpeed;   // Offset:  176 Size:     4 [unused]
//   float _BottomImpactSpread;         // Offset:  180 Size:     4 [unused]
//   float _VelocityDamping;            // Offset:  184 Size:     4 [unused]
//   float _MaximumSpeed;               // Offset:  188 Size:     4 [unused]
//   float _ClosedVesselDampingRate;    // Offset:  192 Size:     4 [unused]
//   float _ClosedVesselMaximumRelativeSpeed;// Offset:  196 Size:     4 [unused]
//   float _Viscosity;                  // Offset:  200 Size:     4 [unused]
//   float _PassiveMixRate;             // Offset:  204 Size:     4 [unused]
//   float _AgitationMixRate;           // Offset:  208 Size:     4 [unused]
//   float _FullMixRelativeSpeed;       // Offset:  212 Size:     4 [unused]
//   float _MaximumMixPerSubstep;       // Offset:  216 Size:     4 [unused]
//   float _MinimumVisibleAlpha;        // Offset:  220 Size:     4 [unused]
//   float2 _Gravity;                   // Offset:  224 Size:     8 [unused]
//   float2 _GridOrigin;                // Offset:  232 Size:     8
//   float2 _WorldMin;                  // Offset:  240 Size:     8 [unused]
//   float2 _WorldMax;                  // Offset:  248 Size:     8 [unused]
//   float2 _TransformDelta;            // Offset:  256 Size:     8 [unused]
//   int _SwapA;                        // Offset:  264 Size:     4 [unused]
//   int _SwapB;                        // Offset:  268 Size:     4 [unused]
//   float2 _SwapDeltaA;                // Offset:  272 Size:     8 [unused]
//   float2 _SwapDeltaB;                // Offset:  280 Size:     8 [unused]
//   int _BoundaryGroupCount;           // Offset:  288 Size:     4
//   int _ImprovedVesselCount;          // Offset:  292 Size:     4 [unused]
//   float _ImprovedAreaPerMl;          // Offset:  296 Size:     4 [unused]
//   float _ImprovedKernelRatio;        // Offset:  300 Size:     4 [unused]
//   float _ImprovedCompliance;         // Offset:  304 Size:     4 [unused]
//   float _ImprovedCorrectionRatio;    // Offset:  308 Size:     4 [unused]
//   float _ImprovedWallDensity;        // Offset:  312 Size:     4 [unused]
//   float _ImprovedShear;              // Offset:  316 Size:     4 [unused]
//   float _ImprovedTension;            // Offset:  320 Size:     4 [unused]
//   float _ImprovedWetting;            // Offset:  324 Size:     4 [unused]
//
// }
//
// Resource bind info for _Boundaries
// {
//
//   struct BoundarySegment
//   {
//       
//       float2 a;                      // Offset:    0
//       float2 b;                      // Offset:    8
//       float2 velocityA;              // Offset:   16
//       float2 velocityB;              // Offset:   24
//       uint vesselId;                 // Offset:   32
//       uint flags;                    // Offset:   36
//       float2 localA;                 // Offset:   40
//       float2 localB;                 // Offset:   48
//       float2 startPosition;          // Offset:   56
//       float2 endPosition;            // Offset:   64
//       float startAngle;              // Offset:   72
//       float angleDelta;              // Offset:   76
//
//   } $Element;                        // Offset:    0 Size:    80
//
// }
//
// Resource bind info for _BoundaryGroups
// {
//
//   struct BoundaryGroup
//   {
//       
//       float2 minPosition;            // Offset:    0
//       float2 maxPosition;            // Offset:    8
//       float2 sweptMin;               // Offset:   16
//       float2 sweptMax;               // Offset:   24
//       uint first;                    // Offset:   32
//       uint end;                      // Offset:   36
//       uint contourFirst;             // Offset:   40
//       uint contourEnd;               // Offset:   44
//       uint vesselId;                 // Offset:   48
//
//   } $Element;                        // Offset:    0 Size:    52
//
// }
//
// Resource bind info for _Particles
// {
//
//   struct LiquidParticle
//   {
//       
//       float2 position;               // Offset:    0
//       float2 previousPosition;       // Offset:    8
//       float2 velocity;               // Offset:   16
//       float volumeMl;                // Offset:   24
//       float temperatureC;            // Offset:   28
//       uint vesselId;                 // Offset:   32
//       uint techniqueFlags;           // Offset:   36
//       uint stateFlags;               // Offset:   40
//       uint active;                   // Offset:   44
//       uint padding;                  // Offset:   48
//
//   } $Element;                        // Offset:    0 Size:    52
//
// }
//
// Resource bind info for _GridHeads
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
// Resource bind info for _GridNext
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
// Resource bind info for _StreamParticles
// {
//
//   struct StreamParticle
//   {
//       
//       uint token;                    // Offset:    0
//       uint previousToken;            // Offset:    4
//       uint streamId;                 // Offset:    8
//       uint sourceId;                 // Offset:   12
//       float delay;                   // Offset:   16
//       float stepDt;                  // Offset:   20
//       float startFraction;           // Offset:   24
//       float birthTime;               // Offset:   28
//       float radius;                  // Offset:   32
//       uint detached;                 // Offset:   36
//       uint pending;                  // Offset:   40
//       uint padding;                  // Offset:   44
//
//   } $Element;                        // Offset:    0 Size:    48
//
// }
//
// Resource bind info for _StreamContactSnapshot
// {
//
//   uint $Element;                     // Offset:    0 Size:     4
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// _Boundaries                       texture  struct         r/o             t0      1 
// _BoundaryGroups                   texture  struct         r/o             t1      1 
// _Particles                            UAV  struct         r/w             u0      1 
// _GridHeads                            UAV  struct         r/w             u1      1 
// _GridNext                             UAV  struct         r/w             u2      1 
// _StreamParticles                      UAV  struct         r/w             u3      1 
// _StreamContactSnapshot                UAV  struct         r/w             u4      1 
// $Globals                          cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[19], immediateIndexed
dcl_resource_structured t0, 80
dcl_resource_structured t1, 52
dcl_uav_structured u0, 52
dcl_uav_structured u1, 4
dcl_uav_structured u2, 4
dcl_uav_structured u3, 48
dcl_uav_structured u4, 4
dcl_input vThreadID.x
dcl_temps 9
dcl_thread_group 64, 1, 1
uge r0.x, vThreadID.x, cb0[1].y
if_nz r0.x
  ret 
endif 
ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r0.xy, vThreadID.x, l(0), u0.xyxx
ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r0.z, vThreadID.x, l(32), u0.xxxx
ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r1.xy, vThreadID.x, l(40), u0.xyxx
ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r0.w, vThreadID.x, l(0), u3.xxxx
ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r1.z, vThreadID.x, l(20), u3.xxxx
ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r1.w, vThreadID.x, l(36), u3.xxxx
ieq r1.y, r1.y, l(0)
ieq r2.x, r0.z, l(0)
or r1.y, r1.y, r2.x
ieq r0.w, r0.w, l(0)
or r0.w, r0.w, r1.y
ine r1.y, r1.w, l(0)
or r0.w, r0.w, r1.y
ge r1.y, l(0.000001), r1.z
or r0.w, r0.w, r1.y
and r1.x, r1.x, l(4)
ine r1.x, r1.x, l(0)
or r0.w, r0.w, r1.x
if_nz r0.w
  ret 
endif 
mul r0.w, cb0[8].y, l(2.200000)
min r0.w, r0.w, cb0[8].z
add r1.xy, r0.xyxx, -cb0[14].zwzz
div r1.xy, r1.xyxx, cb0[8].zzzz
round_ni r1.xy, r1.xyxx
ftoi r1.xy, r1.xyxx
mul r0.w, r0.w, r0.w
mov r1.zw, cb0[2].yyyz
mov r2.y, l(-1)
loop 
  ilt r2.z, l(1), r2.y
  breakc_nz r2.z
  mov r2.x, l(-1)
  loop 
    ilt r2.z, l(1), r2.x
    breakc_nz r2.z
    iadd r2.zw, r1.xxxy, r2.xxxy
    ige r3.xy, r2.zwzz, l(0, 0, 0, 0)
    and r3.x, r3.y, r3.x
    ilt r3.y, r2.z, r1.z
    and r3.x, r3.y, r3.x
    ilt r3.y, r2.w, r1.w
    and r3.x, r3.y, r3.x
    if_z r3.x
      iadd r3.x, r2.x, l(1)
      mov r2.x, r3.x
      continue 
    endif 
    imad r2.z, r2.w, r1.z, r2.z
    ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r2.z, r2.z, l(0), u1.xxxx
    mov r2.w, r2.z
    mov r3.x, l(0)
    loop 
      ige r3.y, r2.w, l(0)
      ilt r3.z, r3.x, cb0[1].y
      and r3.y, r3.z, r3.y
      breakc_z r3.y
      iadd r3.x, r3.x, l(1)
      ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r3.yz, r2.w, l(0), u0.xxyx
      ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r3.w, r2.w, l(32), u0.xxxx
      ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r4.xy, r2.w, l(40), u0.xyxx
      add r4.zw, r0.xxxy, -r3.yyyz
      ine r5.x, r2.w, vThreadID.x
      ine r4.y, r4.y, l(0)
      and r4.y, r4.y, r5.x
      ieq r3.w, r0.z, r3.w
      and r3.w, r3.w, r4.y
      and r4.x, r4.x, l(4)
      ieq r4.x, r4.x, l(0)
      and r3.w, r3.w, r4.x
      ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r4.x, r2.w, l(0), u3.xxxx
      ieq r4.x, r4.x, l(0)
      ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r4.y, r2.w, l(0), u4.xxxx
      ine r4.y, r4.y, l(0)
      or r4.x, r4.y, r4.x
      and r3.w, r3.w, r4.x
      dp2 r4.x, r4.zwzz, r4.zwzz
      ge r4.x, r0.w, r4.x
      and r3.w, r3.w, r4.x
      min r4.xy, r0.xyxx, r3.yzyy
      max r4.zw, r0.xxxy, r3.yyyz
      add r3.yz, -r0.yyxy, r3.zzyz
      mov r5.xyz, l(0,0,0,0)
      loop 
        ige r5.w, r5.y, cb0[18].x
        mov r5.z, l(0)
        breakc_nz r5.w
        ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r6.xyzw, r5.y, l(0), t1.xyzw
        ge r6.xy, r4.zwzz, r6.xyxx
        and r5.w, r6.y, r6.x
        ge r6.xy, r6.zwzz, r4.xyxx
        and r6.x, r6.y, r6.x
        and r5.w, r5.w, r6.x
        if_z r5.w
          iadd r5.w, r5.y, l(1)
          mov r5.z, l(0)
          mov r5.y, r5.w
          continue 
        endif 
        ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r6.xy, r5.y, l(32), t1.xyxx
        mov r5.w, r5.x
        mov r6.z, r6.x
        mov r6.w, l(0)
        loop 
          uge r7.x, r6.z, r6.y
          mov r6.w, l(0)
          breakc_nz r7.x
          ld_structured_indexable(structured_buffer, stride=80)(mixed,mixed,mixed,mixed) r7.x, r6.z, l(36), t0.xxxx
          and r7.x, r7.x, l(16)
          if_nz r7.x
            iadd r7.x, r6.z, l(1)
            mov r6.w, l(0)
            mov r6.z, r7.x
            continue 
          endif 
          ld_structured_indexable(structured_buffer, stride=80)(mixed,mixed,mixed,mixed) r7.xyzw, r6.z, l(0), t0.xyzw
          min r8.xy, r7.zwzz, r7.xyxx
          lt r8.xy, r4.zwzz, r8.xyxx
          or r8.x, r8.y, r8.x
          max r8.yz, r7.zzwz, r7.xxyx
          lt r8.yz, r8.yyzy, r4.xxyx
          or r8.y, r8.z, r8.y
          or r8.x, r8.y, r8.x
          if_nz r8.x
            iadd r8.x, r6.z, l(1)
            mov r6.w, l(0)
            mov r6.z, r8.x
            continue 
          endif 
          add r7.zw, -r7.yyyx, r7.wwwz
          mul r8.x, r3.y, r7.w
          mad r8.x, r3.z, r7.z, -r8.x
          lt r8.y, l(0.000000), |r8.x|
          if_nz r8.y
            add r7.xy, -r0.xyxx, r7.xyxx
            mul r7.w, r7.w, r7.y
            mad r7.z, r7.x, r7.z, -r7.w
            mul r7.y, r3.z, r7.y
            mad r7.x, r7.x, r3.y, -r7.y
            div r7.xz, r7.xxzx, r8.xxxx
            ge r7.y, r7.z, l(0.000000)
            ge r7.z, l(1.000000), r7.z
            and r7.y, r7.z, r7.y
            ge r7.z, r7.x, l(0.000000)
            and r7.y, r7.z, r7.y
            ge r7.x, l(1.000000), r7.x
            and r7.x, r7.x, r7.y
            if_nz r7.x
              mov r5.w, l(-1)
              mov r6.w, l(-1)
              break 
            endif 
            mov r6.w, r7.x
          else 
            mov r6.w, l(0)
          endif 
          iadd r6.z, r6.z, l(1)
        endloop 
        mov r5.x, r5.w
        mov r5.z, r6.w
        breakc_nz r6.w
        iadd r5.y, r5.y, l(1)
        mov r5.xy, r5.wyww
        mov r5.z, r6.w
      endloop 
      and r3.y, r5.x, r5.z
      not r3.y, r3.y
      and r3.y, r3.y, r3.w
      if_nz r3.y
        store_structured u3.x, vThreadID.x, l(36), l(2)
        ret 
      endif 
      ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r2.w, r2.w, l(0), u2.xxxx
    endloop 
    iadd r2.x, r2.x, l(1)
  endloop 
  iadd r2.y, r2.y, l(1)
endloop 
ret 
// Approximately 184 instruction slots used
