//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer $Globals
// {
//
//   int _StreamHeadCount;              // Offset:    0 Size:     4 [unused]
//   int _StreamRenderingEnabled;       // Offset:    4 Size:     4 [unused]
//   float _SimulationTime;             // Offset:    8 Size:     4 [unused]
//   float _StreamMaximumGap;           // Offset:   12 Size:     4 [unused]
//   float _StreamMaximumLength;        // Offset:   16 Size:     4 [unused]
//   int _ParticleCapacity;             // Offset:   20 Size:     4
//   int _MaximumIngredients;           // Offset:   24 Size:     4
//   int _IngredientCount;              // Offset:   28 Size:     4
//   int _SpawnCount;                   // Offset:   32 Size:     4 [unused]
//   int _GridWidth;                    // Offset:   36 Size:     4
//   int _GridHeight;                   // Offset:   40 Size:     4
//   int _GridCellCount;                // Offset:   44 Size:     4 [unused]
//   int _BoundaryCount;                // Offset:   48 Size:     4 [unused]
//   int _VesselTriggerCount;           // Offset:   52 Size:     4 [unused]
//   int _AgitatorCount;                // Offset:   56 Size:     4 [unused]
//   int _TechniqueTargetVessel;        // Offset:   60 Size:     4 [unused]
//   int _TechniqueMask;                // Offset:   64 Size:     4 [unused]
//   int _TechniqueStateMask;           // Offset:   68 Size:     4 [unused]
//   int _TransformTargetVessel;        // Offset:   72 Size:     4 [unused]
//   int _SuspensionTargetVessel;       // Offset:   76 Size:     4 [unused]
//   int _SuspensionEnabled;            // Offset:   80 Size:     4 [unused]
//   int _ReferenceSolverEnabled;       // Offset:   84 Size:     4 [unused]
//   int _ImprovedPhysics;              // Offset:   88 Size:     4 [unused]
//   int _TransferTargetVessel;         // Offset:   92 Size:     4 [unused]
//   float _ReferenceParticleVolume;    // Offset:   96 Size:     4 [unused]
//   float _ReferenceRestDensity;       // Offset:  100 Size:     4 [unused]
//   float _ReferencePressureStiffness; // Offset:  104 Size:     4 [unused]
//   float _ReferenceNearPressureStiffness;// Offset:  108 Size:     4 [unused]
//   float _ReferenceViscosityRate;     // Offset:  112 Size:     4 [unused]
//   float _ReferenceMaximumTensionRatio;// Offset:  116 Size:     4 [unused]
//   float _ReferenceMaximumAcceleration;// Offset:  120 Size:     4 [unused]
//   float _ReferenceMaximumDisplacementRatio;// Offset:  124 Size:     4 [unused]
//   float _DeltaTime;                  // Offset:  128 Size:     4 [unused]
//   float _ParticleRadius;             // Offset:  132 Size:     4 [unused]
//   float _SmoothingRadius;            // Offset:  136 Size:     4
//   float _RestDensity;                // Offset:  140 Size:     4 [unused]
//   float _DensityCompliance;          // Offset:  144 Size:     4 [unused]
//   float _LambdaEpsilon;              // Offset:  148 Size:     4 [unused]
//   float _ArtificialPressureStrength; // Offset:  152 Size:     4 [unused]
//   float _ArtificialPressureRadiusRatio;// Offset:  156 Size:     4 [unused]
//   float _BoundaryDensityScale;       // Offset:  160 Size:     4 [unused]
//   float _WallFriction;               // Offset:  164 Size:     4 [unused]
//   float _WallRestitution;            // Offset:  168 Size:     4 [unused]
//   float _SplashTransfer;             // Offset:  172 Size:     4 [unused]
//   float _SplashMinimumImpactSpeed;   // Offset:  176 Size:     4 [unused]
//   float _BottomImpactSpread;         // Offset:  180 Size:     4 [unused]
//   float _VelocityDamping;            // Offset:  184 Size:     4 [unused]
//   float _MaximumSpeed;               // Offset:  188 Size:     4 [unused]
//   float _ClosedVesselDampingRate;    // Offset:  192 Size:     4 [unused]
//   float _ClosedVesselMaximumRelativeSpeed;// Offset:  196 Size:     4 [unused]
//   float _Viscosity;                  // Offset:  200 Size:     4 [unused]
//   float _PassiveMixRate;             // Offset:  204 Size:     4
//   float _AgitationMixRate;           // Offset:  208 Size:     4
//   float _FullMixRelativeSpeed;       // Offset:  212 Size:     4
//   float _MaximumMixPerSubstep;       // Offset:  216 Size:     4
//   float _MinimumVisibleAlpha;        // Offset:  220 Size:     4 [unused]
//   float2 _Gravity;                   // Offset:  224 Size:     8 [unused]
//   float2 _GridOrigin;                // Offset:  232 Size:     8
//   float2 _WorldMin;                  // Offset:  240 Size:     8 [unused]
//   float2 _WorldMax;                  // Offset:  248 Size:     8 [unused]
//   float2 _TransformDelta;            // Offset:  256 Size:     8 [unused]
//   int _SwapA;                        // Offset:  264 Size:     4 [unused]
//   int _SwapB;                        // Offset:  268 Size:     4 [unused]
//   float2 _SwapDeltaA;                // Offset:  272 Size:     8 [unused]
//   float2 _SwapDeltaB;                // Offset:  280 Size:     8 [unused]
//   int _BoundaryGroupCount;           // Offset:  288 Size:     4 [unused]
//   int _ImprovedVesselCount;          // Offset:  292 Size:     4 [unused]
//   float _ImprovedAreaPerMl;          // Offset:  296 Size:     4 [unused]
//   float _ImprovedKernelRatio;        // Offset:  300 Size:     4 [unused]
//   float _ImprovedCompliance;         // Offset:  304 Size:     4 [unused]
//   float _ImprovedCorrectionRatio;    // Offset:  308 Size:     4 [unused]
//   float _ImprovedWallDensity;        // Offset:  312 Size:     4 [unused]
//   float _ImprovedShear;              // Offset:  316 Size:     4 [unused]
//   float _ImprovedTension;            // Offset:  320 Size:     4 [unused]
//   float _ImprovedWetting;            // Offset:  324 Size:     4 [unused]
//
// }
//
// Resource bind info for _CompositionRead
// {
//
//   float $Element;                    // Offset:    0 Size:     4
//
// }
//
// Resource bind info for _Particles
// {
//
//   struct LiquidParticle
//   {
//       
//       float2 position;               // Offset:    0
//       float2 previousPosition;       // Offset:    8
//       float2 velocity;               // Offset:   16
//       float volumeMl;                // Offset:   24
//       float temperatureC;            // Offset:   28
//       uint vesselId;                 // Offset:   32
//       uint techniqueFlags;           // Offset:   36
//       uint stateFlags;               // Offset:   40
//       uint active;                   // Offset:   44
//       uint padding;                  // Offset:   48
//
//   } $Element;                        // Offset:    0 Size:    52
//
// }
//
// Resource bind info for _CompositionWrite
// {
//
//   float $Element;                    // Offset:    0 Size:     4
//
// }
//
// Resource bind info for _ConservativeMixWeights
// {
//
//   float $Element;                    // Offset:    0 Size:     4
//
// }
//
// Resource bind info for _GridHeads
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
// Resource bind info for _GridNext
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
// Resource bind info for _StreamParticles
// {
//
//   struct StreamParticle
//   {
//       
//       uint token;                    // Offset:    0
//       uint previousToken;            // Offset:    4
//       uint streamId;                 // Offset:    8
//       uint sourceId;                 // Offset:   12
//       float delay;                   // Offset:   16
//       float stepDt;                  // Offset:   20
//       float startFraction;           // Offset:   24
//       float birthTime;               // Offset:   28
//       float radius;                  // Offset:   32
//       uint detached;                 // Offset:   36
//       uint pending;                  // Offset:   40
//       uint padding;                  // Offset:   44
//
//   } $Element;                        // Offset:    0 Size:    48
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// _CompositionRead                  texture  struct         r/o             t0      1 
// _Particles                            UAV  struct         r/w             u0      1 
// _CompositionWrite                     UAV  struct         r/w             u1      1 
// _ConservativeMixWeights               UAV  struct         r/w             u2      1 
// _GridHeads                            UAV  struct         r/w             u3      1 
// _GridNext                             UAV  struct         r/w             u4      1 
// _StreamParticles                      UAV  struct         r/w             u5      1 
// $Globals                          cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[15], immediateIndexed
dcl_resource_structured t0, 4
dcl_uav_structured u0, 52
dcl_uav_structured u1, 4
dcl_uav_structured u2, 4
dcl_uav_structured u3, 4
dcl_uav_structured u4, 4
dcl_uav_structured u5, 48
dcl_input vThreadID.x
dcl_temps 11
dcl_thread_group 64, 1, 1
uge r0.x, vThreadID.x, cb0[1].y
if_nz r0.x
  ret 
endif 
ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r0.xy, vThreadID.x, l(0), u0.xyxx
ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r1.xyz, vThreadID.x, l(16), u0.xyzx
ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r0.z, vThreadID.x, l(32), u0.xxxx
ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r2.xy, vThreadID.x, l(40), u0.xyxx
ine r0.w, r2.y, l(0)
lt r1.w, l(0.000000), r1.z
add r2.zw, r0.xxxy, -cb0[14].zzzw
div r2.zw, r2.zzzw, cb0[8].zzzz
round_ni r2.zw, r2.zzzw
ftoi r2.zw, r2.zzzw
ieq r2.y, r2.y, l(0)
ge r3.x, l(0.000000), r1.z
max r3.y, cb0[8].z, l(0.000010)
max r3.z, cb0[13].y, l(0.010000)
mov r3.w, cb0[1].w
mov r4.xy, cb0[2].yzyy
mov r4.z, l(0)
loop 
  ige r4.w, r4.z, cb0[1].z
  breakc_nz r4.w
  imad r4.w, vThreadID.x, cb0[1].z, r4.z
  ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r5.x, r4.w, l(0), t0.xxxx
  ilt r5.y, r4.z, r3.w
  and r5.y, r0.w, r5.y
  and r5.y, r1.w, r5.y
  if_nz r5.y
    mov r5.yz, r4.xxyx
    mov r5.w, l(0)
    mov r6.y, l(-1)
    loop 
      ilt r6.z, l(1), r6.y
      breakc_nz r6.z
      mov r6.z, r5.w
      mov r6.x, l(-1)
      loop 
        ilt r6.w, l(1), r6.x
        breakc_nz r6.w
        iadd r7.xy, r2.zwzz, r6.xyxx
        ige r7.zw, r7.xxxy, l(0, 0, 0, 0)
        and r6.w, r7.w, r7.z
        ilt r7.z, r7.x, r5.y
        and r6.w, r6.w, r7.z
        ilt r7.z, r7.y, r5.z
        and r6.w, r6.w, r7.z
        if_z r6.w
          iadd r6.w, r6.x, l(1)
          mov r6.x, r6.w
          continue 
        endif 
        imad r6.w, r7.y, r5.y, r7.x
        ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r6.w, r6.w, l(0), u3.xxxx
        ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r7.x, vThreadID.x, l(20), u5.xxxx
        mov r7.y, r6.z
        mov r7.z, r6.w
        mov r7.w, l(0)
        loop 
          ige r8.x, r7.z, l(0)
          ilt r8.y, r7.w, cb0[1].y
          and r8.x, r8.y, r8.x
          breakc_z r8.x
          iadd r7.w, r7.w, l(1)
          ine r8.x, r7.z, vThreadID.x
          if_nz r8.x
            ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r8.xy, r7.z, l(0), u0.xyxx
            ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r9.xyz, r7.z, l(16), u0.xyzx
            ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r8.z, r7.z, l(32), u0.xxxx
            ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r10.xy, r7.z, l(40), u0.xyxx
            ieq r8.w, r10.y, l(0)
            or r8.w, r2.y, r8.w
            or r8.w, r3.x, r8.w
            ge r9.w, l(0.000000), r9.z
            or r8.w, r8.w, r9.w
            or r9.w, r2.x, r10.x
            and r9.w, r9.w, l(4)
            ine r9.w, r9.w, l(0)
            or r8.w, r8.w, r9.w
            ine r8.z, r0.z, r8.z
            or r8.z, r8.z, r8.w
            if_z r8.z
              ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r8.z, r7.z, l(20), u5.xxxx
              min r8.z, r7.x, r8.z
              lt r8.w, l(0.000001), r8.z
              add r8.xy, r0.xyxx, -r8.xyxx
              dp2 r8.x, r8.xyxx, r8.xyxx
              sqrt r8.x, r8.x
              div r8.x, r8.x, r3.y
              add r8.x, -r8.x, l(1.000000)
              max r8.x, r8.x, l(0.000000)
              add r9.xy, r1.xyxx, -r9.xyxx
              dp2 r8.y, r9.xyxx, r9.xyxx
              sqrt r8.y, r8.y
              div r8.y, r8.y, r3.z
              min r8.y, r8.y, l(1.000000)
              mad r8.y, cb0[13].x, r8.y, cb0[12].w
              mul r8.x, r8.x, r8.y
              mul r8.x, r8.z, r8.x
              min r8.x, r8.x, cb0[13].z
              mul r8.x, r8.x, l(0.031250)
              mul r8.y, r1.z, r9.z
              add r8.z, r1.z, r9.z
              div r8.y, r8.y, r8.z
              mul r8.x, r8.y, r8.x
              and r8.x, r8.x, r8.w
            else 
              mov r8.x, l(0)
            endif 
            ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r8.y, vThreadID.x, l(0), u2.xxxx
            ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r8.z, r7.z, l(0), u2.xxxx
            max r8.y, r8.z, r8.y
            div r8.x, r8.x, r8.y
            div r8.x, r8.x, r1.z
            imad r8.y, r7.z, cb0[1].z, r4.z
            ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r8.y, r8.y, l(0), t0.xxxx
            add r8.y, -r5.x, r8.y
            mad r7.y, r8.x, r8.y, r7.y
          endif 
          ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r7.z, r7.z, l(0), u4.xxxx
        endloop 
        mov r6.z, r7.y
        iadd r6.x, r6.x, l(1)
      endloop 
      mov r5.w, r6.z
      iadd r6.y, r6.y, l(1)
    endloop 
  else 
    mov r5.w, l(0)
  endif 
  add r5.x, r5.w, r5.x
  store_structured u1.x, r4.w, l(0), r5.x
  iadd r4.z, r4.z, l(1)
endloop 
ret 
// Approximately 136 instruction slots used
