//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer $Globals
// {
//
//   int _StreamHeadCount;              // Offset:    0 Size:     4 [unused]
//   int _StreamRenderingEnabled;       // Offset:    4 Size:     4 [unused]
//   float _SimulationTime;             // Offset:    8 Size:     4 [unused]
//   float _StreamMaximumGap;           // Offset:   12 Size:     4 [unused]
//   float _StreamMaximumLength;        // Offset:   16 Size:     4 [unused]
//   int _ParticleCapacity;             // Offset:   20 Size:     4
//   int _MaximumIngredients;           // Offset:   24 Size:     4
//   int _IngredientCount;              // Offset:   28 Size:     4
//   int _SpawnCount;                   // Offset:   32 Size:     4 [unused]
//   int _GridWidth;                    // Offset:   36 Size:     4
//   int _GridHeight;                   // Offset:   40 Size:     4
//   int _GridCellCount;                // Offset:   44 Size:     4 [unused]
//   int _BoundaryCount;                // Offset:   48 Size:     4 [unused]
//   int _VesselTriggerCount;           // Offset:   52 Size:     4 [unused]
//   int _AgitatorCount;                // Offset:   56 Size:     4 [unused]
//   int _TechniqueTargetVessel;        // Offset:   60 Size:     4 [unused]
//   int _TechniqueMask;                // Offset:   64 Size:     4 [unused]
//   int _TechniqueStateMask;           // Offset:   68 Size:     4 [unused]
//   int _TransformTargetVessel;        // Offset:   72 Size:     4 [unused]
//   int _SuspensionTargetVessel;       // Offset:   76 Size:     4 [unused]
//   int _SuspensionEnabled;            // Offset:   80 Size:     4 [unused]
//   int _ReferenceSolverEnabled;       // Offset:   84 Size:     4 [unused]
//   int _ImprovedPhysics;              // Offset:   88 Size:     4 [unused]
//   int _TransferTargetVessel;         // Offset:   92 Size:     4 [unused]
//   float _ReferenceParticleVolume;    // Offset:   96 Size:     4 [unused]
//   float _ReferenceRestDensity;       // Offset:  100 Size:     4 [unused]
//   float _ReferencePressureStiffness; // Offset:  104 Size:     4 [unused]
//   float _ReferenceNearPressureStiffness;// Offset:  108 Size:     4 [unused]
//   float _ReferenceViscosityRate;     // Offset:  112 Size:     4 [unused]
//   float _ReferenceMaximumTensionRatio;// Offset:  116 Size:     4 [unused]
//   float _ReferenceMaximumAcceleration;// Offset:  120 Size:     4 [unused]
//   float _ReferenceMaximumDisplacementRatio;// Offset:  124 Size:     4 [unused]
//   float _DeltaTime;                  // Offset:  128 Size:     4 [unused]
//   float _ParticleRadius;             // Offset:  132 Size:     4 [unused]
//   float _SmoothingRadius;            // Offset:  136 Size:     4
//   float _RestDensity;                // Offset:  140 Size:     4 [unused]
//   float _DensityCompliance;          // Offset:  144 Size:     4 [unused]
//   float _LambdaEpsilon;              // Offset:  148 Size:     4 [unused]
//   float _ArtificialPressureStrength; // Offset:  152 Size:     4 [unused]
//   float _ArtificialPressureRadiusRatio;// Offset:  156 Size:     4 [unused]
//   float _BoundaryDensityScale;       // Offset:  160 Size:     4 [unused]
//   float _WallFriction;               // Offset:  164 Size:     4 [unused]
//   float _WallRestitution;            // Offset:  168 Size:     4 [unused]
//   float _SplashTransfer;             // Offset:  172 Size:     4 [unused]
//   float _SplashMinimumImpactSpeed;   // Offset:  176 Size:     4 [unused]
//   float _BottomImpactSpread;         // Offset:  180 Size:     4 [unused]
//   float _VelocityDamping;            // Offset:  184 Size:     4 [unused]
//   float _MaximumSpeed;               // Offset:  188 Size:     4 [unused]
//   float _ClosedVesselDampingRate;    // Offset:  192 Size:     4 [unused]
//   float _ClosedVesselMaximumRelativeSpeed;// Offset:  196 Size:     4 [unused]
//   float _Viscosity;                  // Offset:  200 Size:     4 [unused]
//   float _PassiveMixRate;             // Offset:  204 Size:     4
//   float _AgitationMixRate;           // Offset:  208 Size:     4
//   float _FullMixRelativeSpeed;       // Offset:  212 Size:     4
//   float _MaximumMixPerSubstep;       // Offset:  216 Size:     4
//   float _MinimumVisibleAlpha;        // Offset:  220 Size:     4 [unused]
//   float2 _Gravity;                   // Offset:  224 Size:     8 [unused]
//   float2 _GridOrigin;                // Offset:  232 Size:     8
//   float2 _WorldMin;                  // Offset:  240 Size:     8 [unused]
//   float2 _WorldMax;                  // Offset:  248 Size:     8 [unused]
//   float2 _TransformDelta;            // Offset:  256 Size:     8 [unused]
//   int _SwapA;                        // Offset:  264 Size:     4 [unused]
//   int _SwapB;                        // Offset:  268 Size:     4 [unused]
//   float2 _SwapDeltaA;                // Offset:  272 Size:     8 [unused]
//   float2 _SwapDeltaB;                // Offset:  280 Size:     8 [unused]
//   int _BoundaryGroupCount;           // Offset:  288 Size:     4 [unused]
//   int _ImprovedVesselCount;          // Offset:  292 Size:     4 [unused]
//   float _ImprovedAreaPerMl;          // Offset:  296 Size:     4 [unused]
//   float _ImprovedKernelRatio;        // Offset:  300 Size:     4 [unused]
//   float _ImprovedCompliance;         // Offset:  304 Size:     4 [unused]
//   float _ImprovedCorrectionRatio;    // Offset:  308 Size:     4 [unused]
//   float _ImprovedWallDensity;        // Offset:  312 Size:     4 [unused]
//   float _ImprovedShear;              // Offset:  316 Size:     4 [unused]
//   float _ImprovedTension;            // Offset:  320 Size:     4 [unused]
//   float _ImprovedWetting;            // Offset:  324 Size:     4 [unused]
//
// }
//
// Resource bind info for _CompositionRead
// {
//
//   float $Element;                    // Offset:    0 Size:     4
//
// }
//
// Resource bind info for _Particles
// {
//
//   struct LiquidParticle
//   {
//       
//       float2 position;               // Offset:    0
//       float2 previousPosition;       // Offset:    8
//       float2 velocity;               // Offset:   16
//       float volumeMl;                // Offset:   24
//       float temperatureC;            // Offset:   28
//       uint vesselId;                 // Offset:   32
//       uint techniqueFlags;           // Offset:   36
//       uint stateFlags;               // Offset:   40
//       uint active;                   // Offset:   44
//       uint padding;                  // Offset:   48
//
//   } $Element;                        // Offset:    0 Size:    52
//
// }
//
// Resource bind info for _CompositionWrite
// {
//
//   float $Element;                    // Offset:    0 Size:     4
//
// }
//
// Resource bind info for _GridHeads
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
// Resource bind info for _GridNext
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
// Resource bind info for _StreamParticles
// {
//
//   struct StreamParticle
//   {
//       
//       uint token;                    // Offset:    0
//       uint previousToken;            // Offset:    4
//       uint streamId;                 // Offset:    8
//       uint sourceId;                 // Offset:   12
//       float delay;                   // Offset:   16
//       float stepDt;                  // Offset:   20
//       float startFraction;           // Offset:   24
//       float birthTime;               // Offset:   28
//       float radius;                  // Offset:   32
//       uint detached;                 // Offset:   36
//       uint pending;                  // Offset:   40
//       uint padding;                  // Offset:   44
//
//   } $Element;                        // Offset:    0 Size:    48
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// _CompositionRead                  texture  struct         r/o             t0      1 
// _Particles                            UAV  struct         r/w             u0      1 
// _CompositionWrite                     UAV  struct         r/w             u1      1 
// _GridHeads                            UAV  struct         r/w             u2      1 
// _GridNext                             UAV  struct         r/w             u3      1 
// _StreamParticles                      UAV  struct         r/w             u4      1 
// $Globals                          cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[15], immediateIndexed
dcl_resource_structured t0, 4
dcl_uav_structured u0, 52
dcl_uav_structured u1, 4
dcl_uav_structured u2, 4
dcl_uav_structured u3, 4
dcl_uav_structured u4, 48
dcl_input vThreadID.x
dcl_temps 10
dcl_thread_group 64, 1, 1
uge r0.x, vThreadID.x, cb0[1].y
if_nz r0.x
  ret 
endif 
ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r0.xy, vThreadID.x, l(0), u0.xyxx
ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r1.xyz, vThreadID.x, l(16), u0.xyzx
ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r0.z, vThreadID.x, l(32), u0.xxxx
ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r2.xy, vThreadID.x, l(40), u0.xyxx
ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r0.w, vThreadID.x, l(20), u4.xxxx
ge r0.w, l(0.000001), r0.w
ieq r1.w, r2.y, l(0)
or r0.w, r0.w, r1.w
and r1.w, r2.x, l(4)
ine r1.w, r1.w, l(0)
or r0.w, r0.w, r1.w
ige r1.w, l(0), cb0[1].w
or r0.w, r0.w, r1.w
if_nz r0.w
  mov r0.w, l(0)
  loop 
    ige r1.w, r0.w, cb0[1].z
    breakc_nz r1.w
    imad r1.w, vThreadID.x, cb0[1].z, r0.w
    ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r2.x, r1.w, l(0), t0.xxxx
    store_structured u1.x, r1.w, l(0), r2.x
    iadd r0.w, r0.w, l(1)
  endloop 
  ret 
endif 
add r2.xy, r0.xyxx, -cb0[14].zwzz
div r2.xy, r2.xyxx, cb0[8].zzzz
round_ni r2.xy, r2.xyxx
ftoi r2.xy, r2.xyxx
ieq r0.w, r0.z, l(0)
max r1.w, cb0[8].z, l(0.000010)
max r2.z, cb0[13].y, l(0.010000)
mul r2.w, cb0[13].z, l(0.031250)
mov r3.xy, cb0[2].yzyy
mov r3.z, l(0)
loop 
  ige r3.w, r3.z, cb0[1].w
  breakc_nz r3.w
  imad r3.w, vThreadID.x, cb0[1].z, r3.z
  ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r4.x, r3.w, l(0), t0.xxxx
  mov r4.yz, r3.xxyx
  mov r4.w, l(0)
  mov r5.y, l(-1)
  loop 
    ilt r5.z, l(1), r5.y
    breakc_nz r5.z
    mov r5.z, r4.w
    mov r5.x, l(-1)
    loop 
      ilt r5.w, l(1), r5.x
      breakc_nz r5.w
      iadd r6.xy, r2.xyxx, r5.xyxx
      ige r6.zw, r6.xxxy, l(0, 0, 0, 0)
      and r5.w, r6.w, r6.z
      ilt r6.z, r6.x, r4.y
      and r5.w, r5.w, r6.z
      ilt r6.z, r6.y, r4.z
      and r5.w, r5.w, r6.z
      if_z r5.w
        iadd r5.w, r5.x, l(1)
        mov r5.x, r5.w
        continue 
      endif 
      imad r5.w, r6.y, r4.y, r6.x
      ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r5.w, r5.w, l(0), u2.xxxx
      ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r6.x, vThreadID.x, l(20), u4.xxxx
      mov r6.y, r5.z
      mov r6.z, r5.w
      mov r6.w, l(0)
      loop 
        ige r7.x, r6.z, l(0)
        ilt r7.y, r6.w, cb0[1].y
        and r7.x, r7.y, r7.x
        breakc_z r7.x
        iadd r6.w, r6.w, l(1)
        ine r7.x, r6.z, vThreadID.x
        if_nz r7.x
          ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r7.xy, r6.z, l(0), u0.xyxx
          ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r8.xyz, r6.z, l(16), u0.xyzx
          ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r7.z, r6.z, l(32), u0.xxxx
          ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r9.xy, r6.z, l(40), u0.xyxx
          add r7.xy, r0.xyxx, -r7.xyxx
          dp2 r7.x, r7.xyxx, r7.xyxx
          sqrt r7.x, r7.x
          ieq r7.y, r0.z, r7.z
          or r7.y, r0.w, r7.y
          ieq r7.z, r7.z, l(0)
          or r7.y, r7.z, r7.y
          ine r7.z, r9.y, l(0)
          and r7.w, r9.x, l(4)
          ieq r7.w, r7.w, l(0)
          and r7.z, r7.w, r7.z
          and r7.y, r7.y, r7.z
          lt r7.z, r7.x, cb0[8].z
          and r7.y, r7.z, r7.y
          if_nz r7.y
            div r7.x, r7.x, r1.w
            add r7.x, -r7.x, l(1.000000)
            max r7.x, r7.x, l(0.000000)
            add r7.yz, r1.xxyx, -r8.xxyx
            dp2 r7.y, r7.yzyy, r7.yzyy
            sqrt r7.y, r7.y
            div r7.y, r7.y, r2.z
            min r7.y, r7.y, l(1.000000)
            mad r7.y, cb0[13].x, r7.y, cb0[12].w
            mul r7.x, r7.x, r7.y
            mul r7.x, r6.x, r7.x
            mul r7.x, r7.x, l(0.031250)
            min r7.x, r2.w, r7.x
            imad r7.y, r6.z, cb0[1].z, r3.z
            ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r7.y, r7.y, l(0), t0.xxxx
            add r7.z, r1.z, r8.z
            max r7.z, r7.z, l(0.000010)
            mul r7.y, r8.z, r7.y
            mad r7.y, r4.x, r1.z, r7.y
            div r7.y, r7.y, r7.z
            add r7.y, -r4.x, r7.y
            mad r6.y, r7.y, r7.x, r6.y
          endif 
        endif 
        ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r6.z, r6.z, l(0), u3.xxxx
      endloop 
      mov r5.z, r6.y
      iadd r5.x, r5.x, l(1)
    endloop 
    mov r4.w, r5.z
    iadd r5.y, r5.y, l(1)
  endloop 
  add r4.x, r4.w, r4.x
  max r4.x, r4.x, l(0.000000)
  store_structured u1.x, r3.w, l(0), r4.x
  iadd r3.z, r3.z, l(1)
endloop 
mov r0.xy, l(0,0,0,0)
loop 
  ige r0.z, r0.y, cb0[1].w
  breakc_nz r0.z
  imad r0.z, vThreadID.x, cb0[1].z, r0.y
  ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r0.z, r0.z, l(0), u1.xxxx
  add r0.x, r0.z, r0.x
  iadd r0.y, r0.y, l(1)
endloop 
lt r0.y, l(0.000010), r0.x
if_nz r0.y
  mov r0.y, l(0)
  loop 
    ige r0.z, r0.y, cb0[1].w
    breakc_nz r0.z
    imad r0.z, vThreadID.x, cb0[1].z, r0.y
    ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r0.w, r0.z, l(0), u1.xxxx
    div r0.w, r0.w, r0.x
    store_structured u1.x, r0.z, l(0), r0.w
    iadd r0.y, r0.y, l(1)
  endloop 
endif 
mov r0.x, cb0[1].w
loop 
  ige r0.y, r0.x, cb0[1].z
  breakc_nz r0.y
  imad r0.y, vThreadID.x, cb0[1].z, r0.x
  store_structured u1.x, r0.y, l(0), l(0)
  iadd r0.x, r0.x, l(1)
endloop 
ret 
// Approximately 168 instruction slots used
