//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer $Globals
// {
//
//   int _StreamHeadCount;              // Offset:    0 Size:     4 [unused]
//   int _StreamRenderingEnabled;       // Offset:    4 Size:     4 [unused]
//   float _SimulationTime;             // Offset:    8 Size:     4 [unused]
//   float _StreamMaximumGap;           // Offset:   12 Size:     4 [unused]
//   float _StreamMaximumLength;        // Offset:   16 Size:     4 [unused]
//   int _ParticleCapacity;             // Offset:   20 Size:     4
//   int _MaximumIngredients;           // Offset:   24 Size:     4
//   int _IngredientCount;              // Offset:   28 Size:     4 [unused]
//   int _SpawnCount;                   // Offset:   32 Size:     4
//   int _GridWidth;                    // Offset:   36 Size:     4 [unused]
//   int _GridHeight;                   // Offset:   40 Size:     4 [unused]
//   int _GridCellCount;                // Offset:   44 Size:     4 [unused]
//   int _BoundaryCount;                // Offset:   48 Size:     4 [unused]
//   int _VesselTriggerCount;           // Offset:   52 Size:     4 [unused]
//   int _AgitatorCount;                // Offset:   56 Size:     4 [unused]
//   int _TechniqueTargetVessel;        // Offset:   60 Size:     4 [unused]
//   int _TechniqueMask;                // Offset:   64 Size:     4 [unused]
//   int _TechniqueStateMask;           // Offset:   68 Size:     4 [unused]
//   int _TransformTargetVessel;        // Offset:   72 Size:     4 [unused]
//   int _SuspensionTargetVessel;       // Offset:   76 Size:     4 [unused]
//   int _SuspensionEnabled;            // Offset:   80 Size:     4 [unused]
//   int _ReferenceSolverEnabled;       // Offset:   84 Size:     4 [unused]
//   int _ImprovedPhysics;              // Offset:   88 Size:     4 [unused]
//   int _TransferTargetVessel;         // Offset:   92 Size:     4 [unused]
//   float _ReferenceParticleVolume;    // Offset:   96 Size:     4 [unused]
//   float _ReferenceRestDensity;       // Offset:  100 Size:     4 [unused]
//   float _ReferencePressureStiffness; // Offset:  104 Size:     4 [unused]
//   float _ReferenceNearPressureStiffness;// Offset:  108 Size:     4 [unused]
//   float _ReferenceViscosityRate;     // Offset:  112 Size:     4 [unused]
//   float _ReferenceMaximumTensionRatio;// Offset:  116 Size:     4 [unused]
//   float _ReferenceMaximumAcceleration;// Offset:  120 Size:     4 [unused]
//   float _ReferenceMaximumDisplacementRatio;// Offset:  124 Size:     4 [unused]
//   float _DeltaTime;                  // Offset:  128 Size:     4 [unused]
//   float _ParticleRadius;             // Offset:  132 Size:     4 [unused]
//   float _SmoothingRadius;            // Offset:  136 Size:     4 [unused]
//   float _RestDensity;                // Offset:  140 Size:     4 [unused]
//   float _DensityCompliance;          // Offset:  144 Size:     4 [unused]
//   float _LambdaEpsilon;              // Offset:  148 Size:     4 [unused]
//   float _ArtificialPressureStrength; // Offset:  152 Size:     4 [unused]
//   float _ArtificialPressureRadiusRatio;// Offset:  156 Size:     4 [unused]
//   float _BoundaryDensityScale;       // Offset:  160 Size:     4 [unused]
//   float _WallFriction;               // Offset:  164 Size:     4 [unused]
//   float _WallRestitution;            // Offset:  168 Size:     4 [unused]
//   float _SplashTransfer;             // Offset:  172 Size:     4 [unused]
//   float _SplashMinimumImpactSpeed;   // Offset:  176 Size:     4 [unused]
//   float _BottomImpactSpread;         // Offset:  180 Size:     4 [unused]
//   float _VelocityDamping;            // Offset:  184 Size:     4 [unused]
//   float _MaximumSpeed;               // Offset:  188 Size:     4 [unused]
//   float _ClosedVesselDampingRate;    // Offset:  192 Size:     4 [unused]
//   float _ClosedVesselMaximumRelativeSpeed;// Offset:  196 Size:     4 [unused]
//   float _Viscosity;                  // Offset:  200 Size:     4 [unused]
//   float _PassiveMixRate;             // Offset:  204 Size:     4 [unused]
//   float _AgitationMixRate;           // Offset:  208 Size:     4 [unused]
//   float _FullMixRelativeSpeed;       // Offset:  212 Size:     4 [unused]
//   float _MaximumMixPerSubstep;       // Offset:  216 Size:     4 [unused]
//   float _MinimumVisibleAlpha;        // Offset:  220 Size:     4 [unused]
//   float2 _Gravity;                   // Offset:  224 Size:     8 [unused]
//   float2 _GridOrigin;                // Offset:  232 Size:     8 [unused]
//   float2 _WorldMin;                  // Offset:  240 Size:     8 [unused]
//   float2 _WorldMax;                  // Offset:  248 Size:     8 [unused]
//   float2 _TransformDelta;            // Offset:  256 Size:     8 [unused]
//   int _SwapA;                        // Offset:  264 Size:     4 [unused]
//   int _SwapB;                        // Offset:  268 Size:     4 [unused]
//   float2 _SwapDeltaA;                // Offset:  272 Size:     8 [unused]
//   float2 _SwapDeltaB;                // Offset:  280 Size:     8 [unused]
//   int _BoundaryGroupCount;           // Offset:  288 Size:     4 [unused]
//   int _ImprovedVesselCount;          // Offset:  292 Size:     4 [unused]
//   float _ImprovedAreaPerMl;          // Offset:  296 Size:     4 [unused]
//   float _ImprovedKernelRatio;        // Offset:  300 Size:     4 [unused]
//   float _ImprovedCompliance;         // Offset:  304 Size:     4 [unused]
//   float _ImprovedCorrectionRatio;    // Offset:  308 Size:     4 [unused]
//   float _ImprovedWallDensity;        // Offset:  312 Size:     4 [unused]
//   float _ImprovedShear;              // Offset:  316 Size:     4 [unused]
//   float _ImprovedTension;            // Offset:  320 Size:     4 [unused]
//   float _ImprovedWetting;            // Offset:  324 Size:     4 [unused]
//
// }
//
// Resource bind info for _FreeIndicesRead
// {
//
//   uint $Element;                     // Offset:    0 Size:     4
//
// }
//
// Resource bind info for _SpawnCommands
// {
//
//   struct SpawnCommand
//   {
//       
//       float2 position;               // Offset:    0
//       float2 velocity;               // Offset:    8
//       float volumeMl;                // Offset:   16
//       float temperatureC;            // Offset:   20
//       uint sourceIngredient;         // Offset:   24
//       uint vesselId;                 // Offset:   28
//       uint stateFlags;               // Offset:   32
//
//   } $Element;                        // Offset:    0 Size:    36
//
// }
//
// Resource bind info for _SpawnStreams
// {
//
//   struct StreamParticle
//   {
//       
//       uint token;                    // Offset:    0
//       uint previousToken;            // Offset:    4
//       uint streamId;                 // Offset:    8
//       uint sourceId;                 // Offset:   12
//       float delay;                   // Offset:   16
//       float stepDt;                  // Offset:   20
//       float startFraction;           // Offset:   24
//       float birthTime;               // Offset:   28
//       float radius;                  // Offset:   32
//       uint detached;                 // Offset:   36
//       uint pending;                  // Offset:   40
//       uint padding;                  // Offset:   44
//
//   } $Element;                        // Offset:    0 Size:    48
//
// }
//
// Resource bind info for _Particles
// {
//
//   struct LiquidParticle
//   {
//       
//       float2 position;               // Offset:    0
//       float2 previousPosition;       // Offset:    8
//       float2 velocity;               // Offset:   16
//       float volumeMl;                // Offset:   24
//       float temperatureC;            // Offset:   28
//       uint vesselId;                 // Offset:   32
//       uint techniqueFlags;           // Offset:   36
//       uint stateFlags;               // Offset:   40
//       uint active;                   // Offset:   44
//       uint padding;                  // Offset:   48
//
//   } $Element;                        // Offset:    0 Size:    52
//
// }
//
// Resource bind info for _CompositionA
// {
//
//   float $Element;                    // Offset:    0 Size:     4
//
// }
//
// Resource bind info for _CompositionB
// {
//
//   float $Element;                    // Offset:    0 Size:     4
//
// }
//
// Resource bind info for _LedgerAmounts
// {
//
//   float $Element;                    // Offset:    0 Size:     4
//
// }
//
// Resource bind info for _FreeCount
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
// Resource bind info for _Statistics
// {
//
//   uint $Element;                     // Offset:    0 Size:     4
//
// }
//
// Resource bind info for _StreamParticles
// {
//
//   struct StreamParticle
//   {
//       
//       uint token;                    // Offset:    0
//       uint previousToken;            // Offset:    4
//       uint streamId;                 // Offset:    8
//       uint sourceId;                 // Offset:   12
//       float delay;                   // Offset:   16
//       float stepDt;                  // Offset:   20
//       float startFraction;           // Offset:   24
//       float birthTime;               // Offset:   28
//       float radius;                  // Offset:   32
//       uint detached;                 // Offset:   36
//       uint pending;                  // Offset:   40
//       uint padding;                  // Offset:   44
//
//   } $Element;                        // Offset:    0 Size:    48
//
// }
//
// Resource bind info for _StreamLookup
// {
//
//   uint2 $Element;                    // Offset:    0 Size:     8
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// _FreeIndicesRead                  texture  struct         r/o             t0      1 
// _SpawnCommands                    texture  struct         r/o             t1      1 
// _SpawnStreams                     texture  struct         r/o             t2      1 
// _Particles                            UAV  struct         r/w             u0      1 
// _CompositionA                         UAV  struct         r/w             u1      1 
// _CompositionB                         UAV  struct         r/w             u2      1 
// _LedgerAmounts                        UAV  struct         r/w             u3      1 
// _FreeCount                            UAV  struct         r/w             u4      1 
// _Statistics                           UAV  struct         r/w             u5      1 
// _StreamParticles                      UAV  struct         r/w             u6      1 
// _StreamLookup                         UAV  struct         r/w             u7      1 
// $Globals                          cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[3], immediateIndexed
dcl_resource_structured t0, 4
dcl_resource_structured t1, 36
dcl_resource_structured t2, 48
dcl_uav_structured u0, 52
dcl_uav_structured u1, 4
dcl_uav_structured u2, 4
dcl_uav_structured u3, 4
dcl_uav_structured u4, 4
dcl_uav_structured u5, 4
dcl_uav_structured u6, 48
dcl_uav_structured u7, 8
dcl_input vThreadID.x
dcl_temps 5
dcl_thread_group 64, 1, 1
uge r0.x, vThreadID.x, cb0[2].x
if_nz r0.x
  ret 
endif 
ld_structured_indexable(structured_buffer, stride=36)(mixed,mixed,mixed,mixed) r0.xyzw, vThreadID.x, l(16), t1.xyzw
imm_atomic_iadd r1.x, u4, l(0, 0, 0, 0), l(-1)
ige r1.y, l(0), r1.x
if_nz r1.y
  atomic_iadd u4, l(0, 0, 0, 0), l(1)
  atomic_iadd u5, l(0, 0, 0, 0), l(1)
  iadd r1.y, cb0[1].z, l(1)
  imad r1.z, vThreadID.x, r1.y, r0.z
  bfi r1.z, l(30), l(2), r1.z, l(2)
  ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r1.w, r1.z, l(0), u3.xxxx
  add r1.w, r0.x, r1.w
  store_structured u3.x, r1.z, l(0), r1.w
  imad r1.y, vThreadID.x, r1.y, cb0[1].z
  bfi r1.y, l(30), l(2), r1.y, l(2)
  ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r1.z, r1.y, l(0), u3.xxxx
  add r1.z, r0.x, r1.z
  store_structured u3.x, r1.y, l(0), r1.z
  ret 
endif 
ld_structured_indexable(structured_buffer, stride=36)(mixed,mixed,mixed,mixed) r2.xyzw, vThreadID.x, l(0), t1.xyzw
ld_structured_indexable(structured_buffer, stride=36)(mixed,mixed,mixed,mixed) r3.z, vThreadID.x, l(32), t1.xxxx
iadd r1.x, r1.x, l(-1)
ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r1.y, r1.x, l(0), t0.xxxx
iadd r1.z, cb0[1].z, l(1)
imad r1.w, r1.y, r1.z, r0.z
ishl r1.w, r1.w, l(2)
ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r4.x, r1.w, l(0), u3.xxxx
add r4.x, r0.x, r4.x
store_structured u3.x, r1.w, l(0), r4.x
imad r1.z, r1.y, r1.z, cb0[1].z
ishl r1.z, r1.z, l(2)
ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r1.w, r1.z, l(0), u3.xxxx
add r1.w, r0.x, r1.w
store_structured u3.x, r1.z, l(0), r1.w
max r4.z, r0.x, l(0.000000)
store_structured u0.xyzw, r1.y, l(0), r2.xyxy
mov r4.xy, r2.zwzz
mov r4.w, r0.y
store_structured u0.xyzw, r1.y, l(16), r4.xyzw
mov r3.x, r0.w
mov r3.yw, l(0,0,0,0)
store_structured u0.xyzw, r1.y, l(32), r3.xyzw
store_structured u0.x, r1.y, l(48), l(0)
ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r2.xyzw, vThreadID.x, l(0), t2.xyzw
ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r3.xyzw, vThreadID.x, l(16), t2.xyzw
ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r4.xyzw, vThreadID.x, l(32), t2.xyzw
store_structured u6.xyzw, r1.y, l(0), r2.xyzw
store_structured u6.xyzw, r1.y, l(16), r3.xyzw
store_structured u6.xyzw, r1.y, l(32), r4.xyzw
if_nz r2.x
  ishl r0.x, cb0[1].y, l(1)
  udiv null, r0.x, r2.x, r0.x
  mov r1.x, r2.x
  store_structured u7.xy, r0.x, l(0), r1.xyxx
endif 
mov r0.x, l(0)
loop 
  ige r0.y, r0.x, cb0[1].z
  breakc_nz r0.y
  ieq r0.y, r0.z, r0.x
  and r0.y, r0.y, l(0x3f800000)
  imad r0.w, r1.y, cb0[1].z, r0.x
  store_structured u1.x, r0.w, l(0), r0.y
  store_structured u2.x, r0.w, l(0), r0.y
  iadd r0.x, r0.x, l(1)
endloop 
ret 
// Approximately 71 instruction slots used
