//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer $Globals
// {
//
//   int _StreamHeadCount;              // Offset:    0 Size:     4 [unused]
//   int _StreamRenderingEnabled;       // Offset:    4 Size:     4 [unused]
//   float _SimulationTime;             // Offset:    8 Size:     4 [unused]
//   float _StreamMaximumGap;           // Offset:   12 Size:     4 [unused]
//   float _StreamMaximumLength;        // Offset:   16 Size:     4 [unused]
//   int _ParticleCapacity;             // Offset:   20 Size:     4
//   int _MaximumIngredients;           // Offset:   24 Size:     4 [unused]
//   int _IngredientCount;              // Offset:   28 Size:     4 [unused]
//   int _SpawnCount;                   // Offset:   32 Size:     4 [unused]
//   int _GridWidth;                    // Offset:   36 Size:     4 [unused]
//   int _GridHeight;                   // Offset:   40 Size:     4 [unused]
//   int _GridCellCount;                // Offset:   44 Size:     4 [unused]
//   int _BoundaryCount;                // Offset:   48 Size:     4 [unused]
//   int _VesselTriggerCount;           // Offset:   52 Size:     4
//   int _AgitatorCount;                // Offset:   56 Size:     4 [unused]
//   int _TechniqueTargetVessel;        // Offset:   60 Size:     4 [unused]
//   int _TechniqueMask;                // Offset:   64 Size:     4 [unused]
//   int _TechniqueStateMask;           // Offset:   68 Size:     4 [unused]
//   int _TransformTargetVessel;        // Offset:   72 Size:     4 [unused]
//   int _SuspensionTargetVessel;       // Offset:   76 Size:     4 [unused]
//   int _SuspensionEnabled;            // Offset:   80 Size:     4 [unused]
//   int _ReferenceSolverEnabled;       // Offset:   84 Size:     4 [unused]
//   int _ImprovedPhysics;              // Offset:   88 Size:     4 [unused]
//   int _TransferTargetVessel;         // Offset:   92 Size:     4 [unused]
//   float _ReferenceParticleVolume;    // Offset:   96 Size:     4 [unused]
//   float _ReferenceRestDensity;       // Offset:  100 Size:     4 [unused]
//   float _ReferencePressureStiffness; // Offset:  104 Size:     4 [unused]
//   float _ReferenceNearPressureStiffness;// Offset:  108 Size:     4 [unused]
//   float _ReferenceViscosityRate;     // Offset:  112 Size:     4 [unused]
//   float _ReferenceMaximumTensionRatio;// Offset:  116 Size:     4 [unused]
//   float _ReferenceMaximumAcceleration;// Offset:  120 Size:     4 [unused]
//   float _ReferenceMaximumDisplacementRatio;// Offset:  124 Size:     4 [unused]
//   float _DeltaTime;                  // Offset:  128 Size:     4 [unused]
//   float _ParticleRadius;             // Offset:  132 Size:     4
//   float _SmoothingRadius;            // Offset:  136 Size:     4 [unused]
//   float _RestDensity;                // Offset:  140 Size:     4 [unused]
//   float _DensityCompliance;          // Offset:  144 Size:     4 [unused]
//   float _LambdaEpsilon;              // Offset:  148 Size:     4 [unused]
//   float _ArtificialPressureStrength; // Offset:  152 Size:     4 [unused]
//   float _ArtificialPressureRadiusRatio;// Offset:  156 Size:     4 [unused]
//   float _BoundaryDensityScale;       // Offset:  160 Size:     4 [unused]
//   float _WallFriction;               // Offset:  164 Size:     4 [unused]
//   float _WallRestitution;            // Offset:  168 Size:     4 [unused]
//   float _SplashTransfer;             // Offset:  172 Size:     4 [unused]
//   float _SplashMinimumImpactSpeed;   // Offset:  176 Size:     4 [unused]
//   float _BottomImpactSpread;         // Offset:  180 Size:     4 [unused]
//   float _VelocityDamping;            // Offset:  184 Size:     4 [unused]
//   float _MaximumSpeed;               // Offset:  188 Size:     4 [unused]
//   float _ClosedVesselDampingRate;    // Offset:  192 Size:     4 [unused]
//   float _ClosedVesselMaximumRelativeSpeed;// Offset:  196 Size:     4 [unused]
//   float _Viscosity;                  // Offset:  200 Size:     4 [unused]
//   float _PassiveMixRate;             // Offset:  204 Size:     4 [unused]
//   float _AgitationMixRate;           // Offset:  208 Size:     4 [unused]
//   float _FullMixRelativeSpeed;       // Offset:  212 Size:     4 [unused]
//   float _MaximumMixPerSubstep;       // Offset:  216 Size:     4 [unused]
//   float _MinimumVisibleAlpha;        // Offset:  220 Size:     4 [unused]
//   float2 _Gravity;                   // Offset:  224 Size:     8 [unused]
//   float2 _GridOrigin;                // Offset:  232 Size:     8 [unused]
//   float2 _WorldMin;                  // Offset:  240 Size:     8 [unused]
//   float2 _WorldMax;                  // Offset:  248 Size:     8 [unused]
//   float2 _TransformDelta;            // Offset:  256 Size:     8 [unused]
//   int _SwapA;                        // Offset:  264 Size:     4 [unused]
//   int _SwapB;                        // Offset:  268 Size:     4 [unused]
//   float2 _SwapDeltaA;                // Offset:  272 Size:     8 [unused]
//   float2 _SwapDeltaB;                // Offset:  280 Size:     8 [unused]
//   int _BoundaryGroupCount;           // Offset:  288 Size:     4
//   int _ImprovedVesselCount;          // Offset:  292 Size:     4 [unused]
//   float _ImprovedAreaPerMl;          // Offset:  296 Size:     4 [unused]
//   float _ImprovedKernelRatio;        // Offset:  300 Size:     4 [unused]
//   float _ImprovedCompliance;         // Offset:  304 Size:     4 [unused]
//   float _ImprovedCorrectionRatio;    // Offset:  308 Size:     4 [unused]
//   float _ImprovedWallDensity;        // Offset:  312 Size:     4 [unused]
//   float _ImprovedShear;              // Offset:  316 Size:     4 [unused]
//   float _ImprovedTension;            // Offset:  320 Size:     4 [unused]
//   float _ImprovedWetting;            // Offset:  324 Size:     4 [unused]
//
// }
//
// Resource bind info for _Boundaries
// {
//
//   struct BoundarySegment
//   {
//       
//       float2 a;                      // Offset:    0
//       float2 b;                      // Offset:    8
//       float2 velocityA;              // Offset:   16
//       float2 velocityB;              // Offset:   24
//       uint vesselId;                 // Offset:   32
//       uint flags;                    // Offset:   36
//       float2 localA;                 // Offset:   40
//       float2 localB;                 // Offset:   48
//       float2 startPosition;          // Offset:   56
//       float2 endPosition;            // Offset:   64
//       float startAngle;              // Offset:   72
//       float angleDelta;              // Offset:   76
//
//   } $Element;                        // Offset:    0 Size:    80
//
// }
//
// Resource bind info for _VesselTriggers
// {
//
//   struct VesselTrigger
//   {
//       
//       float2 center;                 // Offset:    0
//       float2 axisX;                  // Offset:    8
//       float2 axisY;                  // Offset:   16
//       float2 halfExtents;            // Offset:   24
//       uint vesselId;                 // Offset:   32
//       int priority;                  // Offset:   36
//       uint active;                   // Offset:   40
//       uint flags;                    // Offset:   44
//
//   } $Element;                        // Offset:    0 Size:    48
//
// }
//
// Resource bind info for _BoundaryGroups
// {
//
//   struct BoundaryGroup
//   {
//       
//       float2 minPosition;            // Offset:    0
//       float2 maxPosition;            // Offset:    8
//       float2 sweptMin;               // Offset:   16
//       float2 sweptMax;               // Offset:   24
//       uint first;                    // Offset:   32
//       uint end;                      // Offset:   36
//       uint contourFirst;             // Offset:   40
//       uint contourEnd;               // Offset:   44
//       uint vesselId;                 // Offset:   48
//
//   } $Element;                        // Offset:    0 Size:    52
//
// }
//
// Resource bind info for _Particles
// {
//
//   struct LiquidParticle
//   {
//       
//       float2 position;               // Offset:    0
//       float2 previousPosition;       // Offset:    8
//       float2 velocity;               // Offset:   16
//       float volumeMl;                // Offset:   24
//       float temperatureC;            // Offset:   28
//       uint vesselId;                 // Offset:   32
//       uint techniqueFlags;           // Offset:   36
//       uint stateFlags;               // Offset:   40
//       uint active;                   // Offset:   44
//       uint padding;                  // Offset:   48
//
//   } $Element;                        // Offset:    0 Size:    52
//
// }
//
// Resource bind info for _Statistics
// {
//
//   uint $Element;                     // Offset:    0 Size:     4
//
// }
//
// Resource bind info for _StreamParticles
// {
//
//   struct StreamParticle
//   {
//       
//       uint token;                    // Offset:    0
//       uint previousToken;            // Offset:    4
//       uint streamId;                 // Offset:    8
//       uint sourceId;                 // Offset:   12
//       float delay;                   // Offset:   16
//       float stepDt;                  // Offset:   20
//       float startFraction;           // Offset:   24
//       float birthTime;               // Offset:   28
//       float radius;                  // Offset:   32
//       uint detached;                 // Offset:   36
//       uint pending;                  // Offset:   40
//       uint padding;                  // Offset:   44
//
//   } $Element;                        // Offset:    0 Size:    48
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// _Boundaries                       texture  struct         r/o             t0      1 
// _VesselTriggers                   texture  struct         r/o             t1      1 
// _BoundaryGroups                   texture  struct         r/o             t2      1 
// _Particles                            UAV  struct         r/w             u0      1 
// _Statistics                           UAV  struct         r/w             u1      1 
// _StreamParticles                      UAV  struct         r/w             u2      1 
// $Globals                          cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[19], immediateIndexed
dcl_resource_structured t0, 80
dcl_resource_structured t1, 48
dcl_resource_structured t2, 52
dcl_uav_structured u0, 52
dcl_uav_structured u1, 4
dcl_uav_structured u2, 48
dcl_input vThreadID.x
dcl_temps 15
dcl_thread_group 64, 1, 1
uge r0.x, vThreadID.x, cb0[1].y
if_nz r0.x
  ret 
endif 
ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r0.xyzw, vThreadID.x, l(0), u0.xyzw
ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r1.x, vThreadID.x, l(32), u0.xxxx
ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r1.yz, vThreadID.x, l(40), u0.xxyx
ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r1.w, vThreadID.x, l(20), u2.xxxx
ge r1.w, l(0.000001), r1.w
ieq r1.z, r1.z, l(0)
or r1.z, r1.z, r1.w
and r1.y, r1.y, l(4)
ine r1.y, r1.y, l(0)
or r1.y, r1.y, r1.z
if_nz r1.y
  ret 
endif 
add r1.y, cb0[8].y, l(0.000500)
mov r2.y, l(0)
mov r1.zw, r0.xxxy
mov r2.z, l(0)
loop 
  ige r2.w, r2.z, cb0[18].x
  breakc_nz r2.w
  min r3.xy, r0.zwzz, r1.zwzz
  add r3.xy, r3.xyxx, -cb0[8].yyyy
  max r3.zw, r0.zzzw, r1.zzzw
  add r3.zw, r3.zzzw, cb0[8].yyyy
  ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r4.xyzw, r2.z, l(16), t2.xyzw
  ge r3.zw, r3.zzzw, r4.xxxy
  and r2.w, r3.w, r3.z
  ge r3.xy, r4.zwzz, r3.xyxx
  and r3.x, r3.y, r3.x
  and r2.w, r2.w, r3.x
  if_z r2.w
    iadd r2.w, r2.z, l(1)
    mov r2.z, r2.w
    continue 
  endif 
  ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r3.xy, r2.z, l(32), t2.xyxx
  mov r3.zw, r1.zzzw
  mov r2.w, r3.x
  loop 
    uge r4.x, r2.w, r3.y
    breakc_nz r4.x
    ld_structured_indexable(structured_buffer, stride=80)(mixed,mixed,mixed,mixed) r4.xyzw, r2.w, l(32), t0.xyzw
    and r5.x, r4.y, l(16)
    if_z r5.x
      ine r4.x, r1.x, r4.x
      if_nz r4.x
        and r4.x, r4.y, l(2)
        ine r4.x, r4.x, l(0)
        if_nz r1.x
          mov r5.xy, l(0,0,0,0)
          mov r4.y, l(0)
          loop 
            ige r5.z, r5.y, cb0[3].y
            mov r4.y, l(0)
            breakc_nz r5.z
            ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r5.z, r5.y, l(32), t1.xxxx
            ieq r5.z, r1.x, r5.z
            ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r5.w, r5.y, l(44), t1.xxxx
            and r5.w, r5.w, l(2)
            ine r5.w, r5.w, l(0)
            and r5.z, r5.w, r5.z
            if_nz r5.z
              mov r5.x, l(-1)
              mov r4.y, l(-1)
              break 
            endif 
            iadd r2.x, r5.y, l(1)
            mov r5.xy, r2.yxyy
            mov r4.y, r5.z
          endloop 
          and r2.x, r5.x, r4.y
        else 
          mov r2.x, l(0)
        endif 
        or r2.x, r2.x, r4.x
        not r2.x, r2.x
      else 
        mov r2.x, l(-1)
      endif 
    else 
      mov r2.x, l(0)
    endif 
    if_z r2.x
      iadd r2.x, r2.w, l(1)
      mov r2.w, r2.x
      continue 
    endif 
    ld_structured_indexable(structured_buffer, stride=80)(mixed,mixed,mixed,mixed) r6.xyzw, r2.w, l(0), t0.xyzw
    ld_structured_indexable(structured_buffer, stride=80)(mixed,mixed,mixed,mixed) r7.xyzw, r2.w, l(48), t0.xyzw
    ld_structured_indexable(structured_buffer, stride=80)(mixed,mixed,mixed,mixed) r8.xyzw, r2.w, l(64), t0.xyzw
    ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r2.x, vThreadID.x, l(24), u2.xxxx
    add r5.yz, -r7.zzwz, r8.xxyx
    mad r5.yz, r2.xxxx, r5.yyzy, r7.zzwz
    add r4.x, -r2.x, l(1.000000)
    mul r5.w, r4.x, r8.w
    add r7.zw, -r5.yyyz, r8.xxxy
    dp2 r9.x, r4.zwzz, r4.zwzz
    dp2 r9.y, r7.xyxx, r7.xyxx
    sqrt r9.xy, r9.xyxx
    max r9.x, r9.y, r9.x
    lt r9.y, |r5.w|, l(0.000001)
    min r9.zw, r6.zzzw, r6.xxxy
    add r10.xyzw, r6.xyzw, -r7.zwzw
    min r11.xy, r10.zwzz, r10.xyxx
    min r11.xy, r9.zwzz, r11.xyxx
    max r6.xy, r6.zwzz, r6.xyxx
    max r6.zw, r10.zzzw, r10.xxxy
    max r11.zw, r6.zzzw, r6.xxxy
    min r6.xy, r8.xyxx, r5.yzyy
    add r6.xy, -r9.xxxx, r6.xyxx
    max r9.zw, r8.xxxy, r5.yyyz
    add r6.zw, r9.xxxx, r9.zzzw
    movc r6.xyzw, r9.yyyy, r11.xyzw, r6.xyzw
    max r9.zw, r0.zzzw, r3.zzzw
    add r6.xy, r6.xyxx, -cb0[8].yyyy
    lt r6.xy, r9.zwzz, r6.xyxx
    or r6.x, r6.y, r6.x
    min r9.zw, r0.zzzw, r3.zzzw
    add r6.yz, r6.zzwz, cb0[8].yyyy
    lt r6.yz, r6.yyzy, r9.zzwz
    or r6.y, r6.z, r6.y
    or r6.x, r6.y, r6.x
    if_z r6.x
      add r6.xy, -r0.zwzz, r3.zwzz
      add r6.zw, -r7.zzzw, r6.xxxy
      dp2 r6.z, r6.zwzz, r6.zwzz
      sqrt r6.z, r6.z
      mad r6.z, |r5.w|, r9.x, r6.z
      ge r6.w, r6.z, l(0.000000)
      if_nz r6.w
        mad r2.x, r8.w, r2.x, r8.z
        mul r6.w, |r5.w|, l(64.000000)
        round_pi r6.w, r6.w
        ftoi r6.w, r6.w
        iadd r6.w, r6.w, l(128)
        imin r6.w, r6.w, l(2048)
        add r9.xz, -r4.wwzw, r7.yyxy
        mad r4.x, r8.w, r4.x, r2.x
        sincos r4.x, r10.x, r4.x
        div r8.z, l(0.040000), |r5.w|
        min r8.z, r8.z, l(0.050000)
        mov r10.yz, r3.zzwz
        mov r8.w, l(0)
        mov r9.w, l(0)
        mov r10.w, l(0)
        loop 
          ige r11.x, r9.w, r6.w
          mov r10.w, l(0)
          breakc_nz r11.x
          mad r11.x, r5.w, r8.w, r2.x
          mad r11.yz, r7.zzwz, r8.wwww, r5.yyzy
          sincos r11.x, r12.x, r11.x
          mul r12.yz, r4.wwzw, r11.xxxx
          mad r13.x, r12.x, r4.z, -r12.y
          mad r13.y, r12.x, r4.w, r12.z
          add r12.yz, r11.yyzy, r13.xxyx
          mul r11.xw, r7.yyyx, r11.xxxx
          mad r13.x, r12.x, r7.x, -r11.x
          mad r13.y, r12.x, r7.y, r11.w
          add r11.xw, r11.yyyz, r13.xxxy
          mad r12.xw, r8.wwww, r6.yyyx, r0.wwwz
          add r13.xy, -r12.yzyy, r11.xwxx
          dp2 r11.x, r13.xyxx, r13.xyxx
          lt r11.w, l(0.000000), r11.x
          add r14.xy, -r12.yzyy, r12.wxww
          dp2 r14.x, r14.xyxx, r13.xyxx
          div_sat r11.x, r14.x, r11.x
          and r11.x, r11.x, r11.w
          mad r12.yz, r13.xxyx, r11.xxxx, r12.yyzy
          add r12.xw, -r12.zzzy, r12.xxxw
          dp2 r11.w, r12.xwxx, r12.xwxx
          sqrt r11.w, r11.w
          ge r14.x, r1.y, r11.w
          if_nz r14.x
            lt r14.x, l(0.000000), r11.w
            div r12.xw, r12.xxxw, r11.wwww
            mov r13.zw, -r13.yyyy
            dp2 r13.z, r13.xzxx, r13.xwxx
            rsq r13.z, r13.z
            mul r13.xy, r13.xyxx, l(1.000000, -1.000000, 0.000000, 0.000000)
            mul r13.xy, r13.zzzz, r13.xyxx
            movc r12.xw, r14.xxxx, r12.xxxw, r13.xxxy
            add r13.xy, -r11.yzyy, r12.yzyy
            mov r13.z, -r13.y
            mad r11.yz, r5.wwww, r13.zzxz, r7.zzwz
            add r11.yz, r6.xxyx, -r11.yyzy
            dp2 r11.y, r11.zyzz, r12.xwxx
            lt r11.y, r11.y, l(-0.000000)
            if_nz r11.y
              mad r11.xz, r11.xxxx, r9.xxzx, r4.wwzw
              mul r12.yz, r4.xxxx, r11.xxzx
              mad r13.x, r10.x, r11.z, -r12.y
              mad r13.y, r10.x, r11.x, r12.z
              add r11.xz, r8.xxyx, r13.xxyx
              add r12.y, -r8.w, l(1.000000)
              mul r12.y, r5.w, r12.y
              sincos r13.x, r14.x, r12.y
              mul r12.yz, r12.xxwx, r13.xxxx
              mad r13.x, r14.x, r12.w, -r12.y
              mad r13.y, r14.x, r12.x, r12.z
              add r11.xz, r3.zzwz, -r11.xxzx
              dp2 r11.x, r11.xzxx, r13.xyxx
              add r11.x, -r11.x, cb0[8].y
              iadd r11.z, r9.w, l(1)
              atomic_umax u1, l(3, 0, 0, 0), r11.z
              max r11.x, r11.x, l(0.000000)
              mad r11.xz, r13.xxyx, r11.xxxx, r3.zzwz
              mov r10.w, l(-1)
              mov r10.yz, r11.xxzx
              break 
            endif 
            if_nz r9.y
              iadd r11.x, r9.w, l(1)
              atomic_umax u1, l(3, 0, 0, 0), r11.x
              mov r10.yz, r3.zzwz
              mov r10.w, l(-1)
              break 
            endif 
            add r8.w, r8.z, r8.w
            or r11.x, r9.y, r11.y
          else 
            add r11.y, r11.w, -cb0[8].y
            div r11.y, r11.y, r6.z
            mul r11.y, r11.y, l(0.900000)
            max r11.y, r11.y, l(0.000001)
            add r8.w, r8.w, r11.y
            mov r11.x, l(0)
          endif 
          ge r11.y, r8.w, l(1.000000)
          if_nz r11.y
            iadd r11.z, r9.w, l(1)
            atomic_umax u1, l(3, 0, 0, 0), r11.z
            mov r10.yz, r3.zzwz
            mov r10.w, l(-1)
            break 
          endif 
          or r10.w, r11.x, r11.y
          iadd r9.w, r9.w, l(1)
        endloop 
        if_z r10.w
          atomic_iadd u1, l(2, 0, 0, 0), l(1)
          atomic_umax u1, l(3, 0, 0, 0), r6.w
          mov r10.yz, r3.zzwz
        endif 
      else 
        mov r10.yz, r3.zzwz
      endif 
    else 
      mov r10.yz, r3.zzwz
    endif 
    add r4.xz, -r3.zzwz, r10.yyzy
    dp2 r2.x, r4.xzxx, r4.xzxx
    lt r2.x, l(0.000000), r2.x
    if_nz r2.x
      store_structured u2.x, vThreadID.x, l(36), l(1)
    endif 
    mov r3.zw, r10.yyyz
    iadd r2.w, r2.w, l(1)
  endloop 
  mov r1.zw, r3.zzzw
  iadd r2.z, r2.z, l(1)
endloop 
store_structured u0.xy, vThreadID.x, l(0), r1.zwzz
ret 
// Approximately 268 instruction slots used
