//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer $Globals
// {
//
//   int _StreamHeadCount;              // Offset:    0 Size:     4 [unused]
//   int _StreamRenderingEnabled;       // Offset:    4 Size:     4 [unused]
//   float _SimulationTime;             // Offset:    8 Size:     4 [unused]
//   float _StreamMaximumGap;           // Offset:   12 Size:     4 [unused]
//   float _StreamMaximumLength;        // Offset:   16 Size:     4 [unused]
//   int _ParticleCapacity;             // Offset:   20 Size:     4
//   int _MaximumIngredients;           // Offset:   24 Size:     4 [unused]
//   int _IngredientCount;              // Offset:   28 Size:     4 [unused]
//   int _SpawnCount;                   // Offset:   32 Size:     4 [unused]
//   int _GridWidth;                    // Offset:   36 Size:     4 [unused]
//   int _GridHeight;                   // Offset:   40 Size:     4 [unused]
//   int _GridCellCount;                // Offset:   44 Size:     4 [unused]
//   int _BoundaryCount;                // Offset:   48 Size:     4 [unused]
//   int _VesselTriggerCount;           // Offset:   52 Size:     4
//   int _AgitatorCount;                // Offset:   56 Size:     4 [unused]
//   int _TechniqueTargetVessel;        // Offset:   60 Size:     4 [unused]
//   int _TechniqueMask;                // Offset:   64 Size:     4 [unused]
//   int _TechniqueStateMask;           // Offset:   68 Size:     4 [unused]
//   int _TransformTargetVessel;        // Offset:   72 Size:     4
//   int _SuspensionTargetVessel;       // Offset:   76 Size:     4 [unused]
//   int _SuspensionEnabled;            // Offset:   80 Size:     4 [unused]
//   int _ReferenceSolverEnabled;       // Offset:   84 Size:     4 [unused]
//   int _ImprovedPhysics;              // Offset:   88 Size:     4 [unused]
//   int _TransferTargetVessel;         // Offset:   92 Size:     4 [unused]
//   float _ReferenceParticleVolume;    // Offset:   96 Size:     4 [unused]
//   float _ReferenceRestDensity;       // Offset:  100 Size:     4 [unused]
//   float _ReferencePressureStiffness; // Offset:  104 Size:     4 [unused]
//   float _ReferenceNearPressureStiffness;// Offset:  108 Size:     4 [unused]
//   float _ReferenceViscosityRate;     // Offset:  112 Size:     4 [unused]
//   float _ReferenceMaximumTensionRatio;// Offset:  116 Size:     4 [unused]
//   float _ReferenceMaximumAcceleration;// Offset:  120 Size:     4 [unused]
//   float _ReferenceMaximumDisplacementRatio;// Offset:  124 Size:     4 [unused]
//   float _DeltaTime;                  // Offset:  128 Size:     4 [unused]
//   float _ParticleRadius;             // Offset:  132 Size:     4
//   float _SmoothingRadius;            // Offset:  136 Size:     4
//   float _RestDensity;                // Offset:  140 Size:     4 [unused]
//   float _DensityCompliance;          // Offset:  144 Size:     4 [unused]
//   float _LambdaEpsilon;              // Offset:  148 Size:     4 [unused]
//   float _ArtificialPressureStrength; // Offset:  152 Size:     4 [unused]
//   float _ArtificialPressureRadiusRatio;// Offset:  156 Size:     4 [unused]
//   float _BoundaryDensityScale;       // Offset:  160 Size:     4 [unused]
//   float _WallFriction;               // Offset:  164 Size:     4 [unused]
//   float _WallRestitution;            // Offset:  168 Size:     4 [unused]
//   float _SplashTransfer;             // Offset:  172 Size:     4 [unused]
//   float _SplashMinimumImpactSpeed;   // Offset:  176 Size:     4 [unused]
//   float _BottomImpactSpread;         // Offset:  180 Size:     4 [unused]
//   float _VelocityDamping;            // Offset:  184 Size:     4 [unused]
//   float _MaximumSpeed;               // Offset:  188 Size:     4 [unused]
//   float _ClosedVesselDampingRate;    // Offset:  192 Size:     4 [unused]
//   float _ClosedVesselMaximumRelativeSpeed;// Offset:  196 Size:     4 [unused]
//   float _Viscosity;                  // Offset:  200 Size:     4 [unused]
//   float _PassiveMixRate;             // Offset:  204 Size:     4 [unused]
//   float _AgitationMixRate;           // Offset:  208 Size:     4 [unused]
//   float _FullMixRelativeSpeed;       // Offset:  212 Size:     4 [unused]
//   float _MaximumMixPerSubstep;       // Offset:  216 Size:     4 [unused]
//   float _MinimumVisibleAlpha;        // Offset:  220 Size:     4 [unused]
//   float2 _Gravity;                   // Offset:  224 Size:     8 [unused]
//   float2 _GridOrigin;                // Offset:  232 Size:     8 [unused]
//   float2 _WorldMin;                  // Offset:  240 Size:     8 [unused]
//   float2 _WorldMax;                  // Offset:  248 Size:     8 [unused]
//   float2 _TransformDelta;            // Offset:  256 Size:     8
//   int _SwapA;                        // Offset:  264 Size:     4 [unused]
//   int _SwapB;                        // Offset:  268 Size:     4 [unused]
//   float2 _SwapDeltaA;                // Offset:  272 Size:     8 [unused]
//   float2 _SwapDeltaB;                // Offset:  280 Size:     8 [unused]
//   int _BoundaryGroupCount;           // Offset:  288 Size:     4
//   int _ImprovedVesselCount;          // Offset:  292 Size:     4 [unused]
//   float _ImprovedAreaPerMl;          // Offset:  296 Size:     4 [unused]
//   float _ImprovedKernelRatio;        // Offset:  300 Size:     4 [unused]
//   float _ImprovedCompliance;         // Offset:  304 Size:     4 [unused]
//   float _ImprovedCorrectionRatio;    // Offset:  308 Size:     4 [unused]
//   float _ImprovedWallDensity;        // Offset:  312 Size:     4 [unused]
//   float _ImprovedShear;              // Offset:  316 Size:     4 [unused]
//   float _ImprovedTension;            // Offset:  320 Size:     4 [unused]
//   float _ImprovedWetting;            // Offset:  324 Size:     4 [unused]
//
// }
//
// Resource bind info for _Boundaries
// {
//
//   struct BoundarySegment
//   {
//       
//       float2 a;                      // Offset:    0
//       float2 b;                      // Offset:    8
//       float2 velocityA;              // Offset:   16
//       float2 velocityB;              // Offset:   24
//       uint vesselId;                 // Offset:   32
//       uint flags;                    // Offset:   36
//       float2 localA;                 // Offset:   40
//       float2 localB;                 // Offset:   48
//       float2 startPosition;          // Offset:   56
//       float2 endPosition;            // Offset:   64
//       float startAngle;              // Offset:   72
//       float angleDelta;              // Offset:   76
//
//   } $Element;                        // Offset:    0 Size:    80
//
// }
//
// Resource bind info for _VesselTriggers
// {
//
//   struct VesselTrigger
//   {
//       
//       float2 center;                 // Offset:    0
//       float2 axisX;                  // Offset:    8
//       float2 axisY;                  // Offset:   16
//       float2 halfExtents;            // Offset:   24
//       uint vesselId;                 // Offset:   32
//       int priority;                  // Offset:   36
//       uint active;                   // Offset:   40
//       uint flags;                    // Offset:   44
//
//   } $Element;                        // Offset:    0 Size:    48
//
// }
//
// Resource bind info for _BoundaryGroups
// {
//
//   struct BoundaryGroup
//   {
//       
//       float2 minPosition;            // Offset:    0
//       float2 maxPosition;            // Offset:    8
//       float2 sweptMin;               // Offset:   16
//       float2 sweptMax;               // Offset:   24
//       uint first;                    // Offset:   32
//       uint end;                      // Offset:   36
//       uint contourFirst;             // Offset:   40
//       uint contourEnd;               // Offset:   44
//       uint vesselId;                 // Offset:   48
//
//   } $Element;                        // Offset:    0 Size:    52
//
// }
//
// Resource bind info for _Particles
// {
//
//   struct LiquidParticle
//   {
//       
//       float2 position;               // Offset:    0
//       float2 previousPosition;       // Offset:    8
//       float2 velocity;               // Offset:   16
//       float volumeMl;                // Offset:   24
//       float temperatureC;            // Offset:   28
//       uint vesselId;                 // Offset:   32
//       uint techniqueFlags;           // Offset:   36
//       uint stateFlags;               // Offset:   40
//       uint active;                   // Offset:   44
//       uint padding;                  // Offset:   48
//
//   } $Element;                        // Offset:    0 Size:    52
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// _Boundaries                       texture  struct         r/o             t0      1 
// _VesselTriggers                   texture  struct         r/o             t1      1 
// _BoundaryGroups                   texture  struct         r/o             t2      1 
// _Particles                            UAV  struct         r/w             u0      1 
// $Globals                          cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[19], immediateIndexed
dcl_resource_structured t0, 80
dcl_resource_structured t1, 48
dcl_resource_structured t2, 52
dcl_uav_structured u0, 52
dcl_input vThreadID.x
dcl_temps 6
dcl_thread_group 64, 1, 1
uge r0.x, vThreadID.x, cb0[1].y
if_nz r0.x
  ret 
endif 
ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r0.xyzw, vThreadID.x, l(0), u0.xyzw
ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r1.x, vThreadID.x, l(32), u0.xxxx
ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r1.y, vThreadID.x, l(44), u0.xxxx
if_z r1.y
  ret 
endif 
ine r1.y, r1.x, cb0[4].z
if_nz r1.y
  ine r1.y, r1.x, l(0)
  ine r1.z, cb0[4].z, l(0)
  if_nz cb0[4].z
    mov r2.xy, l(0,0,0,0)
    mov r1.w, l(0)
    loop 
      ige r2.z, r1.w, cb0[18].x
      breakc_nz r2.z
      ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r3.xyz, r1.w, l(40), t2.xyzx
      ine r2.z, r3.z, cb0[4].z
      if_nz r2.z
        iadd r2.z, r1.w, l(1)
        mov r1.w, r2.z
        continue 
      endif 
      mov r2.xy, r3.xyxx
      break 
    endloop 
  else 
    mov r2.xy, l(0,0,0,0)
  endif 
  mov r1.w, l(0)
  mov r2.z, r2.x
  loop 
    uge r2.w, r2.z, r2.y
    breakc_nz r2.w
    ld_structured_indexable(structured_buffer, stride=80)(mixed,mixed,mixed,mixed) r3.xy, r2.z, l(32), t0.xyxx
    ine r2.w, r3.x, cb0[4].z
    and r3.x, r3.y, l(8)
    ieq r3.x, r3.x, l(0)
    or r2.w, r2.w, r3.x
    if_nz r2.w
      iadd r2.w, r2.z, l(1)
      mov r2.z, r2.w
      continue 
    endif 
    ld_structured_indexable(structured_buffer, stride=80)(mixed,mixed,mixed,mixed) r3.xyzw, r2.z, l(0), t0.xyzw
    lt r4.xy, r0.yyyy, r3.ywyy
    ine r2.w, r4.y, r4.x
    add r3.zw, -r3.xxxy, r3.zzzw
    add r3.y, r0.y, -r3.y
    mul r3.y, r3.y, r3.z
    div r3.y, r3.y, r3.w
    add r3.x, r3.y, r3.x
    lt r3.x, r0.x, r3.x
    not r3.y, r1.w
    movc r3.x, r3.x, r3.y, r1.w
    movc r1.w, r2.w, r3.x, r1.w
    iadd r2.z, r2.z, l(1)
  endloop 
  and r1.z, r1.w, r1.z
  if_z r1.z
    add r1.z, cb0[8].y, cb0[8].z
    max r1.z, r1.z, l(0.000000)
    mov r2.xy, l(0,0x80000001,0,0)
    mov r1.w, l(0)
    loop 
      ieq r2.z, r2.x, l(0)
      ilt r2.w, r1.w, cb0[3].y
      and r2.z, r2.w, r2.z
      breakc_z r2.z
      ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r3.xyzw, r1.w, l(32), t1.xyzw
      ieq r2.z, r3.z, l(0)
      and r2.w, r3.w, l(2)
      ine r2.w, r2.w, l(0)
      ine r3.z, r3.x, cb0[4].z
      and r2.w, r2.w, r3.z
      or r2.z, r2.w, r2.z
      if_nz r2.z
        iadd r2.z, r1.w, l(1)
        mov r1.w, r2.z
        continue 
      endif 
      ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r4.xyzw, r1.w, l(0), t1.xyzw
      ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r5.xyzw, r1.w, l(16), t1.xyzw
      add r2.zw, r0.xxxy, -r4.xxxy
      dp2 r3.z, r2.zwzz, r4.zwzz
      dp2 r2.z, r2.zwzz, r5.xyxx
      add r4.xy, r1.zzzz, r5.zwzz
      ge r2.w, r4.x, |r3.z|
      ge r2.z, r4.y, |r2.z|
      and r2.z, r2.z, r2.w
      if_nz r3.x
        mov r3.zw, l(0,0,0,0)
        mov r2.w, l(0)
        loop 
          ige r4.x, r2.w, cb0[18].x
          breakc_nz r4.x
          ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r4.xyz, r2.w, l(40), t2.xyzx
          ine r4.z, r3.x, r4.z
          if_nz r4.z
            iadd r4.z, r2.w, l(1)
            mov r2.w, r4.z
            continue 
          endif 
          mov r3.zw, r4.xxxy
          break 
        endloop 
      else 
        mov r3.zw, l(0,0,0,0)
      endif 
      mov r2.w, l(0)
      mov r4.x, r3.z
      loop 
        uge r4.y, r4.x, r3.w
        breakc_nz r4.y
        ld_structured_indexable(structured_buffer, stride=80)(mixed,mixed,mixed,mixed) r4.yz, r4.x, l(32), t0.xxyx
        ine r4.y, r3.x, r4.y
        and r4.z, r4.z, l(8)
        ieq r4.z, r4.z, l(0)
        or r4.y, r4.z, r4.y
        if_nz r4.y
          iadd r4.y, r4.x, l(1)
          mov r4.x, r4.y
          continue 
        endif 
        ld_structured_indexable(structured_buffer, stride=80)(mixed,mixed,mixed,mixed) r5.xyzw, r4.x, l(0), t0.xyzw
        lt r4.yz, r0.yyyy, r5.yywy
        ine r4.y, r4.z, r4.y
        add r4.zw, -r5.xxxy, r5.zzzw
        add r5.y, r0.y, -r5.y
        mul r4.z, r4.z, r5.y
        div r4.z, r4.z, r4.w
        add r4.z, r4.z, r5.x
        lt r4.z, r0.x, r4.z
        not r4.w, r2.w
        movc r4.z, r4.z, r4.w, r2.w
        movc r2.w, r4.y, r4.z, r2.w
        iadd r4.x, r4.x, l(1)
      endloop 
      and r2.z, r2.w, r2.z
      ige r4.x, r3.y, r2.y
      and r2.z, r2.z, r4.x
      movc r2.xy, r2.zzzz, r3.xyxx, r2.xyxx
      iadd r1.w, r1.w, l(1)
    endloop 
  else 
    mov r2.x, cb0[4].z
  endif 
  ine r1.z, r2.x, cb0[4].z
  or r1.y, r1.z, r1.y
  if_nz r1.y
    ret 
  endif 
  mov r1.x, cb0[4].z
endif 
add r0.xyzw, r0.xyzw, cb0[16].xyxy
store_structured u0.xyzw, vThreadID.x, l(0), r0.xyzw
store_structured u0.x, vThreadID.x, l(32), r1.x
ret 
// Approximately 162 instruction slots used
