//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer $Globals
// {
//
//   int _StreamHeadCount;              // Offset:    0 Size:     4 [unused]
//   int _StreamRenderingEnabled;       // Offset:    4 Size:     4 [unused]
//   float _SimulationTime;             // Offset:    8 Size:     4 [unused]
//   float _StreamMaximumGap;           // Offset:   12 Size:     4 [unused]
//   float _StreamMaximumLength;        // Offset:   16 Size:     4 [unused]
//   int _ParticleCapacity;             // Offset:   20 Size:     4
//   int _MaximumIngredients;           // Offset:   24 Size:     4
//   int _IngredientCount;              // Offset:   28 Size:     4
//   int _SpawnCount;                   // Offset:   32 Size:     4 [unused]
//   int _GridWidth;                    // Offset:   36 Size:     4 [unused]
//   int _GridHeight;                   // Offset:   40 Size:     4 [unused]
//   int _GridCellCount;                // Offset:   44 Size:     4 [unused]
//   int _BoundaryCount;                // Offset:   48 Size:     4 [unused]
//   int _VesselTriggerCount;           // Offset:   52 Size:     4 [unused]
//   int _AgitatorCount;                // Offset:   56 Size:     4 [unused]
//   int _TechniqueTargetVessel;        // Offset:   60 Size:     4 [unused]
//   int _TechniqueMask;                // Offset:   64 Size:     4 [unused]
//   int _TechniqueStateMask;           // Offset:   68 Size:     4 [unused]
//   int _TransformTargetVessel;        // Offset:   72 Size:     4 [unused]
//   int _SuspensionTargetVessel;       // Offset:   76 Size:     4 [unused]
//   int _SuspensionEnabled;            // Offset:   80 Size:     4 [unused]
//   int _ReferenceSolverEnabled;       // Offset:   84 Size:     4 [unused]
//   int _ImprovedPhysics;              // Offset:   88 Size:     4 [unused]
//   int _TransferTargetVessel;         // Offset:   92 Size:     4 [unused]
//   float _ReferenceParticleVolume;    // Offset:   96 Size:     4 [unused]
//   float _ReferenceRestDensity;       // Offset:  100 Size:     4 [unused]
//   float _ReferencePressureStiffness; // Offset:  104 Size:     4 [unused]
//   float _ReferenceNearPressureStiffness;// Offset:  108 Size:     4 [unused]
//   float _ReferenceViscosityRate;     // Offset:  112 Size:     4 [unused]
//   float _ReferenceMaximumTensionRatio;// Offset:  116 Size:     4 [unused]
//   float _ReferenceMaximumAcceleration;// Offset:  120 Size:     4 [unused]
//   float _ReferenceMaximumDisplacementRatio;// Offset:  124 Size:     4 [unused]
//   float _DeltaTime;                  // Offset:  128 Size:     4 [unused]
//   float _ParticleRadius;             // Offset:  132 Size:     4 [unused]
//   float _SmoothingRadius;            // Offset:  136 Size:     4 [unused]
//   float _RestDensity;                // Offset:  140 Size:     4 [unused]
//   float _DensityCompliance;          // Offset:  144 Size:     4 [unused]
//   float _LambdaEpsilon;              // Offset:  148 Size:     4 [unused]
//   float _ArtificialPressureStrength; // Offset:  152 Size:     4 [unused]
//   float _ArtificialPressureRadiusRatio;// Offset:  156 Size:     4 [unused]
//   float _BoundaryDensityScale;       // Offset:  160 Size:     4 [unused]
//   float _WallFriction;               // Offset:  164 Size:     4 [unused]
//   float _WallRestitution;            // Offset:  168 Size:     4 [unused]
//   float _SplashTransfer;             // Offset:  172 Size:     4 [unused]
//   float _SplashMinimumImpactSpeed;   // Offset:  176 Size:     4 [unused]
//   float _BottomImpactSpread;         // Offset:  180 Size:     4 [unused]
//   float _VelocityDamping;            // Offset:  184 Size:     4 [unused]
//   float _MaximumSpeed;               // Offset:  188 Size:     4 [unused]
//   float _ClosedVesselDampingRate;    // Offset:  192 Size:     4 [unused]
//   float _ClosedVesselMaximumRelativeSpeed;// Offset:  196 Size:     4 [unused]
//   float _Viscosity;                  // Offset:  200 Size:     4 [unused]
//   float _PassiveMixRate;             // Offset:  204 Size:     4 [unused]
//   float _AgitationMixRate;           // Offset:  208 Size:     4 [unused]
//   float _FullMixRelativeSpeed;       // Offset:  212 Size:     4 [unused]
//   float _MaximumMixPerSubstep;       // Offset:  216 Size:     4 [unused]
//   float _MinimumVisibleAlpha;        // Offset:  220 Size:     4
//   float2 _Gravity;                   // Offset:  224 Size:     8 [unused]
//   float2 _GridOrigin;                // Offset:  232 Size:     8 [unused]
//   float2 _WorldMin;                  // Offset:  240 Size:     8 [unused]
//   float2 _WorldMax;                  // Offset:  248 Size:     8 [unused]
//   float2 _TransformDelta;            // Offset:  256 Size:     8 [unused]
//   int _SwapA;                        // Offset:  264 Size:     4 [unused]
//   int _SwapB;                        // Offset:  268 Size:     4 [unused]
//   float2 _SwapDeltaA;                // Offset:  272 Size:     8 [unused]
//   float2 _SwapDeltaB;                // Offset:  280 Size:     8 [unused]
//   int _BoundaryGroupCount;           // Offset:  288 Size:     4 [unused]
//   int _ImprovedVesselCount;          // Offset:  292 Size:     4 [unused]
//   float _ImprovedAreaPerMl;          // Offset:  296 Size:     4 [unused]
//   float _ImprovedKernelRatio;        // Offset:  300 Size:     4 [unused]
//   float _ImprovedCompliance;         // Offset:  304 Size:     4 [unused]
//   float _ImprovedCorrectionRatio;    // Offset:  308 Size:     4 [unused]
//   float _ImprovedWallDensity;        // Offset:  312 Size:     4 [unused]
//   float _ImprovedShear;              // Offset:  316 Size:     4 [unused]
//   float _ImprovedTension;            // Offset:  320 Size:     4 [unused]
//   float _ImprovedWetting;            // Offset:  324 Size:     4 [unused]
//
// }
//
// Resource bind info for _CompositionRead
// {
//
//   float $Element;                    // Offset:    0 Size:     4
//
// }
//
// Resource bind info for _IngredientVisuals
// {
//
//   struct IngredientVisual
//   {
//       
//       float4 color;                  // Offset:    0
//       uint inheritMixedColor;        // Offset:   16
//       uint padding0;                 // Offset:   20
//       uint padding1;                 // Offset:   24
//       uint padding2;                 // Offset:   28
//
//   } $Element;                        // Offset:    0 Size:    32
//
// }
//
// Resource bind info for _Particles
// {
//
//   struct LiquidParticle
//   {
//       
//       float2 position;               // Offset:    0
//       float2 previousPosition;       // Offset:    8
//       float2 velocity;               // Offset:   16
//       float volumeMl;                // Offset:   24
//       float temperatureC;            // Offset:   28
//       uint vesselId;                 // Offset:   32
//       uint techniqueFlags;           // Offset:   36
//       uint stateFlags;               // Offset:   40
//       uint active;                   // Offset:   44
//       uint padding;                  // Offset:   48
//
//   } $Element;                        // Offset:    0 Size:    52
//
// }
//
// Resource bind info for _ParticleColors
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// _CompositionRead                  texture  struct         r/o             t0      1 
// _IngredientVisuals                texture  struct         r/o             t1      1 
// _Particles                            UAV  struct         r/w             u0      1 
// _ParticleColors                       UAV  struct         r/w             u1      1 
// $Globals                          cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[14], immediateIndexed
dcl_resource_structured t0, 4
dcl_resource_structured t1, 32
dcl_uav_structured u0, 52
dcl_uav_structured u1, 16
dcl_input vThreadID.x
dcl_temps 3
dcl_thread_group 64, 1, 1
uge r0.x, vThreadID.x, cb0[1].y
if_nz r0.x
  ret 
endif 
ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r0.x, vThreadID.x, l(44), u0.xxxx
ieq r0.x, r0.x, l(0)
ige r0.y, l(0), cb0[1].w
or r0.x, r0.y, r0.x
if_nz r0.x
  store_structured u1.xyzw, vThreadID.x, l(0), l(0,0,0,0)
  ret 
endif 
mov r0.xyz, l(0,0,0,0)
loop 
  ige r0.w, r0.z, cb0[1].w
  breakc_nz r0.w
  imad r0.w, vThreadID.x, cb0[1].z, r0.z
  ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r0.w, r0.w, l(0), t0.xxxx
  max r0.w, r0.w, l(0.000000)
  add r0.y, r0.w, r0.y
  ld_structured_indexable(structured_buffer, stride=32)(mixed,mixed,mixed,mixed) r1.x, r0.z, l(16), t1.xxxx
  add r0.w, r0.w, r0.x
  movc r0.x, r1.x, r0.x, r0.w
  iadd r0.z, r0.z, l(1)
endloop 
lt r0.z, l(0.000010), r0.x
max r0.y, r0.y, l(0.000010)
movc r0.x, r0.z, r0.x, r0.y
mov r1.xyzw, l(0,0,0,0)
mov r0.y, l(0)
loop 
  ige r0.w, r0.y, cb0[1].w
  breakc_nz r0.w
  ld_structured_indexable(structured_buffer, stride=32)(mixed,mixed,mixed,mixed) r0.w, r0.y, l(16), t1.xxxx
  ine r0.w, r0.w, l(0)
  and r0.w, r0.w, r0.z
  if_nz r0.w
    iadd r0.w, r0.y, l(1)
    mov r0.y, r0.w
    continue 
  endif 
  ld_structured_indexable(structured_buffer, stride=32)(mixed,mixed,mixed,mixed) r2.xyzw, r0.y, l(0), t1.xyzw
  imad r0.w, vThreadID.x, cb0[1].z, r0.y
  ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r0.w, r0.w, l(0), t0.xxxx
  max r0.w, r0.w, l(0.000000)
  div r0.w, r0.w, r0.x
  mad r1.xyzw, r2.xyzw, r0.wwww, r1.xyzw
  iadd r0.y, r0.y, l(1)
endloop 
max r1.w, r1.w, cb0[13].w
mov_sat r1.xyzw, r1.xyzw
store_structured u1.xyzw, vThreadID.x, l(0), r1.xyzw
ret 
// Approximately 53 instruction slots used
