//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer $Globals
// {
//
//   int _StreamHeadCount;              // Offset:    0 Size:     4 [unused]
//   int _StreamRenderingEnabled;       // Offset:    4 Size:     4 [unused]
//   float _SimulationTime;             // Offset:    8 Size:     4 [unused]
//   float _StreamMaximumGap;           // Offset:   12 Size:     4 [unused]
//   float _StreamMaximumLength;        // Offset:   16 Size:     4 [unused]
//   int _ParticleCapacity;             // Offset:   20 Size:     4
//   int _MaximumIngredients;           // Offset:   24 Size:     4
//   int _IngredientCount;              // Offset:   28 Size:     4
//   int _SpawnCount;                   // Offset:   32 Size:     4 [unused]
//   int _GridWidth;                    // Offset:   36 Size:     4
//   int _GridHeight;                   // Offset:   40 Size:     4
//   int _GridCellCount;                // Offset:   44 Size:     4 [unused]
//   int _BoundaryCount;                // Offset:   48 Size:     4 [unused]
//   int _VesselTriggerCount;           // Offset:   52 Size:     4
//   int _AgitatorCount;                // Offset:   56 Size:     4 [unused]
//   int _TechniqueTargetVessel;        // Offset:   60 Size:     4 [unused]
//   int _TechniqueMask;                // Offset:   64 Size:     4 [unused]
//   int _TechniqueStateMask;           // Offset:   68 Size:     4 [unused]
//   int _TransformTargetVessel;        // Offset:   72 Size:     4 [unused]
//   int _SuspensionTargetVessel;       // Offset:   76 Size:     4 [unused]
//   int _SuspensionEnabled;            // Offset:   80 Size:     4 [unused]
//   int _ReferenceSolverEnabled;       // Offset:   84 Size:     4
//   int _ImprovedPhysics;              // Offset:   88 Size:     4 [unused]
//   int _TransferTargetVessel;         // Offset:   92 Size:     4 [unused]
//   float _ReferenceParticleVolume;    // Offset:   96 Size:     4 [unused]
//   float _ReferenceRestDensity;       // Offset:  100 Size:     4 [unused]
//   float _ReferencePressureStiffness; // Offset:  104 Size:     4 [unused]
//   float _ReferenceNearPressureStiffness;// Offset:  108 Size:     4 [unused]
//   float _ReferenceViscosityRate;     // Offset:  112 Size:     4 [unused]
//   float _ReferenceMaximumTensionRatio;// Offset:  116 Size:     4 [unused]
//   float _ReferenceMaximumAcceleration;// Offset:  120 Size:     4 [unused]
//   float _ReferenceMaximumDisplacementRatio;// Offset:  124 Size:     4 [unused]
//   float _DeltaTime;                  // Offset:  128 Size:     4 [unused]
//   float _ParticleRadius;             // Offset:  132 Size:     4
//   float _SmoothingRadius;            // Offset:  136 Size:     4
//   float _RestDensity;                // Offset:  140 Size:     4 [unused]
//   float _DensityCompliance;          // Offset:  144 Size:     4 [unused]
//   float _LambdaEpsilon;              // Offset:  148 Size:     4 [unused]
//   float _ArtificialPressureStrength; // Offset:  152 Size:     4 [unused]
//   float _ArtificialPressureRadiusRatio;// Offset:  156 Size:     4 [unused]
//   float _BoundaryDensityScale;       // Offset:  160 Size:     4 [unused]
//   float _WallFriction;               // Offset:  164 Size:     4
//   float _WallRestitution;            // Offset:  168 Size:     4
//   float _SplashTransfer;             // Offset:  172 Size:     4
//   float _SplashMinimumImpactSpeed;   // Offset:  176 Size:     4
//   float _BottomImpactSpread;         // Offset:  180 Size:     4
//   float _VelocityDamping;            // Offset:  184 Size:     4
//   float _MaximumSpeed;               // Offset:  188 Size:     4
//   float _ClosedVesselDampingRate;    // Offset:  192 Size:     4
//   float _ClosedVesselMaximumRelativeSpeed;// Offset:  196 Size:     4
//   float _Viscosity;                  // Offset:  200 Size:     4
//   float _PassiveMixRate;             // Offset:  204 Size:     4 [unused]
//   float _AgitationMixRate;           // Offset:  208 Size:     4 [unused]
//   float _FullMixRelativeSpeed;       // Offset:  212 Size:     4 [unused]
//   float _MaximumMixPerSubstep;       // Offset:  216 Size:     4 [unused]
//   float _MinimumVisibleAlpha;        // Offset:  220 Size:     4 [unused]
//   float2 _Gravity;                   // Offset:  224 Size:     8 [unused]
//   float2 _GridOrigin;                // Offset:  232 Size:     8
//   float2 _WorldMin;                  // Offset:  240 Size:     8
//   float2 _WorldMax;                  // Offset:  248 Size:     8
//   float2 _TransformDelta;            // Offset:  256 Size:     8 [unused]
//   int _SwapA;                        // Offset:  264 Size:     4 [unused]
//   int _SwapB;                        // Offset:  268 Size:     4 [unused]
//   float2 _SwapDeltaA;                // Offset:  272 Size:     8 [unused]
//   float2 _SwapDeltaB;                // Offset:  280 Size:     8 [unused]
//   int _BoundaryGroupCount;           // Offset:  288 Size:     4
//   int _ImprovedVesselCount;          // Offset:  292 Size:     4 [unused]
//   float _ImprovedAreaPerMl;          // Offset:  296 Size:     4 [unused]
//   float _ImprovedKernelRatio;        // Offset:  300 Size:     4 [unused]
//   float _ImprovedCompliance;         // Offset:  304 Size:     4 [unused]
//   float _ImprovedCorrectionRatio;    // Offset:  308 Size:     4 [unused]
//   float _ImprovedWallDensity;        // Offset:  312 Size:     4 [unused]
//   float _ImprovedShear;              // Offset:  316 Size:     4 [unused]
//   float _ImprovedTension;            // Offset:  320 Size:     4 [unused]
//   float _ImprovedWetting;            // Offset:  324 Size:     4 [unused]
//
// }
//
// Resource bind info for _CompositionRead
// {
//
//   float $Element;                    // Offset:    0 Size:     4
//
// }
//
// Resource bind info for _VelocityRead
// {
//
//   float2 $Element;                   // Offset:    0 Size:     8
//
// }
//
// Resource bind info for _Boundaries
// {
//
//   struct BoundarySegment
//   {
//       
//       float2 a;                      // Offset:    0
//       float2 b;                      // Offset:    8
//       float2 velocityA;              // Offset:   16
//       float2 velocityB;              // Offset:   24
//       uint vesselId;                 // Offset:   32
//       uint flags;                    // Offset:   36
//       float2 localA;                 // Offset:   40
//       float2 localB;                 // Offset:   48
//       float2 startPosition;          // Offset:   56
//       float2 endPosition;            // Offset:   64
//       float startAngle;              // Offset:   72
//       float angleDelta;              // Offset:   76
//
//   } $Element;                        // Offset:    0 Size:    80
//
// }
//
// Resource bind info for _VesselTriggers
// {
//
//   struct VesselTrigger
//   {
//       
//       float2 center;                 // Offset:    0
//       float2 axisX;                  // Offset:    8
//       float2 axisY;                  // Offset:   16
//       float2 halfExtents;            // Offset:   24
//       uint vesselId;                 // Offset:   32
//       int priority;                  // Offset:   36
//       uint active;                   // Offset:   40
//       uint flags;                    // Offset:   44
//
//   } $Element;                        // Offset:    0 Size:    48
//
// }
//
// Resource bind info for _BoundaryGroups
// {
//
//   struct BoundaryGroup
//   {
//       
//       float2 minPosition;            // Offset:    0
//       float2 maxPosition;            // Offset:    8
//       float2 sweptMin;               // Offset:   16
//       float2 sweptMax;               // Offset:   24
//       uint first;                    // Offset:   32
//       uint end;                      // Offset:   36
//       uint contourFirst;             // Offset:   40
//       uint contourEnd;               // Offset:   44
//       uint vesselId;                 // Offset:   48
//
//   } $Element;                        // Offset:    0 Size:    52
//
// }
//
// Resource bind info for _Particles
// {
//
//   struct LiquidParticle
//   {
//       
//       float2 position;               // Offset:    0
//       float2 previousPosition;       // Offset:    8
//       float2 velocity;               // Offset:   16
//       float volumeMl;                // Offset:   24
//       float temperatureC;            // Offset:   28
//       uint vesselId;                 // Offset:   32
//       uint techniqueFlags;           // Offset:   36
//       uint stateFlags;               // Offset:   40
//       uint active;                   // Offset:   44
//       uint padding;                  // Offset:   48
//
//   } $Element;                        // Offset:    0 Size:    52
//
// }
//
// Resource bind info for _LedgerAmounts
// {
//
//   float $Element;                    // Offset:    0 Size:     4
//
// }
//
// Resource bind info for _GridHeads
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
// Resource bind info for _GridNext
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
// Resource bind info for _FreeIndices
// {
//
//   uint $Element;                     // Offset:    0 Size:     4
//
// }
//
// Resource bind info for _FreeCount
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
// Resource bind info for _Statistics
// {
//
//   uint $Element;                     // Offset:    0 Size:     4
//
// }
//
// Resource bind info for _StreamParticles
// {
//
//   struct StreamParticle
//   {
//       
//       uint token;                    // Offset:    0
//       uint previousToken;            // Offset:    4
//       uint streamId;                 // Offset:    8
//       uint sourceId;                 // Offset:   12
//       float delay;                   // Offset:   16
//       float stepDt;                  // Offset:   20
//       float startFraction;           // Offset:   24
//       float birthTime;               // Offset:   28
//       float radius;                  // Offset:   32
//       uint detached;                 // Offset:   36
//       uint pending;                  // Offset:   40
//       uint padding;                  // Offset:   44
//
//   } $Element;                        // Offset:    0 Size:    48
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// _CompositionRead                  texture  struct         r/o             t0      1 
// _VelocityRead                     texture  struct         r/o             t1      1 
// _Boundaries                       texture  struct         r/o             t2      1 
// _VesselTriggers                   texture  struct         r/o             t3      1 
// _BoundaryGroups                   texture  struct         r/o             t4      1 
// _Particles                            UAV  struct         r/w             u0      1 
// _LedgerAmounts                        UAV  struct         r/w             u1      1 
// _GridHeads                            UAV  struct         r/w             u2      1 
// _GridNext                             UAV  struct         r/w             u3      1 
// _FreeIndices                          UAV  struct         r/w             u4      1 
// _FreeCount                            UAV  struct         r/w             u5      1 
// _Statistics                           UAV  struct         r/w             u6      1 
// _StreamParticles                      UAV  struct         r/w             u7      1 
// $Globals                          cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[19], immediateIndexed
dcl_resource_structured t0, 4
dcl_resource_structured t1, 8
dcl_resource_structured t2, 80
dcl_resource_structured t3, 48
dcl_resource_structured t4, 52
dcl_uav_structured u0, 52
dcl_uav_structured u1, 4
dcl_uav_structured u2, 4
dcl_uav_structured u3, 4
dcl_uav_structured u4, 4
dcl_uav_structured u5, 4
dcl_uav_structured u6, 4
dcl_uav_structured u7, 48
dcl_input vThreadID.x
dcl_temps 15
dcl_thread_group 64, 1, 1
uge r0.x, vThreadID.x, cb0[1].y
if_nz r0.x
  ret 
endif 
ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r0.xyzw, vThreadID.x, l(0), u0.xyzw
ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r1.xyzw, vThreadID.x, l(24), u0.xyzw
ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r2.xyz, vThreadID.x, l(40), u0.xyzx
ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r2.w, vThreadID.x, l(20), u7.xxxx
ge r2.w, l(0.000001), r2.w
ieq r3.x, r2.y, l(0)
or r2.w, r2.w, r3.x
and r3.x, r2.x, l(4)
ine r3.x, r3.x, l(0)
or r2.w, r2.w, r3.x
if_nz r2.w
  ret 
endif 
lt r3.xy, r0.xyxx, cb0[15].xyxx
or r2.w, r3.y, r3.x
lt r3.xy, cb0[15].zwzz, r0.xyxx
or r2.w, r2.w, r3.x
or r2.w, r3.y, r2.w
if_nz r2.w
  iadd r2.w, cb0[1].z, l(1)
  mov r3.x, l(0)
  loop 
    ige r3.y, r3.x, cb0[1].w
    breakc_nz r3.y
    imad r3.y, vThreadID.x, r2.w, r3.x
    bfi r3.y, l(30), l(2), r3.y, l(1)
    imad r3.z, vThreadID.x, cb0[1].z, r3.x
    ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r3.z, r3.z, l(0), t0.xxxx
    ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r3.w, r3.y, l(0), u1.xxxx
    mad r3.z, r1.x, r3.z, r3.w
    store_structured u1.x, r3.y, l(0), r3.z
    iadd r3.x, r3.x, l(1)
  endloop 
  imad r2.w, vThreadID.x, r2.w, cb0[1].z
  bfi r2.w, l(30), l(2), r2.w, l(1)
  ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r3.x, r2.w, l(0), u1.xxxx
  add r3.x, r1.x, r3.x
  store_structured u1.x, r2.w, l(0), r3.x
  store_structured u7.x, vThreadID.x, l(36), l(1)
  store_structured u0.x, vThreadID.x, l(32), l(0)
  store_structured u0.x, vThreadID.x, l(44), l(0)
  imm_atomic_iadd r3.x, u5, l(0, 0, 0, 0), l(1)
  ilt r2.w, r3.x, cb0[1].y
  if_nz r2.w
    store_structured u4.x, r3.x, l(0), vThreadID.x
  endif 
  atomic_iadd u6, l(1, 0, 0, 0), l(1)
  ret 
else 
  mov r3.x, r1.z
  mov r3.y, r2.y
endif 
add r2.yw, -r0.zzzw, r0.xxxy
ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r1.z, vThreadID.x, l(20), u7.xxxx
max r1.z, r1.z, l(0.000010)
div r2.yw, r2.yyyw, r1.zzzz
if_nz r3.x
  mov r4.y, l(0)
  mov r4.zw, l(0,0,0,0)
  mov r1.z, l(0)
  loop 
    ige r5.x, r4.w, cb0[3].y
    mov r1.z, l(0)
    breakc_nz r5.x
    ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r5.x, r4.w, l(32), t3.xxxx
    ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r5.yz, r4.w, l(40), t3.xxyx
    ine r5.y, r5.y, l(0)
    ieq r5.x, r3.x, r5.x
    and r5.x, r5.x, r5.y
    and r5.y, r5.z, l(1)
    ine r5.y, r5.y, l(0)
    and r5.x, r5.y, r5.x
    if_nz r5.x
      mov r4.z, l(-1)
      mov r1.z, l(-1)
      break 
    endif 
    iadd r4.x, r4.w, l(1)
    mov r4.zw, r4.yyyx
    mov r1.z, r5.x
  endloop 
  and r1.z, r4.z, r1.z
else 
  mov r1.z, l(0)
endif 
ieq r4.x, cb0[5].y, l(0)
if_z cb0[5].y
  add r4.yz, r0.xxyx, -cb0[14].zzwz
  div r4.yz, r4.yyzy, cb0[8].zzzz
  round_ni r4.yz, r4.yyzy
  ftoi r4.yz, r4.yyzy
  mul r4.w, cb0[8].z, cb0[8].z
  mul r5.x, r4.w, r4.w
  mul r5.x, r5.x, r5.x
  max r5.x, r5.x, l(0.000000)
  mul r5.x, r5.x, l(3.141593)
  div r5.x, l(4.000000), r5.x
  not r5.y, r1.z
  max r5.z, cb0[8].z, l(0.000010)
  mov r6.xyzw, l(0,0,0,0)
  mov r5.w, cb0[2].y
  mov r7.x, cb0[2].z
  mov r7.yz, l(0,0,0,0)
  mov r8.y, l(-1)
  loop 
    ilt r7.w, l(1), r8.y
    breakc_nz r7.w
    mov r8.zw, r6.xxxy
    mov r9.xy, r6.zwzz
    mov r7.w, r7.y
    mov r9.z, r7.z
    mov r8.x, l(-1)
    loop 
      ilt r9.w, l(1), r8.x
      breakc_nz r9.w
      iadd r10.xy, r4.yzyy, r8.xyxx
      ige r10.zw, r10.xxxy, l(0, 0, 0, 0)
      and r9.w, r10.w, r10.z
      ilt r10.z, r10.x, r5.w
      and r9.w, r9.w, r10.z
      ilt r10.z, r10.y, r7.x
      and r9.w, r9.w, r10.z
      if_z r9.w
        iadd r9.w, r8.x, l(1)
        mov r8.x, r9.w
        continue 
      endif 
      imad r9.w, r10.y, r5.w, r10.x
      ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r9.w, r9.w, l(0), u2.xxxx
      mov r10.xy, r8.zwzz
      mov r10.z, r7.w
      mov r11.xyz, r9.xyzx
      mov r10.w, r9.w
      mov r11.w, l(0)
      loop 
        ige r12.x, r10.w, l(0)
        ilt r12.y, r11.w, cb0[1].y
        and r12.x, r12.y, r12.x
        breakc_z r12.x
        iadd r11.w, r11.w, l(1)
        ine r12.x, r10.w, vThreadID.x
        if_nz r12.x
          ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r12.xy, r10.w, l(0), u0.xyxx
          ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r12.z, r10.w, l(32), u0.xxxx
          ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r13.xy, r10.w, l(40), u0.xyxx
          add r12.xy, r0.xyxx, -r12.xyxx
          dp2 r12.w, r12.xyxx, r12.xyxx
          ine r13.y, r13.y, l(0)
          and r13.x, r13.x, l(4)
          ieq r13.x, r13.x, l(0)
          and r13.x, r13.x, r13.y
          ieq r12.z, r3.x, r12.z
          and r12.z, r12.z, r13.x
          lt r13.x, r12.w, r4.w
          and r12.z, r12.z, r13.x
          if_nz r12.z
            mad r12.z, cb0[8].z, cb0[8].z, -r12.w
            mul r13.x, r12.z, r12.z
            mul r13.x, r5.x, r13.x
            mul r13.y, r12.z, r13.x
            ld_structured_indexable(structured_buffer, stride=8)(mixed,mixed,mixed,mixed) r13.zw, r10.w, l(0), t1.xxxy
            mad r10.xy, r13.zwzz, r13.yyyy, r10.xyxx
            mad r10.z, r13.x, r12.z, r10.z
            sqrt r12.z, r12.w
            lt r12.w, l(0.000010), r12.z
            div r14.xy, r12.xyxx, r12.zzzz
            add r12.xy, r2.ywyy, -r13.zwzz
            dp2 r12.x, r12.xyxx, r14.xyxx
            max r12.x, -r12.x, l(0.000000)
            lt r12.y, cb0[11].x, r12.x
            and r12.y, r5.y, r12.y
            div r12.z, r12.z, r5.z
            add r12.z, -r12.z, l(1.000000)
            max r12.z, r12.z, l(0.000000)
            umin r13.x, r10.w, vThreadID.x
            umax r13.y, r10.w, vThreadID.x
            imul null, r13.y, r13.y, l(0xac564b05)
            imad r13.x, r13.x, l(0x2c9277b5), r13.y
            and r13.x, r13.x, l(1)
            movc r13.x, r13.x, l(1.000000), l(-1.000000)
            mov r14.z, -r14.y
            mul r13.xy, r13.xxxx, r14.zxzz
            add r12.x, r12.x, -cb0[11].x
            mul r13.xy, r12.xxxx, r13.xyxx
            mad r13.xy, r13.xyxx, r12.zzzz, r11.xyxx
            add r13.z, r11.z, r12.z
            movc r12.xyz, r12.yyyy, r13.xyzx, r11.xyzx
            movc r11.xyz, r12.wwww, r12.xyzx, r11.xyzx
          endif 
        endif 
        ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r10.w, r10.w, l(0), u3.xxxx
      endloop 
      mov r8.zw, r10.xxxy
      mov r7.w, r10.z
      mov r9.xyz, r11.xyzx
      iadd r8.x, r8.x, l(1)
    endloop 
    mov r6.xy, r8.zwzz
    mov r6.zw, r9.xxxy
    mov r7.y, r7.w
    mov r7.z, r9.z
    iadd r8.y, r8.y, l(1)
  endloop 
  lt r4.y, l(0.000010), r7.y
  div r4.zw, r6.xxxy, r7.yyyy
  ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r5.x, vThreadID.x, l(20), u7.xxxx
  mov_sat r5.y, cb0[12].z
  add r5.y, -r5.y, l(1.000000)
  mul r5.z, r5.x, l(100.000000)
  log r5.y, r5.y
  mul r5.y, r5.y, r5.z
  exp r5.y, r5.y
  add r5.y, -r5.y, l(1.000000)
  add r4.zw, -r2.yyyw, r4.zzzw
  mad r4.zw, r5.yyyy, r4.zzzw, r2.yyyw
  movc r4.yz, r4.yyyy, r4.zzwz, r2.yywy
  lt r4.w, l(0.000010), r7.z
  div r5.yw, r6.zzzw, r7.zzzz
  mov_sat r5.x, cb0[10].w
  add r5.x, -r5.x, l(1.000000)
  log r5.x, r5.x
  mul r5.x, r5.x, r5.z
  exp r5.x, r5.x
  add r5.x, -r5.x, l(1.000000)
  mad r5.xy, r5.ywyy, r5.xxxx, r4.yzyy
  movc r2.yw, r4.wwww, r5.xxxy, r4.yyyz
endif 
mul r4.y, cb0[8].y, l(1.100000)
add r4.zw, -cb0[15].xxxy, cb0[15].zzzw
dp2 r4.z, r4.zwzz, r4.zwzz
sqrt r4.z, r4.z
add r4.z, r4.z, cb0[8].z
movc r4.z, r1.z, r4.z, r4.y
add r5.xy, r0.xyxx, -r4.zzzz
add r5.zw, r0.xxxy, r4.zzzz
mov r6.y, l(0)
mov r6.zw, l(0,0,0,0)
mov r4.w, r4.z
mov r7.xyw, l(0,0,0,0)
mov r8.x, l(0)
loop 
  ige r8.y, r8.x, cb0[18].x
  breakc_nz r8.y
  ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r9.xyzw, r8.x, l(0), t4.xyzw
  ge r8.yz, r5.zzwz, r9.xxyx
  and r8.y, r8.z, r8.y
  ge r8.zw, r9.zzzw, r5.xxxy
  and r8.z, r8.w, r8.z
  and r8.y, r8.z, r8.y
  if_z r8.y
    iadd r8.y, r8.x, l(1)
    mov r8.x, r8.y
    continue 
  endif 
  ld_structured_indexable(structured_buffer, stride=52)(mixed,mixed,mixed,mixed) r8.yz, r8.x, l(32), t4.xxyx
  mov r9.xy, r7.xyxx
  mov r9.zw, r6.zzzw
  mov r8.w, r4.w
  mov r10.x, r7.w
  mov r10.y, r8.y
  loop 
    uge r10.z, r10.y, r8.z
    breakc_nz r10.z
    ld_structured_indexable(structured_buffer, stride=80)(mixed,mixed,mixed,mixed) r10.zw, r10.y, l(32), t2.xxxy
    and r11.x, r10.w, l(16)
    if_z r11.x
      ine r10.z, r3.x, r10.z
      if_nz r10.z
        and r10.z, r10.w, l(2)
        ine r10.z, r10.z, l(0)
        if_nz r3.x
          mov r11.xy, l(0,0,0,0)
          mov r10.w, l(0)
          loop 
            ige r11.z, r11.y, cb0[3].y
            mov r10.w, l(0)
            breakc_nz r11.z
            ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r11.z, r11.y, l(32), t3.xxxx
            ieq r11.z, r3.x, r11.z
            ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r11.w, r11.y, l(44), t3.xxxx
            and r11.w, r11.w, l(2)
            ine r11.w, r11.w, l(0)
            and r11.z, r11.w, r11.z
            if_nz r11.z
              mov r11.x, l(-1)
              mov r10.w, l(-1)
              break 
            endif 
            iadd r6.x, r11.y, l(1)
            mov r11.xy, r6.yxyy
            mov r10.w, r11.z
          endloop 
          and r6.x, r11.x, r10.w
        else 
          mov r6.x, l(0)
        endif 
        or r6.x, r6.x, r10.z
        not r6.x, r6.x
      else 
        mov r6.x, l(-1)
      endif 
    else 
      mov r6.x, l(0)
    endif 
    if_z r6.x
      iadd r6.x, r10.y, l(1)
      mov r10.y, r6.x
      continue 
    endif 
    ld_structured_indexable(structured_buffer, stride=80)(mixed,mixed,mixed,mixed) r12.xyzw, r10.y, l(0), t2.xyzw
    add r13.xy, -r12.xyxx, r12.zwzz
    dp2 r6.x, r13.xyxx, r13.xyxx
    lt r10.z, l(0.000000), r6.x
    add r11.yz, r0.xxyx, -r12.xxyx
    dp2 r11.y, r11.yzyy, r13.xyxx
    div_sat r6.x, r11.y, r6.x
    and r6.x, r6.x, r10.z
    mad r11.yz, r13.xxyx, r6.xxxx, r12.xxyx
    add r11.yz, r0.xxyx, -r11.yyzy
    dp2 r10.z, r11.yzyy, r11.yzyy
    sqrt r10.z, r10.z
    ge r11.w, r10.z, r8.w
    if_nz r11.w
      iadd r11.w, r10.y, l(1)
      mov r10.y, r11.w
      continue 
    endif 
    ld_structured_indexable(structured_buffer, stride=80)(mixed,mixed,mixed,mixed) r12.xyzw, r10.y, l(16), t2.xyzw
    lt r11.w, l(0.000010), r10.z
    div r11.yz, r11.yyzy, r10.zzzz
    mov r13.zw, -r13.yyyy
    dp2 r13.z, r13.xzxx, r13.xwxx
    rsq r13.z, r13.z
    mul r13.xy, r13.yxyy, l(-1.000000, 1.000000, 0.000000, 0.000000)
    mul r13.xy, r13.zzzz, r13.xyxx
    movc r9.xy, r11.wwww, r11.yzyy, r13.xyxx
    add r11.yz, -r12.xxyx, r12.zzwz
    mad r9.zw, r6.xxxx, r11.yyyz, r12.xxxy
    mov r8.w, r10.z
    iadd r10.y, r10.y, l(1)
    mov r10.x, l(-1)
  endloop 
  mov r7.xy, r9.xyxx
  mov r6.zw, r9.zzzw
  mov r4.w, r8.w
  mov r7.w, r10.x
  iadd r8.x, r8.x, l(1)
endloop 
ge r4.y, r4.y, r4.w
and r4.y, r4.y, r7.w
if_nz r4.y
  add r4.yz, r2.yywy, -r6.zzwz
  dp2 r4.w, r4.yzyy, r7.xyxx
  lt r5.x, r4.w, l(0.000000)
  mov_sat r5.yz, cb0[10].zzyz
  add r5.y, r5.y, l(1.000000)
  mul r5.y, r4.w, r5.y
  mad r5.yw, -r5.yyyy, r7.xxxy, r4.yyyz
  add r6.x, r7.y, l(-0.200000)
  mul_sat r6.x, r6.x, l(1.250000)
  imad r6.y, vThreadID.x, l(0x2c9277b5), l(0xac564b05)
  and r6.y, r6.y, l(1)
  movc r6.y, r6.y, l(1.000000), l(-1.000000)
  not r8.x, r1.z
  and r4.x, r4.x, r8.x
  mov r7.z, -r7.x
  mul r8.xy, r6.yyyy, r7.yzyy
  mul r8.xy, -r4.wwww, r8.xyxx
  mov_sat r4.w, cb0[11].y
  mul r8.xy, r4.wwww, r8.xyxx
  mad r6.xy, r8.xyxx, r6.xxxx, r5.ywyy
  movc r4.xw, r4.xxxx, r6.xxxy, r5.yyyw
  movc r4.xy, r5.xxxx, r4.xwxx, r4.yzyy
  dp2 r4.z, r4.xyxx, r7.xyxx
  mul r5.xy, r7.xyxx, r4.zzzz
  mad r4.xy, -r4.zzzz, r7.xyxx, r4.xyxx
  ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r4.z, vThreadID.x, l(20), u7.xxxx
  add r4.w, -r5.z, l(1.000000)
  mul r4.z, r4.z, l(100.000000)
  log r4.w, r4.w
  mul r4.z, r4.w, r4.z
  exp r4.z, r4.z
  add r4.z, -r4.z, l(1.000000)
  add r4.z, -r4.z, l(1.000000)
  mad r4.xy, r4.xyxx, r4.zzzz, r5.xyxx
  add r2.yw, r4.xxxy, r6.zzzw
endif 
and r1.z, r1.z, r7.w
add r4.xy, -r6.zwzz, r2.ywyy
max r4.zw, cb0[12].xxxy, l(0.000000, 0.000000, 0.000000, 0.100000)
ld_structured_indexable(structured_buffer, stride=48)(mixed,mixed,mixed,mixed) r5.x, vThreadID.x, l(20), u7.xxxx
mul r4.z, -r4.z, r5.x
mul r4.z, r4.z, l(1.442695)
exp r4.z, r4.z
mul r4.xy, r4.zzzz, r4.xyxx
dp2 r4.z, r4.xyxx, r4.xyxx
sqrt r4.z, r4.z
lt r5.y, r4.w, r4.z
div r4.z, r4.w, r4.z
mul r4.zw, r4.zzzz, r4.xxxy
movc r4.xy, r5.yyyy, r4.zwzz, r4.xyxx
add r4.xy, r4.xyxx, r6.zwzz
movc r2.yw, r1.zzzz, r4.xxxy, r2.yyyw
mov_sat r1.z, cb0[11].z
add r1.z, -r1.z, l(1.000000)
mul r4.x, r5.x, l(100.000000)
log r1.z, r1.z
mul r1.z, r1.z, r4.x
exp r1.z, r1.z
add r1.z, -r1.z, l(1.000000)
add r1.z, -r1.z, l(1.000000)
mul r2.yw, r1.zzzz, r2.yyyw
dp2 r1.z, r2.ywyy, r2.ywyy
sqrt r1.z, r1.z
lt r4.x, cb0[11].w, r1.z
div r1.z, cb0[11].w, r1.z
mul r4.yz, r1.zzzz, r2.yywy
movc r4.xy, r4.xxxx, r4.yzyy, r2.ywyy
store_structured u0.xyzw, vThreadID.x, l(0), r0.xyzw
mov r4.zw, r1.xxxy
store_structured u0.xyzw, vThreadID.x, l(16), r4.xyzw
mov r3.z, r1.w
mov r3.w, r2.x
store_structured u0.xyzw, vThreadID.x, l(32), r3.xzwy
store_structured u0.x, vThreadID.x, l(48), r2.z
ret 
// Approximately 430 instruction slots used
